### ISSUE TITLE
Copying and pasting DB Editor parameter list value rows into excel and pasting back does not preserve the 'type'

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1204]
This may not be a bug technically since it is really an issue with Excel - but there may be value in addressing it as it would be a common task.

Use case:

I very often copy a number of parameter value rows and paste them into Excel. I then edit the values and the paste back into DB Editor. For example, I created a new object and I want to copy the parameters for another object, change their values, and paste them back in. This usually works nicely. However, it doesn't work for parameter list values or for truth values.  In the case of parameter list values, it is because when copied, the list value is encapsulated in double quotes. When pasted into Excel, the quotes are lost. Re-copying from Excel and attempting to paste back into db editor doesn't work because the quotes are now gone.

For parameter list values, there is a workaround, although it's a little awkward. Instead of pasting into excel, you can select "use text import wizard" and change the "text qualifier" to none. 

![image](https://user-images.githubusercontent.com/7080191/107011521-0adede00-6798-11eb-90b6-3e72f3b58e9a.png)

However, that doesn't work for truth values which end up being  interpreted by excel as booleans making it impossible to paste them back in.

It would be nice if this workflow worked more fluidly - if there was a simple solution, that would be great.

**Comment by manuelma** [comment]
I slightly changed the title to try to be more specific about what exactly doesn't work. I agree there's value on getting this to work.

**Comment by soininen** [comment]
If I remember correctly, when copying/cutting indexed parameter values in DB editor we write them to the clipboard as CSV tables which paste nicely into Excel. There is some code to convert Excel stuff back, too. Might be worth checking that code out. It might be useful for fixing this issue as well.
