### ISSUE TITLE
Keep tool sub-processes open in order to reuse them in further executions

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1222]
Some tools typically need to do a lot of initialization in order to run. It is the case for SpineOpt, and apparently for TUDelft's EMLab tool (to confirm).

To help with this, one may want to keep subprocesses open in order to reuse the results of initialization in further runs. This we accomplish by using Julia Jupyter kernels to execute our Julia tools. This issue is about doing the same for *any* Tool.

Cc @jimhommes

**Comment by jimhommes** [comment]
Thanks for tagging me.
Correct, I think the only addition I have is that it's not only about initialization, but some state of the process which can be returned to. (e.g. for every step of the process it's halted, some other process runs, and proceeds to the next step)

**Comment by jkiviluo** [comment]
@manuelma Something like this is working, right?

**Comment by manuelma** [comment]
Yeah, we can close.
