### ISSUE TITLE
Add support for creating sysimages for Julia tools

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1225]
Sysimages are great for speeding up julia tools which I think can help with new users. Details are [here](https://julialang.github.io/PackageCompiler.jl/dev/sysimages/#sysimages-1)

This will supersede the second task of #1217.

**Comment by PekkaSavolainen** [comment]
This should be done. We have the sysimage option in Julia Tool Properties. Please reopen if I missed something.

**Comment by manuelma** [comment]
I'm pretty sure this is broken at the moment and also, PackageCompiler.jl has become smarter since when we tried and implement this so the process should be simpler.

**Comment by soininen** [comment]
@manuelma I could give this a try if you don't mind.

**Comment by manuelma** [comment]
Thank you @soininen that would be great. Please let me know if you need any help trying to understand what's already in place.
