### ISSUE TITLE
Merge GdxExporter into Exporter

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1263]
So we can get rid of the former. It feels funny having the two of them,..

**Comment by jkiviluo** [comment]
Yes, there is bit of work there due to the peculiarities of GDX, so maybe not a high priority. @soininen of course can say more.

**Comment by soininen** [comment]
GdxExporter does some non-trivial transformations that are currently not available in Exporter:

- Reordering of entity classes and entities
- Replacing parameter indexes (e.g. time stamps) with user-defined labels
- Adding "empty" parameters (missing in GdxExporter too, but a much requested feature nonetheless)
- Merging single parameters (might actually work already in Exporter)

I have some ideas how to implement some of the above items and there are even some 'stubs' in spinedb_api's exporter_mappings for those.

**Comment by manuelma** [comment]
Sounds good. In my opinion it should be at least medium priority though. We shouldn't have something that says Gdx so 'above in our hierarchy'. Not even SpineOpt has that privilege. And two things that are called 'Exporter' also at the very top-level, it just feels odd.

But I agree that from the functionality point of view, it's not a big deal.

**Comment by soininen** [comment]
I'm planning to tackle the second item in the TODO list above as soon as I get the current exporter issues fixed.

**Comment by soininen** [comment]
The new Exporter now supports .gdx format, too. You need to specify the mappings in a particular way, though:
- Pivot tables cannot be exported
- A table name is required as it is used as the set, parameter or scalar name. Set one of the positions (usually object class, relationship class or parameter definition) to 'table name' or use a fixed table name
- Each column from left to right is used as a dimension. Empty gaps between columns will confuse Exporter.
- The last column should contain parameter values, if applicable.
- The first row is used to name the dimensions. Use 'column header' positions or give fixed header names accordingly. Note that `*` can be used as a fixed header name, too. The parameter value column doesn't need a header.
- Scalars use the table name as the scalar's name and the top left value in the table as the scalar value.

We definitely need to have a User guide entry for Exporter and diagnostics in the Specification editor to catch the most common problems.

**Comment by soininen** [comment]
Current plan on deprecating GdxExporter:

1. Hide GdxExporter form Main toolbar.
2. Make GdxExporter show a deprecation message as a exclamation notification with instructions on how to update to Exporter
3. Release 0.7 with deprecated GdxExporter
4. Make project file updater replace GdxExporters by Exporters when project is opened
5. Remove GdxExporter
6. Release 0.8 without GdxExporter

**Comment by manuelma** [comment]
If this goes well, seems like we'd have a protocol for deprecating project items if needed in the future. Good luck!

**Comment by manuelma** [comment]
What's the status on this? For example, do we need to keep maintaining `spinedb_api.spine_io.exporters.gdx`? Can we get rid of all the source code regarding GdxExporter? Would be good to speed up development.

**Comment by soininen** [comment]
As per the plan above, we're still at step 3 as 0.7 has not yet been released so the deprecation is not "official" yet. However, to my knowledge all relevant projects have been using the regular Exporter for quite some time now. As we've had the deprecation warning in-place for quite some time now and there are no plans on releasing 0.7 in the foreseeable future, I feel we could just skip step 3 and proceed with 4.
