### ISSUE TITLE
Importer: Clarify group membership 

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1324]
Currently importer mappings have item type for 'Object group'. In there one can define an object group and the members for the group using targets 'Group names' and 'Member names'. Even though you can select to add parameter values for this 'object group', it's not really functional, since parameter data for the object group is probably not in the same sheet as the group membership (they have different dimensionality). 

After discussing with @manuelma, we decided to drop the possibility to have parameter values in the 'object group' item type. When data for a object group needs to be imported, this should be done through object class. It would be good to make this more apparent for the user. (A message below the mapping options of Object group?)

ObjectGroupMapping is to be renamed to GroupMemberMapping (or similar). This also prepares for the possibility to have relationship groups.

There is a complicated case (where data is in the same sheet despite different dimensionality), which this issue will not cover:
![image](https://user-images.githubusercontent.com/40472544/112291851-2eeb7580-8c99-11eb-9b9b-9a0de01a7c51.png)

That has data for a situation where you can build max 100 MW of coal and gas, but together (as a group of units) they have a max of 150 MW. To be able to import one would require three mappings: 
- a mapping for group membership that takes member object name from column 1 and objectGroup name from column 2. If empty cells, the row is ignored.
- a mapping for object data, that takes object name from column 1 and data from column 3.
- a mapping for objectGroup data, that would be conditional: it activates only if column 1 is empty. Then it would take unitGroup name from column 2 and unitGroup data from column 3. This last one wouldn't work now. Could be made to work with: https://github.com/Spine-project/Spine-Toolbox/issues/1323

**Comment by manuelma** [comment]
We need to coordinate with Exporter here. What's the high-level idea and how do we translate it into something consistent?

**Comment by jkiviluo** [comment]
I think there is low effort for a reasonable outcome: just disallow adding parameter values for object groups (so that the user doesn't get confused and think that he can do it through object group --> the right place is using objects). And when the user has selected 'object group' as the 'item type', then there could a message below the selections saying that "Use 'object class' to import parameter data for 'object groups'".

**Comment by soininen** [comment]
@manuelma I'm assuming you're not working on this right now, right? I can do the work for both Importers and Exporters.
