### ISSUE TITLE
Get rid of gimlet

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1349]
I guess we can get rid of gimlet if we want. My idea is to allow Tool specifications to be created without any program files. For example, like this

```json
{
    "name": "gimlet",
    "tooltype": "executable",
    "includes": [],
    "description": "gimlet replacement",
    "inputfiles": [],
    "inputfiles_opt": [],
    "outputfiles": [],
    "cmdline_args": ["echo", "hello world!"],
    "execute_in_work": false,
    "includes_main_path": "."
}
```

When executed, the above will run `cmd echo "hello world!"` on windows.

This has multiple benefits as I see it:
1. We have less code to maintain
2. We can create e.g. python 'gimlet' tools, to run something like `python -c "hello world!"`
3. We automatically solve the issue of Gimlet not being able to advertise output files.

**Comment by jkiviluo** [comment]
Less code maintenance is always good.

When I look at the interfaces of Gimlet and Tool, it is easier to understand what Gimlet does. Could we achieve something like that with the tool as well and also allow easy shell commands? Should there be a simple radio button:

`( ) Simple shell command  ( ) Use a tool specification`

Command line arguments window could look like this:
```
Arguments from the tool specification:
  -f foo
  -b bar
Additional arguments for the tool instance:
  -o open the bar
```
 
Commands from the tool specification would be greyed out (since they should be changed in the tool specification editor to make clear you're changing something that can affect other tool instances too).

In the case of the Simple shell command, there would be no generic tool spec - each instance would have their own and it's not visible to the user. It would mean that the wrench icon would also be greyed out when the Simple shell command is selected - you cannot modify the tool spec. And the 'main program file / command' would be modifiable (which it would not be when 'Use a tool specification' is in effect).

**Comment by manuelma** [comment]
Thanks for the feedback @jkiviluo. If I understand what you're saying, it's essentially like allowing "anonymous" specifications. I guess all we need to add is that radio button, but I actually would prefer if the Specification combobox had these 'anonymous' specs by default: One for julia, python, gams and exec. The user select that one, and then enter the command line arguments in the view just below, and they're ready to press play.

> Command line arguments window could look like this:

I think they already look pretty much like that, don't they?

**Comment by jkiviluo** [comment]
> I think they already look pretty much like that, don't they?

Right, I modified my line of argument and left that accidentally unchanged. Yes, they already look like that, but a grey-out for the tool spec arguments when using the 'gimlet' type.

**Comment by jkiviluo** [comment]
> I actually would prefer if the Specification combobox had these 'anonymous' specs by default: One for julia, python, gams and exec.

Yes, that sounds great (should it link to the julia/python version?)

**Comment by jkiviluo** [comment]
BTW, I like radio buttons much more than drop-down lists. A list may be needed when there is indefinite amount of options, but here that should not be the case (if Julia/Python versions will be considered, they can have their own drop downs next to the Julia/Python radio buttons). The radio button list gives the (new) user faster understanding what is going on and what the options are. They are also faster to click.

**Comment by manuelma** [comment]
I think we can try that. Any thoughts @PekkaSavolainen @soininen @ererkka ?

- The idea is to introduce anonymous tool specs, one for Julia, Python, GAMS, and exec, that the user can select directly from radio buttons in the Tool properties UI, **without having to open the tool spec editor**. 
- These tool specs don't have any program files, so the command line arguments are directly passed to the 'executable' (e.g., `cmd dir`, `julia -e <some_code>`, etc.
- We get rid of Gimlet at this point.

**Comment by PekkaSavolainen** [comment]
I'm not sure why we would need these anonymous julia, python, and gams specs here. It would be simpler to leave the Python, Julia, etc. choice to the user. I.e. there should be a line edit for the command, where I can type `python script.py -some-args` this would mean that I want to use the python in my PATH. Then I can select a specific python by giving the whole path to the interpreter like this `C:\Python36\python.exe script.py -some-args`.

Also, what about the feature in Gimlet to choose whether to execute in a specific shell or not?

**Comment by soininen** [comment]
I'm strongly for getting the Tool's features that are currently missing in Gimlet to the hands of those who execute command line programs with as little code duplication as possible. These include input/output file handling, consistent item resource advertisement and command line arguments GUI. I don't have a strong opinion on how we do that, though. Having everything in Tool sounds plausible if we can stretch the user interface that far.

**Comment by manuelma** [comment]
> I'm not sure why we would need these anonymous julia, python, and gams specs here. It would be simpler to leave the Python, Julia, etc. choice to the user. I.e. there should be a line edit for the command, where I can type python script.py -some-args this would mean that I want to use the python in my PATH. Then I can select a specific python by giving the whole path to the interpreter like this C:\Python36\python.exe script.py -some-args.

Thanks. This is interesting. I guess the question would be then, why do we do it the way we do it for tool? You're saying that it's easier to pass the path to the (e.g.) python you want to run, but then again we go into great efforts to not do it that way in tool, and use the tooltype property to specify the python...

My inclination would be to respect that here. Also, we already have the interface to define command line arguments, where we can also use filepaths from incoming resource, so I don't like the idea of the line edit a whole lot.

> Also, what about the feature in Gimlet to choose whether to execute in a specific shell or not?

I forgot about this. You're referring to the choice between cmd.exe and powershell on Windows, right? I guess it would be good to have that choice in tool too. Does that feature justify an entire project item? I don't think so...

**Comment by manuelma** [comment]
> Having everything in Tool sounds plausible if we can stretch the user interface that far.

Thanks @soininen. I guess the other option to avoid the code duplication is to subclass more. At the moment Gimlet and Tool are very similar, but we don't reuse any code. We could have a `ToolABC` superclass and let both `Tool` and `Gimlet` subclass from there. Might be an option. On the other hand, I feel like having fewer project items also helps user learning the app.

**Comment by jkiviluo** [comment]
> I'm not sure why we would need these anonymous julia, python, and gams specs here. It would be simpler to leave the Python, Julia, etc. choice to the user. I.e. there should be a line edit for the command, where I can type python script.py -some-args this would mean that I want to use the python in my PATH.

The problem is that we cannot know what people have in path and what versions they use of these tools. E.g. Julia is moving fast. Also Python2 vs Python3 is a real issue. We need to be able control for that - at least when using tool specifications that are meant to be transferable and maintainable between projects. Maybe the simple gimlet type can live without 'language version control' (using PATH), but writing absolute paths in the project is behaviour that we should discourage.

**Comment by soininen** [comment]
I propose we follow the steps of GdxExporter when removing Gimlet:

1. Add a permanent notification to the item (exclamation icon) stating something in the vein "Gimlet is deprecated and will be removed in the future. Please replace this item with Tool configured to execute system commands." Update `CHANGELOG.md` accordingly 
2. Let the notification stay over the next release (0.7?)
3. After users have had time to react (release 0.8, 0.9?), remove Gimlet. Update `CHANGELOG.md` accordingly.

Additionally, we could communicate item deprecations/removals in news letters, forums etc.

**Comment by PekkaSavolainen** [comment]
Absolutely. Thanks @soininen for writing the steps down.

**Comment by ererkka** [comment]
Very professional approach 💯

**Comment by PekkaSavolainen** [comment]
Added the permanent notification, updated changelog, and removed Gimlet from the toolbar as per @soininen's proposal above. Executing Gimlet's still work as before. We just need to remove the Gimlet directory from spine-items when we are ready. Let me know If you still see the Gimlet icon in the toolbar.

**Comment by manuelma** [comment]
We also need to handle project.json files with Gimlets in it. This should be done by a project file version bump. There is something there for when we removed the Combiner. I think a good approach here would be to turn existing Gimlets into Executable tools so it's seamless for the user. Can we do that?

**Comment by PekkaSavolainen** [comment]
That would break the existing Gimlets and we don't want to do that yet.

**Comment by manuelma** [comment]
I'm not sure, my feeling is we should do it for them. We did it for Combiner and it worked great. When are we removing the spine-items/gimlet directory then? We'd need to wait till all users updated their projects, and we don't know when would that happen. What did we do for removing the gdx-exporter? I don't see an odd-looking `if item_type == "gdx-exporter"` in our code.

**Comment by manuelma** [comment]
I feel we're taking an easy path in circumstances we could do much better...

**Comment by PekkaSavolainen** [comment]
Gimlet is gone now and the Spine Toolbox project version has been updated to 10. When you open a project in Spine Toolbox, the upgrade process removes Gimlets and GdxExporters and their connections from the project automatically.
