### ISSUE TITLE
Autoreload

### ISSUE THREAD

**Issue by ptsavol** [spine-tools/Spine-Toolbox#1357]
Provide an option of loading IPython's `autoreload` extension automatically when a Python Console is launched. This option could e.g. be a checkbox in Tool properties.

There seems to be a similar package available for IJulia (https://github.com/malmaud/Autoreload.jl) as well. 

This enhancement idea came up in issue #1350.

**Comment by manuelma** [comment]
I never heard of Autoreload.jl, seems a bit abandoned. In Julia, people use Revise.jl for this purpose. I don't think we need any checkbox in the Tool properties for julia tools.
