### ISSUE TITLE
Validate internal state of project items before execution

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#1374]
We should precheck each executable item before executing a DAG in the Engine to bail out early if there are 'critical flaws' in the items. These 'critical flaws' include at least missing specifications, broken or non-existent urls, missing files, etc. Doing this on Engine's side instead of Toolbox is to make the Engine more self-sufficient e.g. for the headless mode. In practice, we could add a `validate_state()` method or similar to executable items which returns diagnostics information that the Engine can log.

This idea came up in https://github.com/Spine-project/Spine-Toolbox/issues/1371#issuecomment-819461720 by @soininen.

**Comment by PekkaSavolainen** [comment]
@soininen was this the idea?

**Comment by soininen** [comment]
I would rather do the validation on engine side because then it would work out-of-the-box with headless mode, too.

**Comment by PekkaSavolainen** [comment]
> 
> 
> I would rather do the validation on engine side because then it would work out-of-the-box with headless mode, too.

Sure, let's do that instead. I'll update the description.

**Comment by soininen** [comment]
@PekkaSavolainen is the description now clearer on the details?

**Comment by PekkaSavolainen** [comment]
This is kind of done with the new ready_to_execute() methods in ExecutableItems. Only implemented in Data Store and Tool (ExecutableItems) at the moment but there's still some TODOs left in Data Store. 

There's some refactoring work left since we may want to link ready_to_execute() with the _check_notifications() somehow to prevent duplicating code. We can probably leave that for 0.7.

**Comment by manuelma** [comment]
Nice. Although about this:

> There's some refactoring work left since we may want to link ready_to_execute() with the _check_notifications() somehow to prevent duplicating code. We can probably leave that for 0.7.

In my opinion, it's a bit better to delay the release freeze a couple of days and get this done if possible. I can also help if you need. TODOs in the code tend to be forgotten and might get obsolete too.

**Comment by PekkaSavolainen** [comment]
Ok, thanks but this is not so straight-forward as it seems because there's a lot of mini decisions to make. Not all notifications should prevent the item from being executed. For example, Data Connections now show a notification if there are no files attached to it but it should not prevent it from being executed. If you want to give it a shot, that would be very helpful.

**Comment by soininen** [comment]
I believe we have a working validation scheme now.
