### ISSUE TITLE
Datatype in Importer resetting arbitrarily, but definitely when mapping specification is changed

### ISSUE THREAD

**Issue by jimhommes** [spine-tools/Spine-Toolbox#1419]
Hi everyone,

Last week I've been using Spine extensively and I found some problems / exceptions / remarks that I'll be posting. Hope you can appreciate it.

To start off, when using the importer the datatypes seem to "reset" at certain events. It is hard to pin-point exactly when this happens, but I've had multiple times that I tried to execute and had to set all columns from floats to string again.

It definitely happens when the mapping specification is changed. To recreate you can try to create an importer, set column datatypes of parameter values to String and set the "Alternative" to a certain name. The columns that were String before will be set to float.

Nice to have: would it be possible to autodetect datatypes? If a column is all strings I still have to manually set it from float to string.

**Comment by jkiviluo** [comment]
I've taken notice of this behaviour too, but haven't got to around writing an issue. I think it happens when you change the mapping so that there are more 'dimensions' (maybe more accurately: more rows in the Mapping specification tab). It could keep whatever information still fits the new set of rows, but it doesn't. Of course, when you decrease the number of rows in the Mappings tab, then that information is lost.

**Comment by jkiviluo** [comment]
Maybe that was off topic for this issue and should be made into another. Hopefully more related to this one: https://github.com/Spine-project/Spine-Toolbox/issues/1327 - I think it's not resolved either.

**Comment by manuelma** [comment]
I think we should disable data type detection and leave it entirely to the user.

**Comment by soininen** [comment]
> Perhaps we need a system to define the type for multiple columns at once.

This is alredy somewhat  possible: right clicking a column's header cell will open a popup menu with 'Set all data type to...' option. It is a bit clunky and perhaps not very discoverable, though.

**Comment by manuelma** [comment]
Thanks @soininen I had forgotten about that. It's not bad, although ideally I would like to have more options than all or nothing if you know what I mean. I'm not sure how to implement it though... At least on my ubuntu desktop one can 'select' headers and then show the header context menu without loosing the selection. So maybe there could be a context menu entry to set datatypes for all selected headers?

**Comment by manuelma** [comment]
Ok, no answer so no problem. I'll go with my gut, wish me luck.

**Comment by jkiviluo** [comment]
I think this is fine for now. I will close the issue, but please re-open and state what is the remaining issue if you feel like there is something.
