### ISSUE TITLE
Remark: Color marking errors in the importer

### ISSUE THREAD

**Issue by jimhommes** [spine-tools/Spine-Toolbox#1422]
I have some remarks regarding the marking red of incorrectly filled in parameters in the importer.

1) When defining parameter values for the first time, the default datatype is set to float (even when wrong). In this instance the columns are not coded red and it gives the impression everything is alright. It causes frustration when moving on, executing and then finding out the datatypes were set incorrectly. 

2) In the specification mapping (see screenshot) if a value is missing or incorrect, the filled in values are marked red. Wouldn't it make more sense to mark the missing or incorrectly filled in fields red? Especially when it gets more complex (like importing relationship classes) it gets hard to understand what is wrong.

![python_2021-05-31_18-10-08-424_51mdxAyVXp](https://user-images.githubusercontent.com/5991344/120219476-97c41080-c23b-11eb-9a63-3565ee7bb71e.png)

**Comment by manuelma** [comment]
About 1, if the values are not convertible to float, they should be marked red. Is that not the case? Also what do you mean by 'wrong'? What's the correct datatype? Are you expecting Spine Toolbox to figure it out on its own?

About 2, I'm not sure what you mean. For example, in your screenshoot, what should be the red fields? Also when you hover a red field you get a tooltip that indicates which field is causing the error. Fields are not invalid in themselves, they just become invalid sometimes after other fields are set.

**Comment by jimhommes** [comment]
I'm sorry, I guess the description could have been a bit more clear.

1. Say I'm defining parameter values which are strings. The default datatype for parameter values are floats. When I open a new mapping, right-click and define a row as object names and a column as parameter names, the pivoted values (parameter values) will be marked with the light-blue "Parameter values" and are also set to the float datatype. If I change between sheets, the values will be marked red correctly.
2. In the screenshot the fields are marked red because the Object Class Names hasn't been set. So my suggestion is to mark this field red, as it's the missing required field. I wasn't aware of the tooltip, I'll have a look there!

**Comment by manuelma** [comment]
Thanks @jimhommes 

It looks like issue number 1 is a refreshing problem? We do mark values in red if not convertible, but we don't do it immediately when the mapping is defined?

About issue number 2, we could try and do it as you suggest. Maybe it's better. It looks like users don't normally look for tool tips, so we can't really rely on it?

**Comment by jimhommes** [comment]
Yes, your description of issue 1 is exactly right.

Regarding issue 2, of course I don't speak for the entire software community, but I only encounter tool tips by accident. Maybe it should show up faster? Another suggestion is to have a help or  description box, which shows a description of what your mouse is hovering over.

**Comment by manuelma** [comment]
Yes, thanks very much @jimhommes that's clear now. I think I can try something out here.

**Comment by jkiviluo** [comment]
> Another suggestion is to have a help or description box, which shows a description of what your mouse is hovering over.

Good idea @jimhommes Picking this to a new issue: https://github.com/spine-tools/Spine-Toolbox/issues/2783

**Comment by jkiviluo** [comment]
Very likely fixed by now.
