### ISSUE TITLE
Importer block can only specify an import for one file and will overwrite the other import when tried

### ISSUE THREAD

**Issue by jimhommes** [spine-tools/Spine-Toolbox#1423]
The Importer Properties suggest that it's possible to define imports for multiple excel fiels at a time. See screenshot.
![python_2021-05-31_18-14-29-744_OIbAQgoj5M](https://user-images.githubusercontent.com/5991344/120220129-90e9cd80-c23c-11eb-8518-0e2d8502abf3.png)

When just trying out right now I found that if the files have the same Sheet name the same import will reflect on both Sheets.
If not, if you have defined an import for file 1 and start defining an import for file 2, the import for file 1 will disappear without a prompt.

I was so sad to find this out because it had overwritten the largest import I have created thus far.

**Comment by jkiviluo** [comment]
First, I wonder if you have the latest master and the related packages. Remember this https://github.com/Spine-project/Spine-Toolbox#upgrading  

I wonder if these would resonate:
https://github.com/Spine-project/Spine-Toolbox/issues/1141
https://github.com/Spine-project/Spine-Toolbox/issues/1381

**Comment by jimhommes** [comment]
Yes, I have ran the pip install every time I've pulled from master.

**Comment by soininen** [comment]
Importer contains only a single set of mappings that are applied to all available files. You cannot define different mappings for different files unless you make a datapackage and I think we only support .csv files then. In the past Importer had separate mappings for each input file but that model had certain other issues. If you have two different Excel files I suggest you make two Importers, one for each file.

**Comment by jimhommes** [comment]
I understand the current implementation, I just wanted to note that:

1) The layout suggests that multiple mappings is possible, and
2) There is no prompt when an import is overwritten.

My current implementation is as you suggested with multiple import blocks.

**Comment by manuelma** [comment]
The problem is file2 doesn't have the same sheets as file1. So after you've defined the import for file1 and define something for file2, the mappings for the *now absent* sheets are erased. But I think we can keep them, even if the 'present' file doesn't have those sheets.

And when the importer runs, it will see that there are mappings defined both for the sheets of file1 and file2, so it can apply every mapping where it corresponds. How do you like this solution?

**Comment by manuelma** [comment]
Another option would be to check that all the files coming to the Importer item have the same 'structure'. We can perform this check when the user creates arrows, and show an exclamation point notification if the check doesn't pass.

And the check will check that all the files are of the same type, and have the same 'tables' (sheets in case of excel, csv files in the case of datapackage).

Does that sound reasonable?

**Comment by soininen** [comment]
> The problem is file2 doesn't have the same sheets as file1. So after you've defined the import for file1, and then define something for file2, the mappings for the now absent sheets are erased. But I think we can keep them, even if the 'present' file doesn't have those sheets.

This sounds like a logical solution and analogous to how Data Transformer and Exporter work.

**Comment by jkiviluo** [comment]
Yes, that's much better, but I think a more through solution is proposed in https://github.com/Spine-project/Spine-Toolbox/issues/1141. Maybe we don't have time for that right now, but I feel exporter is quite confusing and it would be nice to make it better.

**Comment by manuelma** [comment]
Ok, I will try to implement that solution then. I think we could also have a check that all the ticked files are of the same type and consistent with the importer spec.

I know users that learn the Importer quite quickly, so I don't know it's *that* confusing?

**Comment by jkiviluo** [comment]
We will try address the issue by solving a more comprehensive issue: https://github.com/spine-tools/Spine-Toolbox/issues/1141
