### ISSUE TITLE
Possibility to provide more data per Object Parameter or import description?

### ISSUE THREAD

**Issue by jimhommes** [spine-tools/Spine-Toolbox#1425]
At the moment I'm using the "Alternative Names" in the Import specification to indicate the clock tick of the model. It's nice because you can filter per clock tick. 

Now I would like to define a priority per parameter when importing it in my own code. At the moment, I'm using the "Parameter description" for this. I have to set this manually through the database editor however. 

My question is, is it possible to import more data per parameter? And access it in such a way through the code? This question is also a follow-up to the metadata issue I created, as this is the reason why I was trying it out.

**Comment by jkiviluo** [comment]
What do you mean by clock tick? The datetime of the import?

**Comment by jimhommes** [comment]
In the model there is a variable indicating what year is being simulated (from year 0 to N). So it's basically an integer. This way you can filter when what's been added.

**Comment by manuelma** [comment]
> priority per parameter

**Comment by jimhommes** [comment]
There are two problems with the alternative rank:
1. I'm already using it for the clock indication of the model of when the value was added
2. The rank is a property of a parameter value and I'm looking for a property of the parameter itself

In my code I'm importing all objects from the SpineDB to run my model. This is straightforward except for the fact that there are interdependencies between the objects which mean that here must be a sequence in loading. In short, if Object 1 requires Object 2 then Object 2 must be loaded before Object 1. 

My code iterates over all parameter names and thus has access to their description, which is why I've used that now. I do think it's best if this priority is set in Spine, either through the import or somewhere else. It would also work if there is some possibility of creating more fields per object parameter, which is passed to the code.

**Comment by manuelma** [comment]
This is very interesting, thanks @jimhommes 

May I ask you a follow-up question, what does it mean that object1 'requires' object2? Would it be possible to define an object parameter called `priority`, so an object that needs to be loaded before another has a higher 'priority'?

**Comment by jimhommes** [comment]
Of course. In my Python model an example would be a Power Plant (object 1) having an Energy Producer as owner (object 2). In the Excel file which is loaded there is a reference to a unique name (PP1 -> Owner - EnergyProducerA), and when loaded in the code the repository (central class containing all loaded objects) will look up the direct reference to the Python object. This instead of storing a String and having to look up the String every time.

I've thought about this structure defining an object parameter. However, it can only be defined as a value, and the loading process first sorts the values based on their alternative rank (the clock tick, so most recently added) and then picks out the most recent value based on the object parameters. So, I'd like to have access to the priority before checking the values itself.

**Comment by jkiviluo** [comment]
I don't grasp the issue still. Maybe it could be resolved using map as a parameter value (where the order would be established). Anyway, this is more than a year ago and I'll close the issue. Can be re-opened if there still is an issue.
