### ISSUE TITLE
Importer does not support importing Excel data when column number is >100?

### ISSUE THREAD

**Issue by eriharriso** [spine-tools/Spine-Toolbox#1433]
It seems the importer previewer shows up to 99-100 columns per sheet: trying to move towards higher column numbers in the previewer just brings the user back to column 1.

I tried unsuccessfully to import relationship class parameters from a higher column number (134 in this case) to an sqlite database: while there were no reported errors, the relationship class pivot table was not then visible in the data store editor and I couldn't access the info. I would need to import data from column numbers up to ~300-400: is this or could it be made possible without editing the original Excel files?

**Comment by eriharriso** [comment]
Update: now I successfully imported parameters from column 259. It seems that importing with large column numbers is therefore possible, I do not know what the problem was earlier, unfortunately. The main issue here would then be being able to access these columns with the source data previewer (which would also allow for easier setting of data types).

**Comment by manuelma** [comment]
There was a hardcoded limit on the amount of columns shown, for some mysterious reason. I just removed it so now you can define mappings on any columns. Will close now, please reopen if I missed something.

(You need to update requirements to see the fix, just in case.)

**Comment by soininen** [comment]
> There was a hardcoded limit on the amount of columns shown, for some mysterious reason. I just removed it so now you can define mappings on any columns.

I think the limit was a workaround to make the preview table usable when you have > 8000 columns (Backbone Excel files...). Can we not have an optional user settable cut-off like we have in Exporter?

**Comment by PekkaSavolainen** [comment]
See also #923. Looks like a duplicate.

**Comment by manuelma** [comment]
> I think the limit was a workaround to make the preview table usable when you have > 8000 columns (Backbone Excel files...). Can we not have an optional user settable cut-off like we have in Exporter?

Ah, I didn't know that, thanks! I was thinking that we should rather remove the cut-off in Exporter and rely on lazy loading. It's a better user experience overall. How bad is it to populate a model with 8000 columns? Anybody has an example of such excel files?

**Comment by soininen** [comment]
> rely on lazy loading

Somehow I had the impression that only rows can be loaded lazily but looking at `fetcthMore()` I see that I have been wrong all along. Lazy loading would indeed be better approach.

I believe @jkiviluo might be able to provide exemplary wide Excel files and explain the issues with them in more detail.

**Comment by manuelma** [comment]
Thanks very much for the input guys.

I tested opening a file with the maximum number of columns (16384) and it takes about 5 seconds in my machine. I'll try to optimize it with lazy loading.

`fetchMore()` doesn't distinguish between rows and columns, so apparently one needs to fetch both rows and columns when it's called. A little inconvenient but not the end of the world.

**Comment by jkiviluo** [comment]
I think this works fine nowadays
