### ISSUE TITLE
Autofill when writing

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1435]
It's really nice when you start typing a word in a cell, that the options become visible as a list below the cell. However, the regular behavior is that if you press 'tab' then the first option is written and you move to the next cell. I hope that could work in Toolbox.

Also, when pressing down-arrow, it goes directly to the 2nd entry, which is not intuitive. At least to me.

**Comment by manuelma** [comment]
I implemented that thing based on google's search bar. The behavior attempts to mimic that. The implementation is a bit delicate as it messes up with Qt's own defaults, but I think we can give it a shot so it behaves like described above.

**Comment by jkiviluo** [comment]
I'm keeping this in 0.7 since it should be a small thing. If you disagree, please move to 1.0.
