### ISSUE TITLE
Execute shell commands by using Executable Tool specs

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#1464]
Add support for selecting a shell (or no shell) and a command for Executable Tool specs. This should be implemented by making a new optional widget (see `spine_items.tool.widgets.tool_spec_optional_widgets.py`) that is only shown in Tool spec editor when `Executable` Tool spec type is selected. When this is implemented, Gimlet becomes obsolete and we can get rid of it (#1349).

**Comment by PekkaSavolainen** [comment]
Should be done now. You can set a command and select a shell for Executable Tool Specs. Setting a command overrides the main program file, i.e. if a command is set, the program files are not taken into account. Input files, optional input files and output files should work with a shell command just like with other Tool Specs.

There seems to be some problems with importer's mvcmodel tests. Don't know what that is about because I did not touch the Importer at all.

**Comment by PekkaSavolainen** [comment]
**spine-items** tests in class TestSourceDataTableModel() `test_row_type_checking()` and `test_column_type_checking_produces_error()` fail. `test_row_type_checking()` fails because it tries to cast a string "2018-01-01" to integer in `duration_to_relativedelta()` (line 74) in file `spinedb_api/parameter_value.py`. @soininen Is this a case of incorrect input data for the tests?

**Comment by soininen** [comment]
Looks like the test fails because `MinimalTableModel` nowadays sorts its contents in `reset_model()`. Makes me feel the change breaks Importer's source preview but I need to investigate more.
