### ISSUE TITLE
`is_active` improvements

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1517]
Two nice additional steps would be:

- Syntax to implement the filter when running without toolbox
- Auto/default application of the object_activity_control filter when detected?
Thoughts?

**Comment by DillonJ** [comment]
The more I think about it, the more sense I think it makes to auto-apply the object_activity_control tool filter. If we think about it logically:
 - If there is no object_activity_control tool filter in the DB, then there is nothing to worry about
 - If there is an object_activity_control tool filter in the DB and there are no is_active parameters set to false in the DB, then there is nothing to worry about
 - If there is an object_activity_control tool filter in the DB and there are is_active parameters set to false, then there is a clear intention that those objects be excluded from the dataset and we should respect that.

**Comment by manuelma** [comment]
I don't think toolbox should auto-apply filters. We can auto-apply the tool filter in SpineOpt too, I think that's better. And in that case, I would rename the tool from `object_activity_control` to `spine_opt`.

**Comment by jkiviluo** [comment]
I suppose this will be superseded by the alternative functionality for entities.

**Comment by manuelma** [comment]
Yes, me too. I feel the migration from tool-feature-method plus is_active to the alternative entity will be a bit painful... we need to think about it carefully.
