### ISSUE TITLE
Remove SQLAlchemy from Spine Items

### ISSUE THREAD

**Issue by ghost** [spine-tools/Spine-Toolbox#1521]
This was discussed previously. Maybe Spine Items could rely only on Spine DB API on this.

Modules to consider: `data_store.utils` and `view.view`.

**Comment by jkiviluo** [comment]
@PekkaSavolainen what's the status here`?

**Comment by PekkaSavolainen** [comment]
Not sure what this was about. spine-items imports things from sqlalchemy so it is a requirement at the moment.
