### ISSUE TITLE
Python Tool fails to run simple scripts

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1530]
There is something wonky about the way Tool executes Python scripts at least when 'Basic console' is used. I have this perfectly fine Python script:

```
import sys

def print_args():
    print(sys.argv)

print_args()
```

Trying to execute the above in a Tool produces this exception:

```
File "<stdin>", line 1, in <module>
Traceback (most recent call last):
NameError: name 'sys' is not defined
print(sys.argv)
File "script.py", line 4, in print_args
print_args()
File "script.py", line 6, in <module>
```

Looks like it is not possible to use imported modules in functions, classes etc.

**Comment by soininen** [comment]
@manuelma I think I've a fix for this. Hopefully you haven't started working on it yet.

**Comment by PekkaSavolainen** [comment]
I was testing this a little bit and got your example script in the issue description working. However, my solution does not work like this though

```python
import sys

def print_args():
    print(sys.argv)

if __name__ == "__main__":
	sys.exit(print_args())
```

I'll stop working on this and I'm excited to see your (@soininen) solution here.

**Comment by soininen** [comment]
Should be fixed now. Hopefully I didn't break anything else in the meantime...

**Comment by PekkaSavolainen** [comment]
@soininen Does this work in Basic Console on your machine?

```python
import sys


def print_args():
	print(sys.argv)


if __name__ == "__main__":
 	sys.exit(print_args())
```

For me it prints the sys.argv fine but the Tool execution seems to hang. The hammer keeps on hammering... Your original code in issue description (in Basic Console) works perfectly. Both code snippets run in Jupyter Console without problems.

**Comment by soininen** [comment]
Looks like I did break something.

**Comment by soininen** [comment]
Both scripts execute now in Basic Console and there is no SyntaxErrors anymore with consecutive executions/when writing something to the console.

**Comment by manuelma** [comment]
Nice fix, thank you @soininen !

**Comment by PekkaSavolainen** [comment]
Works now, thanks @soininen.

**Comment by soininen** [comment]
@manuelma Was there still some problem here or...?
