### ISSUE TITLE
Add notification icons to the status bar when logs are obscured

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1540]
Implemented a few days ago. The idea is that whenever messages are sent to the event log and the event log isn't visible, a small icon appears in the status bar that the user can click to show the event log.

Same for item execution log.

Cc @PekkaSavolainen

**Comment by PekkaSavolainen** [comment]
Found a small problem here. All icons in the status bar should be removed when switching a project.

**Comment by jkiviluo** [comment]
@manuelma Seems like this could be closed?

**Comment by manuelma** [comment]
This was not implemented at the end - seemed nice but not too useful.
