### ISSUE TITLE
When generating a graph-view PDF, opening the generated file or containing folder doesn't work

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1552]
So when I export a PDF of the graph view, the PDF is generated fine and I can open it via the file system. However, the file appears in the bottom left of db editor and I can't open it via any of the options there and get the following TB:

`ShellExecute 'file://///sharingiscaring/share/EnergyReform/*******/Hydrilyte System Model3.pdf' failed (error 3).`

**Comment by soininen** [comment]
Opening the pdf works fine for me but it looks you're saving it on a network drive. Perhaps the URL is not correctly formulated in that case?

**Comment by jkiviluo** [comment]
I tried saving to network drive and it was all good. Probably has gotten fixed along the way. Closing...
