### ISSUE TITLE
Feature: comments with parameter values

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1564]
Not sure if this has come up before.

I know we have metadata and commits and I believe @manuelma is considering a minimal commit viewer... but it still feels the the ability to "document" or "annotate" a particular data item is missing from the DB right now.

Thoughts? It feels like this commit viewer could possibly do the trick... it would definitely be the simplest solution from where we are right now since adding parameter value comments might have far reaching impacts across toolbox

**Comment by jkiviluo** [comment]
I think the current metadata together with our current plans to implement validFrom/validTo will cover this quite well.
