### ISSUE TITLE
DB Editor constantly has to be "reloaded"

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1576]
I'm consistently having an issue where if I double click on a datastore to take me to a DB that is already open in DB editor, when the focus shifts to the DB editor with the correct open DB, it doesn't show any parameter values and has to be "reloaded" to show anything.

This behavior happens intermittently in other situations also. I believe @manuelma witnessed this behavior when I was screen sharing :-)

Very often I have to reload multiple times, often having to restart db editor. There are no tracebacks in the console.

It's very annoying when I have a nice layout set up in graph view which is lost forever until we do something about #180.

**Comment by manuelma** [comment]
I tried to reproduce this but didn't manage. Anybody has the same or similar issue? The first step is to find steps to reproduce with some consistency so we don't spend hours debugging this.

**Comment by jkiviluo** [comment]
I think I've also seen this couple of times, but it's hard to pinpoint what is causing it. I will try to catch it next time.

**Comment by manuelma** [comment]
This should be better after 829e54aa5aa2618a2368cb448cae684d2a4d47a8

**Comment by jkiviluo** [comment]
This must be fixed by now.
