### ISSUE TITLE
Killing and reusing Julia consoles

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1586]
When I run a workflow with multiple SpineOpt scenarios executed in parallel, when each execution completes, each console remains open and holding a lot of stuff in memory. In my case, around 6GB per console. There are a number of issues here:
 - I can't see a way to kill the consoles once the executions are complete - I only have interrupt and restart. Typing exit() into the console doesn't appear to work. Restart works to clear the memory but a fresh Julia session remains open and I can't see how to close it.
 - It should be possible to somehow, perhaps optionally, automatically kill a console when the execution is complete - maybe I can simply do this by having an exit statement at the end of the SpineOpt tool script. This will free up the memory for use by the remaining executions.
 - I have a project with 8 SpineOpt scenarios. I am running them 4 at a time. When the first 4 complete, I have 4 Julia consoles each of which could be used to "Hot start" my next scenario runs... but instead, my second 4 will all open in new julia consoles and need to be compiled. It would be nice if the consoles could be reused

**Comment by soininen** [comment]
It is now possible to control the number of console processes. The setting can be found in Toolbox settings under the Engine tab. Spine Engine will start killing random console processes that have finished execution when the limit is reached. This means that you'll still get the execution output in the console window but post-execution debugging is impossible as the Python/Julia interpreter connected to the window is dead.

**Comment by manuelma** [comment]
Nice job! But I think it would also be useful to create a context menu action to just kill a console. I think this issue is more about that, killing specific consoles that hog a lot of memory.

**Comment by soininen** [comment]
Indeed. I wasn't planning on closing this issue yet.

On that note, it is currently possible to free most of the console's memory by restarting it as stated in the Description. This makes me wonder how useful a close option actually is. It is not difficult to implement, though, as I had it implemented for a few hours last week ;) I had to take it down, however, as it was interfering with something else I was working at that moment.

**Comment by manuelma** [comment]
You're right. I think it's mostly for users' piece of mind, and it's so easy to implement that why not?

**Comment by soininen** [comment]
Now we have:
- possibility to kill the console process from the console's right-click context menu; restarting the console will restore the console
- option to kill the console process after execution finishes in Tool's properties tab

Reusing the console processes has already been possible by setting the "Group id" in Tool properties tab.

I believe we are done here.
