### ISSUE TITLE
Display merged object and relationship parameters in graphview in multi-db DB Editor

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1596]
It's possible to open multiple DBs and view them together in a single tab in DB editor as discussed here: https://github.com/Spine-project/Spine-Toolbox/issues/1510

However, when in graph view, the parameter panes only show parameters for the selected items from a single DB. It would be good if the behaviour was consistent with table view where parameters from all open DBs are shows for the selected items.

This would be very useful for viewing ouput data alongside input data and I feel a user would be expecting consistent behaviour across different views.

**Comment by jkiviluo** [comment]
@manuelma Is this done?
