### ISSUE TITLE
Options for displaying nested Maps in the parameter value editor?

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/Spine-Toolbox#1599]
Currently, `Map` parameters are displayed with all their indexes shown at once through the parameter value editor. However, for nested `Map`s with potentially non-`Map` values on some layers, this method might be overly confusing. Instead, it might be easier to view the `Map` one index layer at a time, with all nested `Map`s being shown in the `value` column as `Map`.

**Comment by jkiviluo** [comment]
We plan to have more control about the dimensions inside parameters and I suppose this issue will be solved at that point.
