### ISSUE TITLE
View metadata pops an empty dialog if no metadata associated

### ISSUE THREAD

**Issue by ghost** [spine-tools/Spine-Toolbox#1603]
### Steps to reproduce:
* Create a new datastore, add an object class, a parameter, an object and some value for the parameter.
* Select **View metadata** for the parameter value (from right-click context menu)

### Outcome 
An error dialogue with not much info pops up and there is no metadata shown.

![image](https://user-images.githubusercontent.com/10612239/142421011-c7c13ab5-7f33-4ec1-9990-61405a48d67f.png)
![image](https://user-images.githubusercontent.com/10612239/142421123-a586dd80-46df-470d-ab70-f6a95ec1f494.png)

### Expected

Metadata is shown and can be edited.

**Comment by manuelma** [comment]
That's not an error dialog, it's just that the entity has no metadata associated.

**Comment by ererkka** [comment]
Ok, that explains. But the dialogue was too small to convey the message 😮

**Comment by jkiviluo** [comment]
Metadata widget is nowadays separate
