### ISSUE TITLE
Importer: don't hide tables that are not found in input file

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1608]
Currently, Importer's specification editor hides 'unused' tables from existing specification if the editor was opened with a file which doesn't have those tables. This may confuse users if e.g. the casing of table names changes from file to file.

It seems better if the specification editor would clearly show missing tables in the input file as well as new, yet uknown tables without user defined mappings.

**Comment by jkiviluo** [comment]
@soininen I'm tempted to add this to 0.7 - it can be really confusing. However, it needs to be possible to delete unused table names then.

**Comment by soininen** [comment]
Lets try to fit this in 0.7. The feature is long due.
