### ISSUE TITLE
Pass source and destination resources as command line arguments to jumps

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1621]
In https://github.com/Spine-project/Spine-Toolbox/issues/1620 I was arguing that items need to advertise resources backwards through jumps, so the previous item can modify that resource in order to progress the iteration. Think of a jump that goes back into a Data Store and modifies the data in that Data Store to roll things forward one hour for the next iteration.

But now I think it's better to pass resources from source and destination into the jump itself, and let the jump code do the updating logic on those resources. That's way more flexible and has better isolation.

What do you think? I guess we always wanted to have something like this so the stop condition can be based on results. At the moment, we can only write a condition on the iteration counter which is somewhat limited.

**Comment by jkiviluo** [comment]
Sounds good. Is the jump then a 'tool'? Or should there be only one source and one destination?

**Comment by soininen** [comment]
> What do you think? I guess we always wanted to have something like this so the stop condition can be based on results. At the moment, we can only write a condition on the iteration counter which is somewhat limited.

Indeed, jump scripts obviously need the resources to be able really evaluate the jump condition. I didn't implement it in the first place because at that time, I wasn't sure how to get handle of the resources and which resources should actually be passed to the script. My idea was to gather the forward and backward resources available to the source item but I'm unsure if those are actually useful in this situation. Perhaps the actual forward resources of source and target items make much more sense here.

**Comment by manuelma** [comment]
> Sounds good. Is the jump then a 'tool'? Or should there be only one source and one destination?

Yeah, it's almost like a tool in the end. And yes, the jump has exactly one source and one destination.

> Perhaps the actual forward resources of source and destination items make much more sense here.

I think it makes sense, or at least it does for my particular use case, but we can revisit in the future. I will go for it. Thanks for the feedback.

**Comment by soininen** [comment]
Just a small reminder: please be aware that jumps are allowed to have same source and destination items. In this case we probably don't want to duplicate the available resources.

**Comment by manuelma** [comment]
Thank you for the heads up! My changes are merged into master so you can check my implementation if you want. Accidentally I covered the above exception by storing the resources in a set.

A lot of stuff had to be moved from spine-items to spinetoolbox so the jump can have a similar interface to the tool item. But the actual addition is quite simple, we just store resources in the Jump object via two functions.

One thing I noticed is dagster seems to be in the process of deprecating the old low level api we rely on, PipelineDefinition, SolidDefinition, etc. I don't know what to think about it.

Also I was unable to find how to extract Outputs from SolidDefinitions, so I just stored resources in the SpineEngine instance as advertised by items -- then the Jump can retrieve the necessary resources from these dicts.

Seems to work.

**Comment by jkiviluo** [comment]
@manuelma Can this be closed?
