### ISSUE TITLE
Unintuitive pasting of tabular data from Excel to a selection in Map value editor

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1626]
In Map editor and actually in most if not all tables in Database editor, pasting tabular data from e.g. Excel tries to fit the data to the current selection. From `CopyPasteTableView.paste_on_selection()`:

```
Pastes clipboard data on selection, but not beyond.
        If data is smaller than selection, repeat data to fit selection.
```

I don't think this behavior is intuitive. A user just tried to paste data from Excel into Map editor and was confused because a single table row was selected and thus only the first row of data got pasted. In Excel you would get the entire table pasted no matter the selection.

I feel that the Excel way, i.e. always pasting the entire table to the top left corner of selection would be more intuitive than cropping the data to selection/repeating to fit. We'd do cropping from right and bottom only in case the data wouldn't fit the table. If user notes they pasted too much/too little they can always undo and adjust the data they were originally copying. Or is there some use case I fail to see here?

**Comment by manuelma** [comment]
In excel you can have a single string in the clipboard, select a bunch of cells and then paste, and you will have the string in all the cells. We need that functionality.

Perhaps the paste_on_selection should apply if more than one cell is selected only.

**Comment by jkiviluo** [comment]
> Perhaps the paste_on_selection should apply if more than one cell is selected only?

Sounds like a good plan.

**Comment by soininen** [comment]
If I got this right, the pasting rules should be:

1. If clipboard contains a table, paste it as-is anchoring the top left corner to top left selection
2. If clipboard contains single item, fill the selection with it

**Comment by manuelma** [comment]
That's not excel behavior. Excel behaves exactly like `paste_on_selection` in that if the clipboard contains a table when the user pastes, the table is repeated all over the selection. But if a single cell is selected, then the table is pasted 'normally'.

So the behaviour in my opinion would to call paste_on_selection if the selection has at least two cells.

**Comment by soininen** [comment]
> That's not excel behavior.

Looks like it depends on the version. My Excel (Office 365) behaves as I described above. Still, it makes me wonder if we should just keep the current behavior if it is familiar to at least part of the users...

**Comment by manuelma** [comment]
Oh, sorry my bad. I am actually talking about LibreOffice so maybe just replicate the behavior of your excel? It got to be what users are most familiar with.

**Comment by DillonJ** [comment]
I just tested it - you might both be right - the behaviour @manuelma is describing only happens if the selection size is an integer mutliple in each dimension of the copied table, otherwise, it @soininen's behaviour

**Comment by jkiviluo** [comment]
Anyway, it would be nice that if you have only cell selected it would paste the full table. I do that all the time and it's a hassle to select the right amount of columns.

**Comment by soininen** [comment]
> if the selection size is an integer mutliple in each dimension of the copied table, otherwise, it's @soininen's behaviour

Thanks for the heads up! That makes kind of sense. You never crop the pasted data but sometimes repeat it.

> Anyway, it would be nice that if you have only cell selected it would paste the full table.

That's how it works already. The issue was about how to treat pasting on multiple selected cells.

**Comment by jkiviluo** [comment]
I think the copy paste is working very nicely nowadays. May I close this? @soininen
