### ISSUE TITLE
Pivot view changes entity order whimsically

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1632]
The pivot view orders the entities in alphabetical order or in order of entry without any apparent logic. And it changes all the time. It would be good to be able to order at will (or at least it should stick to one order). Both orders are actually important, because when you are copy-pasting, the order of entry is important to have.

**Comment by manuelma** [comment]
I am aware of it but didn't have much time to fix it. The reason for the ilogical ordering is entries are added as fetched, and fetching is done as the view requests. So depending on what you do with the UI, you will have a different order.

This is managed in entity trees and parameter tables explicitely by sorting elements as added, regardless of when they are fetched. In the pivot table, we need to do the same but that requires an afternoon.

**Comment by jkiviluo** [comment]
Thanks. That explanation should also make it easy for a newcomer to try to address it.
