### ISSUE TITLE
Option to clone dbs into memory before running tools

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1650]
Some colleagues and I are working on a project where tools do a lot of db manipulation (basically we run SpineOpt in a loop while updating the input and output dbs in between iterations). All these reads and writes to disk become quite expensive in the end and we thought it could be a lot more efficient if the db was in memory.

I tried it, and it actually reduced IO time by more than 40% in this particular case.

The idea is quite simple. When the Tool is connecting to the database, we create a sqlite memory db where we copy all the contents of the original DB. The memory DB is passed to the tool to operate on it. When the connection is closed, if the memory DB is 'dirty', then it's copied back to the original.

So I propose we add this as an option to the user in the Data Store item - a check that says something like 'Use memory' and when checked, it does what I described above.

**Comment by jkiviluo** [comment]
@manuelma It's there, can we close?
