### ISSUE TITLE
Segfaults with Spine DB Editor

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1657]
It happens very seldomly to me, but sometimes it crashes with a segfault. Sometimes unittests also segfault misteriously.

I have been wondering if this is due to QThread (or my unability to use it properly), and if using python threading would work more cleanly. I'm not saying PySide2's QThread is bad at all but things like https://bugreports.qt.io/browse/PYSIDE-249 make me uncomfortable.

So I propose to refactor SpineDBWorker and SpineDBFetcher to use python threading or concurrent instead of QThread, and see if it helps.

**Comment by jkiviluo** [comment]
Did you switch to Python threading already or should we mark this as 0.8?

**Comment by manuelma** [comment]
I did switch... there's nothing else to do here except keep waiting. I don't remember when was the last segfault I saw but I believe it's still possible to crash it.
