### ISSUE TITLE
Saving a spec doesn't apply to the project immediately

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1658]
The user needs to save the spec *and then* save the project, otherwise their changes to the spec do not stick after closing the project (without saving).

This feels wrong and has caused me to lose changes repeteadly. Also, changes in the spec do not affect project.json at all. Indeed, all we write in project.json is the path of the specification json file. So in principle, we shouldn't require to save the project after saving the spec. In other words, changing and saving a spec shouldn't make the project dirty.

What should make the project dirty is changing the path of the specification file (and that works correctly at the moment).

**Comment by manuelma** [comment]
Actually, changing the spec's name should also make the project dirty since the spec name is updated in all the items that use the spec. But changing anything other than the name shouldn't dirty the project.

**Comment by jkiviluo** [comment]
I like this change!

**Comment by soininen** [comment]
@manuelma Can we consider this one as fixed?
