### ISSUE TITLE
Importer (and Exporter?) SQLAlchemy connector only works with SQLite?

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1668]
We should make it work with any dialect.

**Comment by soininen** [comment]
I guess we'd also need some way to deal with credentials on MySQL databases. Specifically, we don't want to save them in the specification files which may be accidentally shared over git or similar but rather in `.spinetoolbox/local/`.

**Comment by manuelma** [comment]
You're right! You have some code for hiding stuff, maybe you can point me to it?

**Comment by soininen** [comment]
There is existing code is for the stuff in `project.json` file. I hope it can be adapted to specifications, too.

First of all, there is `ProjectItem.item_dict_local_entries()` that project items can override to inform which item dict entries they want to store in the local folder. Currently, the method is overridden only in Data Store, see line 419 in `data_store.py`. This function gets called in `SpineToolboxProject._pop_local_data_from_items_dict()` while project is being saved which separates the local data from the real `project.json`.

So, item dicts in get divided into local and shared components when saving a project. Upon loading a project, we merge the local data with the shared data in `SpineToolboxProject.load()` (lines 279-280 in `project.py`) using `SpineToolboxProject._merge_local_data_to_project_info()`.

The mechanism is transparent to project items as long as they implement `item_dict_local_entries()`.

I hope this was helpful. Let me know if you need further information!

**Comment by soininen** [comment]
As Data Connections can now have URL references to remote databases, I think we have the Importer case covered. However, Exporter still needs some changes to be able to write to a remote database.
