### ISSUE TITLE
Consider recommending Git install from sources only

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1709]
Hi folks,

Considering the windows installer and the python release are now obsolete, should we consider removing mention of them in the readme and mention only installation from sources. We can reinstate the alternative methods if we have the resources to make more frequent releases or there are less frequent updates. I am concerned that a user using the windows installer or the pip install will not have a positive experience.

Thoughts?

**Comment by soininen** [comment]
I updated the pip package yesterday.

**Comment by jkiviluo** [comment]
I updated the Readme to say that the installer is quite obsolete (but can be still used for a quick look at how Toolbox looks and feels).

**Comment by jkiviluo** [comment]
@DillonJ, if you feel also that would be better removed, that would be fine.
