### ISSUE TITLE
Importer imports parameter values as object names

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1715]
I'm trying to import object class parameter values as arrays from a simple table.

With 'Has header' checked in Source options my input data looks like this:

![kuva](https://user-images.githubusercontent.com/19147159/170655515-f5c46f64-0361-421f-8b33-be585819827f.png)

Mappings are set up as following:

![kuva](https://user-images.githubusercontent.com/19147159/170660181-25e832d7-de7b-4948-8b07-c2df8c0f800a.png)

I'd expect to get objects 'a', 'b' and 'c' in the output database, but Importer imports all parameter *values* as objects, too:
![kuva](https://user-images.githubusercontent.com/19147159/170660388-20a4d6c1-a09a-4515-ab21-70f97b3ce8d1.png)

A workaround is to uncheck 'Has header' and set 'Object names' to 'Row' and 1. However, I'd expect both Mapping configurations to produce the same end result.

**Comment by jkiviluo** [comment]
Still valid bug.
