### ISSUE TITLE
Toolbox hangs if you open an exporter specification connected to a large DB

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1720]
As title... if you open an exporter spec on a large DB, you don't have time to untick the "live preview" checkbox before it starts to work hanging the whole thing and then you can do nothing else only kill toolbox via task manager

**Comment by manuelma** [comment]
@soininen what do you think? Can we deactivate the live preview by default?

**Comment by soininen** [comment]
Yeah, I think it makes sense. It's a bit disappointing that even with threading it still makes the Specification editor painful to use with large datasets.

**Comment by DillonJ** [comment]
Perhaps it already does something along these lines... but could the preview only look at, say, the first few indexes of the timeseries or something like that, to improve performance. The preview is very helpful... but you only want it to guide you with the structure, you don't need it to be showing full results.

**Comment by soininen** [comment]
The preview already limits the  number and size of the tables.
![kuva](https://user-images.githubusercontent.com/19147159/172096516-7a62a7ad-f53f-4cde-8216-655d00ad5bda.png)

**Comment by manuelma** [comment]
I think most of the time goes to the querying, before we can apply the maxes?

**Comment by DillonJ** [comment]
It would be great if we could disable the preview by default. If I attempt to open the specification of an exporter connectected to a large DB it will just hang toolbox and I have to restart everything

**Comment by manuelma** [comment]
I forgot to push this one. Will do now.

**Comment by manuelma** [comment]
Thank you @DillonJ for reporting - please try latest spine-items (i.e., upgrade toolbox reqs), should be now disabled at form loading.
