### ISSUE TITLE
Consider making table view (or pivot view) the default view instead of graph view

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1724]
It seems like graph view is the default view for DB editor. When opening a large DB, if you click on anything you are punished rather serverly by toolbox attempting to graph, very often, the entire model. Thankfully we have the stop button... but I think it would be nicer if one of the other views were the default instead. Table view would be best in my opinion.

**Comment by manuelma** [comment]
Table view is the default the first time you open a new DB. Then it will be whatever you had last time you closed the DB editor. Is that not the case for you?

**Comment by manuelma** [comment]
We'd need to look into it (i.e. try to reproduce) since the intention is to have table view as default.

**Comment by DillonJ** [comment]
OK, I will try and reproduce and post back
