### ISSUE TITLE
Add "Clear all filters" from DB editor parameter value widgets

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1727]
I often use the filters in the object and relationship parameter widgets. However it is a real pain removing them all one by one and sometimes it feels like filters get stuck and/or the option to remove the filter is greyed out even though I can see there is a filter applied. It would be good to have a "clear all filters" option in the context menu which would do two things: systematically clear all filters without relying on what filters it thinks are or aren't currently applied (solving the sticky filters issue) and the convenience of not having to remove them one-by-one.

**Comment by soininen** [comment]
@manuelma Didn't you add this feature some time ago? Is this issue still valid?
