### ISSUE TITLE
Show filepath in Tool Spec Editor

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1745]
Currently the filepath of the main program file and other files is not visible anywhere in the Tool Spec Editor. Add it in parenthesis behind the file name and as a tooltip.

**Comment by PekkaSavolainen** [comment]
The full path to the main program file is visible in the status bar.

**Comment by soininen** [comment]
@PekkaSavolainen is right: the source file path is clearly indicated in the status bar. I wouldn't want to add the path to the file name as it makes the labels long. Also, the tree that gets build for the additional source files is quite nice as-is. We could show the full path in tooltips, though, if we really wanted.
