### ISSUE TITLE
"Make everything bigger" setting in windows distorts Design view

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1775]
"Make everything bigger" in Windows 10 Settings scales all fonts and UI components up to 300%. Using this setting scales the fonts in Design view too, but has no effect on other graphics there distorting project item icons as
- Item name labels become much larger than the icons
- The relative execution order number doesn't fit anymore in its small rectangle
- The notification icon (!) is a font so it too becomes too big

The easiest fix would be to just prevent the setting from affecting Design view fonts. Otherwise, we'd need to scale the other graphics and their positions accordingly.

**Comment by manuelma** [comment]
Or make every font an image somehow? Could work by replacing text graphics items by pixmap graphics items?

**Comment by soininen** [comment]
> Or make every font an image somehow? Could work by replacing text graphics items by pixmap graphics items?

Sounds like more work than fixing a font size but that's an option, indeed. I'm a bit conserned about bitmap pixelation when scaled but perhaps we can just make them high-resolution.

**Comment by soininen** [comment]
Turns out it is enough to use *pixel* size for Design view fonts instead of *point* size which gets scaled. There seems to be plenty of other issues with scaling, though, some which I hope to fix under this same issue.

**Comment by jkiviluo** [comment]
Probably relates to https://github.com/spine-tools/Spine-Toolbox/issues/1635

**Comment by PiispaH** [comment]
This seems to be fixed at least for me on Windows 10.
