### ISSUE TITLE
DB editor ocassionally crashes with segfault

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#1798]
Sometimes when doing something completely random from opening the DB editor to adding entities or classes, to showing the drop down list of parameters, the editor crashes with segfault. We need to investigate but it's probably due to multithreading and bad clean up?

**Comment by manuelma** [comment]
We are calling `QCoreApplication.postEvent` from a *python* `threading.Thread`. Qt says `QCoreApplication.postEvent` is thread-safe but maybe that only applies to `QThreads`?

**Comment by manuelma** [comment]
The below seems related:

https://stackoverflow.com/questions/1595649/threading-in-a-pyqt-application-use-qt-threads-or-python-threads

https://www.kdab.com/the-eight-rules-of-multithreaded-qt/

**Comment by jkiviluo** [comment]
I'm closing this, since things seem to be pretty stable now after the async updates.
