### ISSUE TITLE
SpineToolbox not responding when calling old command

### ISSUE THREAD

**Issue by lilanger** [spine-tools/Spine-Toolbox#1805]
Here is the issue for the bug I raised yesterday in the early user call:
When I run SpineOpt in the SpineToolbox and afterwards type any command and try to recall it with the up-arrow, SpineToolbox freezes. The Anaconda prompt returns: "QAction::event: Ambiguous shortcut overload: Del"
![Toolbox](https://user-images.githubusercontent.com/54096244/198224226-c55dd5ee-6a19-48c4-8cf2-9c83e77bed86.PNG)
![prompt](https://user-images.githubusercontent.com/54096244/198224388-bd4b694f-304c-41ac-819c-7424a44647e2.PNG)

**Comment by PekkaSavolainen** [comment]
Confirmed that requesting history items (using up&down keys) in Julia persistent console on Windows makes Toolbox crash. This is a Linux feature only for now. Above commit disables the feature on Windows.

@manuelma I wonder how this could be disabled on kernel level, meaning that it should actually be disabled in `spine_repl.jl`, just like it is disabled in `spine_repl.py`? This would fix it both for local and remote execution at one go.

**Comment by PiispaH** [comment]
For me toolbox didn't crash, the Julia console just didn't respond to any commands anymore. The python console however worked as it is supposed to with the history items. By changing the Julia terminal type in spine_repl.jl I got it working also in the Julia console.

**Comment by PekkaSavolainen** [comment]
I guess if the Julia console did not respond anymore, it means that the kernel died but If you have a way to fix the feature, go for it.

**Comment by DillonJ** [comment]
Would be great to have this feature - it's always so disappointing when you press up and nothing happens!

**Comment by PiispaH** [comment]
The above linked pr should fix this, I don't have authorization to merge in spine-engine -repo.

**Comment by PekkaSavolainen** [comment]
Nice one! Thanks @PiispaH.  I can merge it.
