### ISSUE TITLE
Toolbox unit tests sometimes hang at test_remove_objects_from_object_tree_model

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1841]
Unit tests randomly hang at `TestSpineDBEditor.test_remove_objects_from_object_tree_model`. I investigated this some time ago and the reason was a deadlock in `SpineDBManager.close_session()` (called from unit test's `tearDown()`). For some reason the fetching thread that held the db_map_lock couldn't progress.

**Comment by jkiviluo** [comment]
Could relate to https://github.com/Spine-project/Spine-Toolbox/issues/1828

**Comment by soininen** [comment]
This problem seems to be gone now that we have refactored the Database manager.
