### ISSUE TITLE
Traceback from Exporter

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1870]
```
Traceback (most recent call last):
File "spinetoolbox\project_item\specification_editor_window.py", line 224, in closeEvent
if not self.tear_down():
File "spine-items\spine_items\exporter\widgets\specification_editor_window.py", line 1004, in tear_down
self._preview_updater.tear_down()
File "spine-items\spine_items\exporter\widgets\preview_updater.py", line 460, in tear_down
self._url_model.modelReset.disconnect(self._enable_controls)
RuntimeError: Internal C++ object (FullUrlListModel) already deleted.
```

Reported by @jkiviluo

**Comment by jkiviluo** [comment]
It is actually an importer in the TradeRES workflow. Trying to import gdx results from Backbone to Toolbox DB.

**Comment by jkiviluo** [comment]
and I don't know what is the pattern. Sometimes it works and sometimes it doesn't.

**Comment by manuelma** [comment]
I see, thank you. So how do I reproduce it, I need a tool running parallel scenarios that feed to an importer than then feeds to a DB?

**Comment by jkiviluo** [comment]
I wish there was an easy way. It seems to happen more likely when there is lot of data hauled and maybe with a couple of parallel importers. We have this in TradeRES project, but it's not feasible to get you to run that (GAMS etc.). I guess I could just copy results files and you could try that part of the workflow, but I don't know what is the pattern so you might just end up wasting your time. I'm reporting those tracebacks with the hope that they would ring a bell.

**Comment by manuelma** [comment]
I guess my question is more fundamental. I have never run an importer in parallel. All my importers are from Data Connection to Data Store so they never un multiple scenarios. In your case, it seems to me that you're feeding tool results to an importer that, because the tool runs in parallel, also runs in parallel. Is that it? Let me try...

**Comment by soininen** [comment]
The Traceback is still from closing the Exporter specification editor, and not in any way connected to executing an Importer.

**Comment by manuelma** [comment]
Sorry about that, I thought we were on https://github.com/Spine-project/Spine-Toolbox/issues/1828 

My two comments above apply to that issue.

**Comment by jkiviluo** [comment]
Ok, my bad too. That traceback had then probably existed before I crashed Toolbox with those importers. It would be good to have time stamp on tracebacks.
