### ISSUE TITLE
Pasting boolean list values to and from Excel

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1878]
When I copy parameter rows with boolean values from toolbox into excel, I get a row like this in excel:

![image](https://user-images.githubusercontent.com/7080191/202219992-89adf022-e4ae-482e-93c4-7bc8f335dd88.png)

When I try to paste this data back into toolbox I will get:

`Invalid value 'FALSE' - it should be one from the parameter value list: 'False', 'True'.`

Entering 'False as the value in excel does not work either.

Is there anything I can enter into the parameter value column in Excel that will be correctly interpreted as the list value I intend when pasted back into Excel?

@manuelma ?

**Comment by manuelma** [comment]
`true` should work - the JSON true.

**Comment by DillonJ** [comment]
They can't be entered into excel... it will automatically change them to Excel's internal boolean values which won't paste into toobox

**Comment by manuelma** [comment]
It works in libreoffice if I enter 'false - with the leading '

**Comment by DillonJ** [comment]
I tried that and it doesn't work in Excel

**Comment by DillonJ** [comment]
Hold on... it does... sorry I was trying 'False... but 'false does work! Thanks!

**Comment by manuelma** [comment]
We still need to fix the error message that thells the user that it should be either True or False (instead of true or false).

**Comment by DillonJ** [comment]
Ah... nice!

**Comment by DillonJ** [comment]
Should we also consider displaying the values as true and false ?

**Comment by soininen** [comment]
TODO (if I got the discussion right):

- [ ] Fix the error message to show the correct values of 'true' and 'false'
- [ ] Display booleans as 'true' or 'false' consistently in the Database editor

**Comment by suvayu** [comment]
I want to work on this issue.  However I don't have a dummy model/data to replicate it with.  So I was wondering, maybe someone already has something?

**Comment by soininen** [comment]
You can create your own test data for this.

1. Make a Toolbox project
2. Add a Data store item
3. Create an SQLite database with the Data store
4. Open Database editor (double-click the Data store)
5. Add a parameter value list on the Parameter value list dock
6. Add both boolean values to the list. To get the type correct, you need to right-click the "Enter new list value here..." and select "Edit..." from the popup menu
7. Create an object class in Object tree
8. Add an object to the class
9. Create a parameter definition for the object class, select the value list created at step 5 as 'value_list_name' in Object parameter definition table
10. Add a parameter value for the object created at step 8 and parameter at step 9 in Object parameter value table.

Now you can try copy-pasting `TRUE` and `'True` from Excel to the "value" column in Object parameter value table and observe how the error message is misleading.

There's seemingly a lot of steps there. Let me know if you get lost on the way.

**Comment by suvayu** [comment]
@soininen after browsing through the code, I arrived at [`spinedb_api.db_mapping_add_mixin.DatabaseMappingAddMixin.add_items(..)`](https://github.com/spine-tools/Spine-Database-API/blob/3e9aeb25b3c56d03fb92b9f5e0ed6f96c66aa35c/spinedb_api/db_mapping_add_mixin.py#L124). Do you think this is in the right direction?

**Comment by soininen** [comment]
@suvayu I messaged you over Element but looks like you missed that. Nevertheless, the error message is indeed in `spinedb_api`, more precisely [here](https://github.com/spine-tools/Spine-Database-API/blob/3e9aeb25b3c56d03fb92b9f5e0ed6f96c66aa35c/spinedb_api/check_functions.py#L439-L441).

**Comment by suvayu** [comment]
Strange, I didn't see a notification on elements and now I see there's a channel with you, but no messages O⁠_⁠o 

Anyway, thanks a lot! Just as I was about to leave work yesterday, I also narrowed it down to that module, but wasn't sure about the function :⁠-⁠P

**Comment by soininen** [comment]
I took the messages down from Element when I replied here. I had some ideas there on how to convert 'true' and 'false' case-insensitively to booleans on input as I think that would be more comprehensive fix for this issue but then I realized it isn't as straightforward as I though.
