### ISSUE TITLE
Make Tool retries user settable

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1882]
If Tool fails to execute, we retry it thrice. This may be useful if the failures are spurious but in my experience this is rarely the case. In fact, I've never used or seen a Tool that wouldn't fail deterministically. Further, it sometimes takes considerable amount of time before some Tools give up and fail. Retrying them two more times just to see the same end result wastes a lot of time.

To cater both Tools that fail deterministically and those that fail due to the phase of the moon, alignment of the starts etc. we should make the number of retries a user setting.

**Comment by manuelma** [comment]
Maybe we can get rid of the re-trying altogether. I don't quite remember why I imeplemented it in the first place, I think it had something to do with one memory-greedy tool being killed by the linux kernel in circumstances I really wanted it to go through. But if it's too hard/messy to implement that setting I would be ok to never retrying anything.

**Comment by soininen** [comment]
> But if it's too hard/messy to implement that setting I would be ok to never retrying anything.

Good to know, thanks for the input! I think we should then consider removal as a serious option if there is no apparent use case for the feature.

**Comment by manuelma** [comment]
I think we can get rid of it. If I ever think I will need it again I can just reimplement it with a setting.
