### ISSUE TITLE
Improve purge

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1905]
At present, purge can cause unintended consequences especially for new users of Toolbox. It's bit too easy to delete everything (classes, parameter definitions, etc.). So, here's what could be done:

- [ ] add button for 'Select data, alternative and scenario items' (could also be 'Select data and scenario items' even if it would select also alternative and alternative / scenario items).
- [ ] When purging all, it could give a warning 'Purging all will remove all structural information from the database. Are you sure?'. I'm hesitant about this, since it's additional clicking which I don't like. Could it just give a warning text in the Purge items dialog itself?
- [ ] An option to 'lock' parts of the database (e.g. purge could not empty classes of a particular DB). This would naturally go beyond purge, so should be its own issue, but we can discuss it first here as part of the purge update.

**Comment by jkiviluo** [comment]
> We already have the "select data items" so I guess you mean you'd like to add something beside this that also selects scenarios and alternatives?

Yes. Those are the two options I use regularly: just 'data' or 'data' and alternative/scenarios. I don't usually 'purge all', but I can see the benefit of that too.

I like the idea of having them as higher level options (and also that Purge all, but then it should probably have that warning).

And yes, data items is not very informative (especially at higher level without the help from checkboxes). However, Jody's "Purge data (preserve structure)" is more informative. Maybe hover over tooltip could say more about what is 'data'.

**Comment by soininen** [comment]
> Maybe hover over tooltip could say more about what is 'data'.

There is already a tooltip but since you haven't seen it, perhaps it's not enough? I labeled the button when I implemented it but I'm also first to agree that the label could be more informative. It's just always about finding balance between compactness and information content.

**Comment by jkiviluo** [comment]
Right. I don't wait for tooltips since I know what the buttons do, but new users could use tooltips, so I think there is definitely value in tooltips. But good names are even more important.
