### ISSUE TITLE
Scenario tree improvements

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1907]
~~- [ ] Don't auto-open lists (it's horrible with many scenarios because they become hard to find)~~
(superseded by https://github.com/spine-tools/Spine-Toolbox/issues/1930)
- [x] Could that `active: no` be removed? I always choose scenarios in the arrow. If they are still used, could the extra list level be removed - the `active: no` would just be special row before the alternatives.
- [x] One can 'copy' a scenario, but there is no 'paste' (or 'duplicate'). Would be very handy.

**Comment by DillonJ** [comment]
Just to point out that you can already duplicate scenarios in the scenario pivot view (right click on the row bar) which is very handy. I agree that a duplicate option would also be handy in the list view.
