### ISSUE TITLE
Separate alternative/scenario tree

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1930]
I realized that I would rather have alternative and scenario trees in separate tabs/windows. They have different functions and it would also be nice to be able to drag from alternative list to the scenario list when they are side-by-side. Now it doesn't work if there are too many alternative/scenarios since vertical space runs out. Of course one can run out of vertical space also after separation, but I think it will make working smoother in many cases.

**Comment by DillonJ** [comment]
I agree this would be nice, especially the dragging thing.

One thing I have found really heplful, is if you go to pivot view for scenaros, you can change whether the scenarios go vertically or horzontally - for me it's the best way by far to visualise the combinations.
