### ISSUE TITLE
DB filter not working

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/Spine-Toolbox#1939]
The DB filter doesn't seem to work as expected. Below in the `scenario filter`, the last three scenarios are actually selected and used by its following tool; and the tool filter apparently does not look right.
![image](https://user-images.githubusercontent.com/43530784/214597137-a8166ce1-93f9-4e1a-aebf-520b62313d67.png)

**Comment by DillonJ** [comment]
I confirm I am having the same issue. Not sure if related, but there is also https://github.com/spine-tools/Spine-Toolbox/issues/1940 where pivot view for scenarios/alternatives is not working either

**Comment by soininen** [comment]
I changed how filters work in links recently and looks like I missed some cases that are now broken. I didn't touch the Database editor at all, though, so I doubt this is related to #1940.

**Comment by PekkaSavolainen** [comment]
@soininen if you're fixing this, you just need to add .value to resource_filter_model.py setData()

```python
    def setData(self, index, value, role=Qt.ItemDataRole.EditRole):
        if role != Qt.ItemDataRole.CheckStateRole:
            return super().setData(index, value, role)
        self._change_filter_checked_state(index, value == Qt.CheckState.Checked.value)  # Add .value here
        return True
```

But this breaks a test. I fixed this so that the tests pass but forgot to try the checkboxes in practice.

**Comment by soininen** [comment]
Thank you @PekkaSavolainen for the heads-up!

**Comment by PekkaSavolainen** [comment]
I can take care of this if you @soininen don't mind.

**Comment by manuelma** [comment]
Not to put pressure but this issue makes some projects unrunnable at the moment...

**Comment by soininen** [comment]
I took the liberty to merge that PR. I'll open another one that adds a unit test, too.

**Comment by PekkaSavolainen** [comment]
> I took the liberty to merge that PR. I'll open another one that adds a unit test, too.

No problem, I was just waiting for the tests to pass.

**Comment by PekkaSavolainen** [comment]
This issue should be fixed now. Please reopen if not.
