### ISSUE TITLE
Issues with importing files in Spine DB editor

### ISSUE THREAD

**Issue by RowanPeng** [spine-tools/Spine-Toolbox#1957]
Hi,

I tried to follow the step-by-step instructions of tutorials in Spinetoolbox introduction file. For the first one, simple system tutorial, in this step (Figure 1), I downloaded the required two files, but I failed to import them in Spine DB editor. I coundn't find them in the path where I stored them. 

Could you help me with this? Thank you!

Regards,

Yuwen

<img width="533" alt="image" src="https://user-images.githubusercontent.com/123334582/216970399-916fd40d-f01e-46bd-bf0c-bbfe9f628c13.png">

**Comment by PekkaSavolainen** [comment]
Is this the problem? The *.sqlite filter seems to be selected by default in the Import file dialog. Just select *.json instead.

![issue_1957](https://user-images.githubusercontent.com/43600314/216974410-e4bd3990-ef10-47e1-b437-85ab3f36161f.png)

**Comment by RowanPeng** [comment]
Ahhh. Okay. Thank you!
