### ISSUE TITLE
The shortcut key to open the Settings dialog does not exist in all keyboard layouts

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1972]
We currently use the `§` as the shortcut to open the Settings dialog. While the key is nicely accessible in the upper left corner of the Finnish keyboard, it doesn't exist at all in e.g. US or UK keyboard layouts. We should rather use something like **Ctrl+Alt+S** instead.

**Comment by PekkaSavolainen** [comment]
The reason I set the shortcut key to § was in fact that it is convenient but I did not take into account other keyboard layouts. That's a valid reason to change it. But Ctrl+Alt+S is really awkward...

**Comment by jkiviluo** [comment]
It's bit awkward, but on the other hand, settings is not the most common thing to access by shortcut. We should save the simple shortcuts for things that users could do a lot. 

Also, I like that it's the first letter of the thing you want to accomplish - easier to remember.

**Comment by soininen** [comment]
I agree with @jkiviluo here. Besides, **Ctrl+Alt+S** is "widely" used in other software, too (PyCharm... ;))

**Comment by PekkaSavolainen** [comment]
It's fine. We need user selectable keyboard shortcuts at some point, though

**Comment by soininen** [comment]
I've already made the change in a branch that'll get merged to master at some point in the future.

**Comment by soininen** [comment]
I ended up using **Ctrl+,** as that is consistent with the Database editor.
