### ISSUE TITLE
Drop the "Custom open project dialog" setting

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#1973]
Is there any reason to use the system default dialog over the custom one?

**Comment by manuelma** [comment]
Just preference I guess. I would like to keep using the system dialog because I have it customized with bookmarks and it just feels great. I have never used the custom dialog which is also pretty cool... But I don't think it's too painful to maintain the option, is it?

**Comment by jkiviluo** [comment]
I like the custom, but no big feelings.

**Comment by soininen** [comment]
So, someone is actually using the system dialog. Better to keep the settings as-is, then.
