### ISSUE TITLE
Close Specification Editor Window when last tab is closed

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#1985]
We don't currently have a keyboard shortcut for closing the Specification Editors Windows (or do we?). You can close the tabs with **Ctrl+F4** but when the last tab is closed you are left staring at this and **Ctrl+F4** does not close it.

![empty_tool_spec_editor](https://user-images.githubusercontent.com/43600314/219339053-2937dd75-7237-4f7d-ba34-4d1944217926.png)

I propose that we don't show this window but close the Spec Editor Window when the last tab is closed.

In addition, Spine DB Editor does not have a keyboard shortcut for closing the tabs but closing the last tab **does close** the Spine DB Editor Window. Ergo, Spine DB Editor tabs should be closable with **Ctrl+F4** as well.

**Comment by soininen** [comment]
The universal exit key **Alt+F4** works on Windows.

**Comment by PekkaSavolainen** [comment]
This is the first time I ever heard of a universal exit key but it seems to work. :)

**Comment by PekkaSavolainen** [comment]
Done.
