### ISSUE TITLE
Running part of workflow should not care about the rest of the workflow

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#1990]
If I try to run a part of the workflow (or even just one tool), then Spine Engine checks the whole workflow first. There are probably good reasons for this, but there are currently some unintended consequences. These are things that are in other parts of the workflow and shouldn't influence running the selected part:
- It asks whether I want to upgrade all DBs in the workflow (if they need upgrading)
- If I use the new 'filter validation' option in the scenario arrow, then the whole workflow will not run if there are no scenarios. This is pretty bad: I can't fill an empty DB with an importer, because there are no scenarios (even though I'm not running that part of the workflow)
-  It can be very slow sometimes to check parts of the worfklow (that are not run). I don't know what it is, but this happens for an result importer item in the FlexTool workflow (again, I'm not executing it, it's just being checked - maybe looking what inputs in what scenarios are available or something).

**Comment by PekkaSavolainen** [comment]
At one point we decided that an item should only get resources from its direct (immediate) predecessors and pass them only to its direct successors. So why does executing item `d` in a DAG `a-b-c-d` traverse the whole DAG? Is this the bug @manuelma, @soininen ?

**Comment by soininen** [comment]
> Right?

Not quite. I believe this breaks Data transformers that need the resources of their predecessor Data stores to provide the correct URL downstream. I might be wrong here, though.

**Comment by PekkaSavolainen** [comment]
> Not quite. I believe this breaks Data transformers that need the resources of their predecessor Data stores to provide the correct URL downstream. I might be wrong here, though.

Well, does it really break it or it just lacks the resources to provide the transforms that it should? DT should just say that required resources were not found and the user should simply select more items for execution and try again.

**Comment by soininen** [comment]
> DT should just say that required resources were not found and the user should simply select more items for execution and try again.

We could do just that.

**Comment by soininen** [comment]
> I just want to check in here in case it is somehow related functionality - or perhaps I should create a new issue about it?

The way to achieve one-shot items currently is to disconnect it from any other item. Maybe we could have a check box to disable links between items? That would solve a few similar issues I've encountered in real-life workflows. It might even be not that difficult to implement.

In any case, I think you'd better open a separate issue.

**Comment by DillonJ** [comment]
Thanks @soininen

**Comment by PekkaSavolainen** [comment]
There's now two PR's (one in Engine, one in Toolbox) ready for testing/review. These PR's should fix all three bullet points in the original issue by @jkiviluo. The main change is basically that when executing only selected project items, we only touch the selected items and their direct neighbors.

Engine PR: https://github.com/spine-tools/spine-engine/pull/83
Branch: fix_dag_when_executing_selected_items

Toolbox PR: https://github.com/spine-tools/Spine-Toolbox/pull/2004
Branch: fix_execution_icons_based_on_executed_icons

**Comment by soininen** [comment]
> It asks whether I want to upgrade all DBs in the workflow (if they need upgrading)

I think this is actually *correct* behavior. We don't generally know if other items are using the database (unless it is in a separate DAG)

> If I use the new 'filter validation' option in the scenario arrow, then the whole workflow will not run if there are no scenarios.

This sounds more like an issue in filter validation itself. If there are no scenarios, then there's no filters to select.

> It can be very slow sometimes to check parts of the worfklow (that are not run).

I just measured the time it takes to validate items in the FlexTool workflow and it is a few microseconds/item. What slows things down are the animations we run for each item/connection even though they're not selected for execution.

My recommended fixes here:
1. Make sure we don't validate items/connections in "other DAGs". We may do this already, didn't check.
2. Make "require filter" validation print a warning if there are no filters available (nothing to select)
3. Consider turning other failed validations of unselected items into warnings that don't break the entire execution.
4. Disable animations for items/connections that have not been selected for execution.

**Comment by jkiviluo** [comment]
> I think this is actually correct behavior. We don't generally know if other items are using the database (unless it is in a separate DAG)

If I'm running just 2. 'Initialize' in the workflow below, then I will be asked if 9. 'Results' should be upgraded. However, I think we can be certain that there is no use of the 9. DB involved in running 2.

> This sounds more like an issue in filter validation itself. If there are no scenarios, then there's no filters to select.

Again, I'm running 2. 'Initialize', but having no scenarios chosen after 5. 'Input_data' will prevent me from running 2. That's wrong in my view.

> I just measured the time it takes to validate items in the FlexTool workflow and it is a few microseconds/item. What slows things down are the animations we run for each item/connection even though they're not selected for execution.

It has often take 2-3 seconds to go through 8. 'Import results' even though I just run 2. 'Initialize'. Didn't happen now, it just took the time it takes to animate (and yes, those animations should be turned off for non-active part of DAG - maybe even for active parts: the animation should stop when the execution stops).

![image](https://user-images.githubusercontent.com/40472544/222141606-70a6bc98-47d4-4982-9881-b1feaf37f065.png)

**Comment by soininen** [comment]
Looks like most of these issues will go away once  @PekkaSavolainen's PR's get merged.

> Again, I'm running 2. 'Initialize', but having no scenarios chosen after 5. 'Input_data' will prevent me from running 2. That's wrong in my view.

That's wrong in my view as well and something we need to fix. I don't think the PRs will tackle this issue so we need to fix it separately.

**Comment by PekkaSavolainen** [comment]
>> Again, I'm running 2. 'Initialize', but having no scenarios chosen after 5. 'Input_data' will prevent me from running 2. That's wrong in my view.

> That's wrong in my view as well and something we need to fix. I don't think the PRs will tackle this issue so we need to fix it separately.

I tried executing 'Initialize' without any chosen scenarios after ' Input_data' as seen below. To me it looks like the PR's tackle this issue as well.

![issue_1990_no_scenarios_selected](https://user-images.githubusercontent.com/43600314/222158231-5c05d50a-183d-4e67-a905-d3544d93aaaf.png)

**Comment by PekkaSavolainen** [comment]
> Trying to execute the Hammer Tool above fails. Before building the example I thought that the validation should just log a warning and let the execution proceed but now I'm not so sure anymore. Maybe stopping the execution in this case is actually the desired behavior?

It says '**Require** at least one checked scenario'. If it would not stop the execution then it was not really required. It's good as it is, in my opinion.

**Comment by jkiviluo** [comment]
Yes, it should not execute in this case.

**Comment by PekkaSavolainen** [comment]
Done. All three problems in the issue description have been solved + you can execute unconnected items in the same dag like previously + there's a note about Data Transformers in the changelog.
