### ISSUE TITLE
Add copy/paste to add relationship dialog

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#1999]
My use case is that I am creating a unit__node__node relationhsip and have already typed it one way I'd like to be able to copy and paste to create it the other way

**Comment by soininen** [comment]
Would Manage relationships dialog work for your use case? It creates all possible combinations of selected objects.

**Comment by DillonJ** [comment]
Hi Antti - yes it probably would have made more sense here.

I'm thinking all dialogs should support copy paste - I think the user would be expecting that

**Comment by soininen** [comment]
I agree with paste support. I just implemented it in Alternative and Scenario trees but many other docks don't support it yet.

**Comment by jkiviluo** [comment]
@soininen I think this is implemented across dialogs by now?

**Comment by soininen** [comment]
I think so too.
