### ISSUE TITLE
Alternative filter sticking silently after DB Reload

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2010]
If I have a scenario filter active and I reload the DB, I then see all data once the view is refreshed. However, as soon as I click on something in the tree, the data reverts to being filtered by the alternative that was previously selected, but is not selected any more.

The following issue is related:

https://github.com/spine-tools/Spine-Toolbox/issues/2009

**Comment by PiispaH** [comment]
This has already been fixed somewhere along the road.
