### ISSUE TITLE
Unnecessary error message when creating a new Data Store

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2014]
Steps:

1. Drag a new Data Store to Design View
2. Select it and select `sqlite` from the Dialect drop-down menu in Data Store Properties widget
3. Click `New Spine db` button
4. Click Save in the File Dialog
5. See below

![new_issue_error_msg_with_new_data_store](https://user-images.githubusercontent.com/43600314/222369280-f2fc0fc1-3cf2-4328-847e-be9ee6b2259c.png)

It's kind of harsh to hit users with an error message when they are doing the correct steps, i.e. the error message should not be displayed in this case.

**Comment by OleMussmann** [comment]
I'm looking into it, but I can't assign it to myself.
