### ISSUE TITLE
Wrong title and labels in Duplicate scenario dialog

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2021]
The right-click context menu in Scenario pivot table has an option to duplicate a scenario. Selecting the option opens a dialog whose title and label have been copy-pasted from "Duplicate object" dialog

![image](https://user-images.githubusercontent.com/19147159/223984354-88b3602e-3d03-40c8-be65-8d0a3a361c32.png)

Most urgent fix would be to replace "object" by "scenario" in the title and label. A more comprehensive fix would check how the duplicate action works in the Scenario tree. At least naming between the pivot table and Scenario trees is inconsistent which could be fixed. I would opt for the naming in Scenario tree because that's what we usually do in similar situations (append a number, not "_copy" to the original name).

**Comment by jkiviluo** [comment]
I agree that nicer to duplicate directly into the scenario list with an appended number. In general, we should avoid extra dialog boxes, they just slow the user down.
