### ISSUE TITLE
Importer's input file filter selection is missing *.*

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2039]
In Importer specification editor window, using this button to open a file:

![image](https://user-images.githubusercontent.com/19147159/225833081-866061f5-e12c-48bb-8168-349082b4c56f.png)

The button opens the standard file dialog with these file type filters:

![image](https://user-images.githubusercontent.com/19147159/225832716-aa862e37-a50d-4919-aab6-bd080250bad3.png)

Even though there are plenty of options, none of them show the files I want to see. Hence, we should add the show-it-all wildcard, `*.*` to the list.

**Comment by sjvrijn** [comment]
The list of available extensions is built-up using the `FILE_EXTENSIONS` attribute of each of the entries in `_CONNECTOR_NAME_TO_CLASS = {"CSVConnector": CSVConnector, ...}`, so a `*.*` extension has to be associated to a Connector.

What would the expected behavior of that Connector be?

**Comment by soininen** [comment]
I believe it is enough to manually add `*.*` to the filter options of the file dialog in `ImportEditorWindow._get_source_file_path()` (line 202 in `spine_items/importer/widgets/import_editor_window.py`). This should fix the issue here globally.
