### ISSUE TITLE
Importer specification editor's Add mappings button gets sometimes disabled

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2046]
The Add button should never be disabled, or at least I see no scenario where it shouldn't be possible to add mappings.

![image](https://user-images.githubusercontent.com/19147159/226570390-5471ce75-0f29-4331-9ba7-0071343c2ea4.png)

How to reproduce:
1. Remove all mappings from a source table
2. Select another table (or the Select All option) on Source tables list
3. Select the previous source table again
4. Observe that the Add button stays disabled and you cannot add mappings anymore to the table

**Comment by manuelma** [comment]
This is also fixed in the entity branch.

**Comment by PiispaH** [comment]
![image](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/1aef3cc9-939b-4107-8f22-7bf1a06fdb21)


If importer spec editor is opened in anonymous mode without any available resources, all of the mappings buttons are always on even if a table with no mappings or select all is selected from source tables. The buttons update only when selecting another source table option and going back to the one that was originally open.
