### ISSUE TITLE
Display booleans in lower-case, edit case insensitively

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2055]
We are inconsistent when it comes to boolean values in Database editor.

- booleans are sometimes displayed in their "Python" representation `True`, `False` (e.g. parameter value table) and sometimes in JSON `true`, `false` (e.g. parameter value editor for single value)
- you cannot input boolean values unless you open the parameter value editor which is inconvenient *except* when the values come from parameter value list
- if it is a parameter value list, you need to enter the values in their JSON presentation (when pasting from, say, Excel)

What would make booleans consistent and more convenient to use:
- Display their values always the same way, e.g. as JSON
- Convert the input strings `true` and `false` case insensitively to booleans

**Comment by soininen** [comment]
> I think I found the place: 

Nice, this looks like one of the places where we could do the type conversion. Be careful, though, as `MinimalTableModel` might be used elsewhere where we don't necessarily want the conversion. Also, there may be inheriting classes that reimplement the method, so you'll need to check those, too. Other input widgets may use other models, see for example `IndexedValueTableModel`.

If you aren't familiar with it already, [`str.casefold()`](https://docs.python.org/3.8/library/stdtypes.html#str.casefold) could be handy here: `if input.casefold() == "true".casefold():`.

**Comment by suvayu** [comment]
Good point, I'll double-check inheriting classes and other models.

Thanks for the `str.casefold()` reminder, I learnt about it recently :)
