### ISSUE TITLE
PySide6-uic not found

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#2059]
In linux where case matters the build script complains that it cannot find PySide6-uic - the file is called pyside6-uic. I had to manually copy it with the name in the script - should we try and adapt the scripts so we call pyside6-uic (lowercase) instead? Hopefully it works in all platforms.  @PekkaSavolainen @soininen what do you think?

**Comment by soininen** [comment]
It is written in lower case on my system as well. I think we should fix the scripts.

**Comment by PekkaSavolainen** [comment]
Above commit fixes the scripts on spine-items side. No changes were needed on Toolbox side.
