### ISSUE TITLE
Pivot view's left and top delegates are invisible

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2062]
The editor delegates below and to the right of the "header" tiles are not visible in Database editor's pivot view. The delegates do open and you can write something in them but you just cannot see what you are doing.

**Comment by manuelma** [comment]
Ah, nice spot. This might be a tricky one because we have a bunch of views superposed. It might be difficult to fix without breaking something else like selection, scrolling, context menu, to name a few.

**Comment by soininen** [comment]
Yeah, it is indeed brittle by construction. I think I found a fix but I will definitely need to test those things you listed.

**Comment by manuelma** [comment]
We could also find an alternative method to freeze the headers that doesn't require superposing views - the current implementation is based on the example provided by Qt though...

**Comment by soininen** [comment]
The fix wasn't too complicated in the end. I think we can stick to the current implementation for a little longer.

**Comment by soininen** [comment]
The above PR fixed this only for Value pivot tables. A fix is needed for Index, Relationship and Scenario pivots as well.
