### ISSUE TITLE
Alternative treeview layout in DB Editor

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2069]
We discussed this a few times in Toolbox and SpineOpt dev meetings.

Treeview is great for managing entities by class and seeing the connections (relationships) between them, and for creating these relationships.

Currently the treeview is laid out as follows:

 - Object Class
    -  Object
       - Relationship class
          - Relationship

There are a couple of issues with this:
 - at the relationship class level, many of the relationships won't be used (but this could be managed by hiding relationship classes that have no relationships as per https://github.com/spine-tools/Spine-Toolbox/issues/2008.)
 - There is a lot of clicking to do to get down to the lowest level and actually see what relationships are set for a particular object.

The idea is to restructure the treeview as follows. Perhaps this could be available as an option - with the user having the possibility to switch between the current view and the view proposed here.

 - Object Class
   -  Object
       - Related entites (Relationship Class)

Here, when one expands an object, they will see only the related entities. This will remove a huge amount of clutter, require fewer clicks and more clearly show the connections between entities.

One possible issue is that right now we use "emtpy" relationships classes to create relationships of that class (we right click on them) so this functionality should be possible by clicking on the object itself where we should have the option to "create relationship" and then select the relationship class to be specified.

**Comment by jkiviluo** [comment]
This has been implemented.
