### ISSUE TITLE
When an excel data connection is modified the resource reference is lost

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2079]
This has come up before and I'm wondering we could fix it as it frequently results in having to rerun an workflow when the problematic resource is encountered.

From the discussion before, I believe it is because when Excel saves a file, it creates a new temporary file and then deletes the original and replaces it with the new file.

Can we expect this behaviour and work around it somehow?

**Comment by soininen** [comment]
There is a workaround already. Is it not working? Please describe your experiences so far.

**Comment by DillonJ** [comment]
Hi @soininen so in theory this should not happen now? When was the workaround introduced?

My experience is that opening and saving an excel file that is in a data connection results in a red x in the tool and the filename in the argument list is replaced by a temporary file name that doesn't exist.

**Comment by DillonJ** [comment]
Ah thanks for the explanation. Some of the files I'm working with are quite big and maybe that explains why it sometimes happens.

**Comment by soininen** [comment]
I forgot to mention: just in case you didn't know, it is possible to fix the Data connection by hand:

![image](https://user-images.githubusercontent.com/19147159/232455660-f9ab760d-3958-4153-9b33-8c3a34d6ed66.png)

**Comment by DillonJ** [comment]
Ah - nice!

**Comment by jkiviluo** [comment]
> Even better solution would be to check every 1s for 5s or something - we don't want to show the Exclamation mark to users for too long.

I think this would be a nice solution and would allow to close the issue. Right?

**Comment by soininen** [comment]
> I think this would be a nice solution and would allow to close the issue. Right?

Yes.

**Comment by PiispaH** [comment]
I can start working on this issue.
