### ISSUE TITLE
Selecting more than one scenario crashes the Toolbox

### ISSUE THREAD

**Issue by tokorte** [spine-tools/Spine-Toolbox#2080]
If i run SpineOpt from Toolbox (0.6.17) everything works fine if i have just one scenario selected in the scenario filter (DB resource filters, db_url@Input, Scenario filter). If i select another scenario and try to run it again (e.g. 2 scenarios in total) the Kernel dies and never comes back. This leads to both scenarios not going past the "Initializing data structure from db" step. (for more information refer to the screenshots). Is there an easy fix for this problem?

spinetoolbox 0.6.17
spinedb_api 0.28.0
spine_engine 0.21.0
spine_items 0.19.0

Python 3.8.1 (default, Mar  2 2020, 13:06:26) [MSC v.1916 64 bit (AMD64)]

![bug1](https://user-images.githubusercontent.com/112625272/231779205-4d501aa7-f6df-4f7e-9e1a-85dfce890462.JPG)
![bug2](https://user-images.githubusercontent.com/112625272/231779301-84b1b7fd-909b-4558-bcda-f91d9864fc54.JPG)

**Comment by tokorte** [comment]
I manged to get multiple scenarios successfully running at the same time by using the Julia "Basic Console" instead of the "Jupyter Console". However, with the Jupyter Console, I can still only run just one scenario. I also noticed you changed the way the scenario are defined in the project.json. Maybe the issue with the Jupyter Console is related to this?

**Comment by PekkaSavolainen** [comment]
Confirmed! Looks like executing multiple scenarios in Jupyter Console is broken at the moment. There's a fix in the PR above (For spine-engine side), but I need to do a little bit more testing before merging. 

Thanks for the bug report.

**Comment by tokorte** [comment]
Ok, thanks for confirming and for creating the PR!

**Comment by PekkaSavolainen** [comment]
This should be working now. Please reopen if necessary.
