### ISSUE TITLE
Opening project can be slow

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2083]
Opening a project (or Toolbox with a project) has gotten quite slow (depending on the project of course). Probably has to do with checking scenario and tool filters to set them up in the workflow. Needs to be profiled.

**Comment by jkiviluo** [comment]
Good example project is FlexTool: https://github.com/irena-flextool/flextool. I think it gets even slower after populating the input data DB from the init DB.

**Comment by PiispaH** [comment]
Should be somewhat faster now. The main issue is that checking if a Tool has every required input file available and that there are no duplicate files in the resources is very slow. Finding the duplicates now takes only a fraction of the time it used to take, but I still haven't figured out how to speed up the check for fulfilling the file requirements. Now these checks are only conducted when the available resources or requirements change. This will also speed up some things when saving tool specifications.

**Comment by PiispaH** [comment]
Now also the check for required input files is a lot faster. On my computer the time to open the Flextool project takes only about a third of the time that it used to.
