### ISSUE TITLE
Duplicating a scenario twice is not the same as duplicating a duplicate scenario

### ISSUE THREAD

**Issue by sjvrijn** [spine-tools/Spine-Toolbox#2085]
## To reproduce

- In DB editor, create a scenario 'tmp'
- duplicate scenario 'tmp' -> creates scenario 'tmp 1'
- duplicate scenario 'tmp' again -> creates scenario 'tmp 2'
- duplicate scenario 'tmp 1' -> creates scenario 'tmp 1 1' instead of 'tmp 3'

This can lead to e.g. the following silly example:

![2023-04-18 16_34_54-Spine DB Editor](https://user-images.githubusercontent.com/8833517/232811324-fe94ef3d-a34e-4077-abb3-ac4fb51620da.png)

## Proposed change

I think the `(n)` notation for copies as used by e.g. windows would be safe enough to avoid messing with intentional numbers at the end of scenarios.

The scenario from above would then run as follows:

- In DB editor, create a scenario 'tmp'
- duplicate scenario 'tmp' -> creates scenario 'tmp (1)'
- duplicate scenario 'tmp' again -> creates scenario 'tmp (2)'
- duplicate scenario 'tmp (1)' -> creates scenario 'tmp (3)'

## Implementation detail

This behavior is currently defined by [`helpers.unique_name()`](https://github.com/spine-tools/Spine-Toolbox/blob/4cc129da76b9629db10b059c27958718429494f2/spinetoolbox/helpers.py#L1022), which is also used by the kernel editor widgets. 

A new implementation may look something like

```python
def unique_name(prefix, existing):

    reserved = set()

    # check if `prefix` is already a duplicate and adjust if needed
    match = re.fullmatch(r"^(.*) \(([0-9]+)\)$", prefix)
    if match:
        prefix = match[0]
        reserved.add(int(match[1]))

    pattern = re.compile(fr"^{prefix} \(([0-9]+)\)$")
    for name in existing:
        match = pattern.fullmatch(name)
        if match:
            reserved.add(int(match[0]))

    for free in range(1, len(reserved)+1):
        if free not in reserved:
            break
    return f"{prefix} ({free})"
```

**Comment by jkiviluo** [comment]
Good catch and should be safe to implement (not going to break anything).
