### ISSUE TITLE
Rogue widget in Database editor

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2091]
I noticed this extra line appearing sometimes in Database editor when switching between different views:

![image](https://user-images.githubusercontent.com/19147159/233364364-72dd32c0-8e08-4f86-9b6f-a46bf2c65e49.png)

Turns out it is a `QTabBar` widget, lost on its way to who-knows-where.

**Comment by soininen** [comment]
The rogue `QTabBar` is the tab bar of the dock widget stack that contains "Object parameter value" and "Object parameter definition" docks when in Table view. I am not sure why it is not hidden when switching to other views, though. I tried to update to PySide6 6.5.0 but the bar is still there. However, it does not rule out a bug in Qt.

**Comment by DillonJ** [comment]
"Widget gone roque" would be a good name for a band, in my opinion :-)
