### ISSUE TITLE
importer fails to overwrite existing item values

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/Spine-Toolbox#2098]
The importer doesn't overwrite values existing in the target DB. The same issue appears in the `SpineInterface.import_data()` function.

**Comment by soininen** [comment]
Could you please check that your importer has been set to replace existing files

![image](https://user-images.githubusercontent.com/19147159/233915898-0bb59ada-371f-4d7f-93d3-b59bac986d34.png)

Also, `import_data()` has a `on_conflict` parameter that should be set to `"replace"` or `"merge"`.
