### ISSUE TITLE
Select new main program file automatically in Tool Spec Editor

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2099]
1. Make a new Tool Specification, ie. open the Tool Specification Editor
2. Give it some name and select Python as the Tool type
3. Click on the **Create new main program** file button, give the file a name and click Ok or Save

The Editor window looks like this now.

![new_issue_select_new_main_program automatically](https://user-images.githubusercontent.com/43600314/234273572-093764c8-e98e-4fe0-89fb-759fe71c6479.png)

Click in the editor widget (black) and start typing -> Nothing happens because the main program file is not selected.

Expected behaviour: When user creates a new main program file, the file should be selected immediately so that the editor is ready to go.

**Comment by soininen** [comment]
Thanks for opening this issue! This has been bugging me for a while. More generally, the editor should not look like it is ready to accept input when you deselect a file in Program files list. It could be disabled or switched to a widget that says "no file selected".

**Comment by AmanSal1** [comment]
can  i work on this ?

**Comment by PekkaSavolainen** [comment]
> can i work on this ?

Sure, go ahead @AmanSal1.

**Comment by AmanSal1** [comment]
I just want to know that the function which is used to save the new program file is save_specification_file ?

Ps: Here is the screenshot of the the function which i am talking about 
![save 1](https://user-images.githubusercontent.com/121633121/235288013-59e2b91b-533d-4535-8ae9-9c548d6fa667.PNG)

**Comment by PekkaSavolainen** [comment]
It's actually on https://github.com/spine-tools/spine-items side.

This one shows the File Dialog, where users can create a new main file.
[new_main_program_file()](https://github.com/spine-tools/spine-items/blob/f08c405fdcc4effc36da93d96239caf211718e92/spine_items/tool/widgets/tool_specification_editor_window.py#L757)

Then this one adds the new main file into the UI. 
[populate_main_programfile()](https://github.com/spine-tools/spine-items/blob/f08c405fdcc4effc36da93d96239caf211718e92/spine_items/tool/widgets/tool_specification_editor_window.py#L328)

After the file has been added to the UI, it just needs to be selected programmatically.

**Comment by AmanSal1** [comment]
@PekkaSavolainen but i have a doubt how are these two repositories linked to each other because i am unable to see the files which has to be changed ?

Spine-items and spinetoolboxx

**Comment by PekkaSavolainen** [comment]
There are four repos (spinetoolbox, spine-items, spine-engine, and spinedb-api) in the https://github.com/spine-tools project that are required for starting the app (Spine Toolbox). The project items (the ones you use to build the workflow on the Design View) like Data Connection, Tool, Data Store, Importer, Exporter, etc. are loaded dynamically from spine-items package when you start Spine Toolbox in [this line](https://github.com/spine-tools/Spine-Toolbox/blob/ee6c75e046f38f09e43314da9dfcf5bca8303d4a/spinetoolbox/ui_main.py#L379). If you look at spine-items, each project item has it's own folder. In spine-items/tool/widgets folder you can find the Tool Specification Editor widget.

**Comment by AmanSal1** [comment]
@PekkaSavolainen okay got it!! thank youu appreciate your help

**Comment by AmanSal1** [comment]
@PekkaSavolainen Till now what I have figured is that the files are given indexes when they are selected by the mouse and then connected to the text editor . So basically now we want that whenever a new main program file is created we want to assign an index to it so it can be directly connected to the text editor but I am unable to find any function or something by which we can assign an index to a file on its creation .
Need some help here!!

**Comment by PekkaSavolainen** [comment]
> ... unable to find any function or something by which we can assign an index to a file on its creation .
> Need some help here!!

If you haven't already, I suggest reading [about model-view programming in QT](https://doc.qt.io/qt-6/model-view-programming.html). That's the stuff that's used throughout spinetoolbox and spine-items packages.

We create a QStandardItem from the file path of the newly created main program file and put that into a QStandardItemModel. This QStandardItemModel is hooked into a QTreeView (specifically `self._ui.treeView_programfiles` in this case). Whenever the data in the Model is changed, the View is automatically updated. You need to get the index of the QStandardItem from the QStandardItemModel and then select it. Hint: we already select the main program file automatically when user's open the Tool Specification Editor for existing Tool Specs.

**Comment by AmanSal1** [comment]
@PekkaSavolainen the solution which I am able to think of is that we can get the file name(file path) on creation and then we use the QStandardItem to create a a object of it and then giving the file path  as a parameter . After that we can use the indexFromItem method of programfiles_model  so we can manually assign the index to it without selecting it from the mouse for assigning the index . Because as if now i can see that the whole file is working on the selection model that is whenever any thing will get selected or  deselected then only indexes are assigned or unassigned. So for this purpose we will have assign the indexes manually till now i have figured out this much

**Comment by PekkaSavolainen** [comment]
@AmanSal1 You are welcome to make a pull request. It may be easier to figure out your idea from looking at the code. That way we can also see if the tests pass with your solution.

**Comment by jkiviluo** [comment]
@AmanSal1 if you're working on this, you could do this directly to v0.8 (which is developed in branch https://github.com/spine-tools/Spine-Toolbox/tree/spinedb_api_issue_215_drop_object_and_relationship). This would reduce merge conflicts. But it's also ok to do it for master (v0.7) and then either you or someone else will merge it to 0.8.
