### ISSUE TITLE
Closing and reopening DB editor does not reload the DB

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2100]
This has caused me big issues - when I open a datastore and I what I'm seeing is actually an old version of the data. Closing the DB and reopening does not refresh it which a user would reasonably be expecting. You have to manually hit the reload button to have it actually refresh

**Comment by DillonJ** [comment]
Edit - there are possibly two issues here - that the DB is not refreshed after a tool changes the data, and secondly that the DB is not refreshed when it is closed and reopened. The DB clearly doesn't realise it's data has changed

**Comment by manuelma** [comment]
Hi @DillonJ can you confirm if this happens all the time or just randomly?

**Comment by DillonJ** [comment]
It happens at least frequently and I think all the time

**Comment by manuelma** [comment]
Ok, thanks. So:
1. Open a DB in DB editor
2. Run a tool that changes the data in the DB -> the data is not refreshed in the editor.
3. Close and reopen the DB editor -> the data is still not refreshed.
4. Press Refresh button -> now the data is refreshed.

Is that it?

**Comment by soininen** [comment]
Could this be same issue as the first one listed in #2081?

**Comment by PiispaH** [comment]
@manuelma do you mind if I look into this?

**Comment by manuelma** [comment]
Hi @PiispaH thanks for asking! The caching implementation has changed enormously in the entity branch, and this may have been fixed. I wonder if you could try and look at this issue in the entity branch itself and see if it still happens?

**Comment by PiispaH** [comment]
This was fixed by #2215
