### ISSUE TITLE
Importer available resource selection not saved

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2101]
When I connect items to a merger, I see a list of available file resources. I am only interested in one and not the other because I just connected the related tool to enforce a certain execution order.

However, when I deselect a resource, save the project and then open it again, my selection is not saved and the workflow fails.

![image](https://user-images.githubusercontent.com/7080191/234499376-ecd505bb-8cec-412f-b165-506d780ad6c6.png)

**Comment by PiispaH** [comment]
Hmm, I can't seem to replicate this. For me the selections are always saved.

**Comment by soininen** [comment]
It looks like selections are not properly saved in two cases:
- The file is in Data Connection's Data, not References
- The file is provided as an output file from Tool

**Comment by soininen** [comment]
Looks like this one has been fixed.
