### ISSUE TITLE
Duplicated controls in Importer's Source options

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2106]
I have a CSV Importer whose Source options look like this:

![image](https://user-images.githubusercontent.com/19147159/235856862-fa3e947d-fb19-4234-8fc4-a1af96ebefd9.png)

**Comment by manuelma** [comment]
I fixed this in the entity branch. The culprit is updating the SourceConnection.BASE_OPTIONS attribute in importer.widgets.options_widgets.

**Comment by soininen** [comment]
> I fixed this in the entity branch. The culprit is updating the SourceConnection.BASE_OPTIONS attribute in importer.widgets.options_widgets.

Great! I'll have a look if I can cherry-pick the fix for 0.7.

**Comment by soininen** [comment]
@manuelma thanks a lot for the pointers! It was an easy fix once I had a peek of your changes in the branch.
