### ISSUE TITLE
Several UI issues since updating to version 0.6.17

### ISSUE THREAD

**Issue by bfb-19** [spine-tools/Spine-Toolbox#2124]
noticed a few issues with the UI since updating my spine version:
1. the entity graph doesn't display anything:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/59866945/6eff3fc9-24bf-4ea7-a5a8-c30e951be74e)

2. the console doesn't display when I click on a running item
![image](https://github.com/spine-tools/Spine-Toolbox/assets/59866945/304e7c46-6c08-4cdc-8c60-4f77b184ebf1)

3. clicking on a certain runtime instance in the output section/reporting section no longer filters the result to only be from that selected runtime
![image](https://github.com/spine-tools/Spine-Toolbox/assets/59866945/f563b240-1fe8-4f66-bc1b-8da776799907)

Hope this is helpful and I appreciate all the work that goes into this!

**Comment by jkiviluo** [comment]
Did you do 

`python -m pip install -U -r requirements.txt`

after

`git pull` ?

**Comment by bfb-19** [comment]
> 

would this still be relevant if I'm not using the development version?

**Comment by jkiviluo** [comment]
Right, sorry. I didn't realize this was from the pipx version. @PekkaSavolainen or @soininen can you make a new release in pipx? I think these issues are not in the master branch.

**Comment by soininen** [comment]
> can you make a new release in pipx?

Done.

**Comment by jkiviluo** [comment]
This should be fixed.
