### ISSUE TITLE
Adding alternatives to a scenario stutters

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2130]
There is something fishy about the way scenario choice is working. When I have a DB with many scenarios and alternatives (e.g. https://github.com/irena-flextool/flextool/blob/master/Init.sqlite), adding a new alternative into a scenario becomes slow and Toolbox flashes the cursor icon multiple times while thinking about adding the new alternative. This may relate to other slowness in Toolbox (e.g. https://github.com/spine-tools/Spine-Toolbox/issues/2083).

**Comment by soininen** [comment]
Dropping alternatives to scenarios seems to work pretty smoothly now even with FlexTool's Init database.
