### ISSUE TITLE
Add relationships widget expanding when choosing relationship class

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2137]
![Relationship_small](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/a0016631-36a3-44da-9b3e-92d84b6ec363)
![Relationship_big](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/159442c2-95e3-40c3-bcb2-99d215fd4a16)

In the DB Editor every time when an item is selected from the Relationship class drop-down list, the whole Add relationships widget expands to the right by a constant amount. This can be repeated many times which leads to an overly wide widget.

This same thing happens also when selecting the number of dimensions in the Add relationship classes widget.

**Comment by jkiviluo** [comment]
I think it's enough to fix this in v0.8 with entities (it's not a relationship class anymore, but I would suspect the same issue will remain).
