### ISSUE TITLE
Remove Kernel Spec Editor

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2145]
There's a widget that lists the Python and Julia kernels called Kernel Specification Editor that you can open from the Settings as well as from the Tool Specification Editor. After doing some work related to kernels, it looks like the widget needs quite a lot of refactoring to make it function again. Instead of doing the refactoring, I thought about removing the whole widget. Would anybody miss it?

The `Kernel spec editor` button on Settings->Tools page will be replaced by `Make new kernel` button, which let's users install a new Python or Julia kernel with a single button click. I believe this makes it easier for new users to get started.

**Comment by jkiviluo** [comment]
In principle it's nice, but it's not easy for new users to know what it means (unless they are familiar with kernels and consoles). I have used it on occasion, but it's no by means a priority for me.

**Comment by PekkaSavolainen** [comment]
Done.
