### ISSUE TITLE
Segfault when importing A5 case study importer specification

### ISSUE THREAD

**Issue by sjvrijn** [spine-tools/Spine-Toolbox#2155]
When following the A5 case study tutorial, I'm encountering a hard crash of the program.

Steps:
- Download `a5.xlsx` and `A5_importer_specification.json` from https://spine-toolbox.readthedocs.io/en/latest/case_study_a5.html#importing-the-model
- Create a new project
- Add a **Data Connection** and an **Importer** and connect them
- Add the `a5.xlsx` filt to the Data connection's File Paths
- Open the importer specification editor, select import mappings from the menu and select the `A5_importer_specification.json` file
- Program hangs for a bit, then hard crashes with a segfault.

I've also made it crash by opening the importer specification editor, closing it, and then opening it again. The second time it crashes before opening. This only happens if the data connection is already connected.

<details>
<summary>Commit hashes for each of the repos:</summary>

spine-toolbox: ea8080ea
spinedb-api: e225ff5 
spine-engine: ee43f01
spine-items: ed2d223
</details>

**Comment by soininen** [comment]
I could not reproduce the crash.
