### ISSUE TITLE
question about how to link external optimisation tool with Spine.

### ISSUE THREAD

**Issue by RowanPeng** [spine-tools/Spine-Toolbox#2157]
Hi,

Our professor is required to link Spine with an external optimisation software. I am wondering whether there is any guidance on how to do this link?

Best regards,

Peng

**Comment by DillonJ** [comment]
Hi @RowanPeng 

It would be helpful if you could provide more details. Will SpineOpt be using outputs of your external software or will it be using outputs of SpineOpt. What format do your inputs/outputs need to be in. In SpineToolbox you have many tools to covert a SpineOpt output DB to other formats using the Exporter tool and create SpineOpt inputs using the Importer tool. Alternatively, you have the python spinedbAPI and the Julia API, SpineInterface to programatically transform your inputs and outputs.

If you could provide more details, we could help with advising on the approach that might work best.
