### ISSUE TITLE
Spine DB editor does not update newly imported parameter values

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/Spine-Toolbox#2166]
After I import some existing values using an importer with the mode "replace", the DB editor still shows the old value. The new value is only displayed until the toolbox gets relaunched, i.e. the "reload" button in the DB does not work either.

**Comment by DillonJ** [comment]
I wonder if this is the same issue as https://github.com/spine-tools/Spine-Toolbox/issues/2100

I think the issue may be that when the API changes data, DB editor doesn't know the data has changed and the cache needs to be updated? @manuelma ?

**Comment by jkiviluo** [comment]
Should have been fixed by https://github.com/spine-tools/Spine-Toolbox/pull/2215. @nnhjy please let us know if not the case.
