### ISSUE TITLE
Allowable Parameter Types

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2176]
This functionality was planned at some stage and I just wanted to check if it's in the plan.

A major issue in SpineOpt is that some parameters need to be a specific type. However, we have no current way to enforce this in toolbox. Duration parameters like `minimum_up_time` are an example. Time and again, users get caught out by either entering a scalar value for these parameters or typing in a duration value like "1h" that gets stored as a string rather than a duration. The user will then get an error in SpineOpt and the cause is not easily identified for a new user. 

Toolbox supports timeseries, time pattern, scalar and map parameters but in the parameter definiition we need to be able to enforce a specific subset of these for individual parameters.

I have a couple of questions:
1. Does the new data structure allow for this?
2. Is it in the implementation plan?

@jkiviluo @manuelma ?

**Comment by jkiviluo** [comment]
The new data structure will allow this, but this part has not yet been implemented. So, it's in the plan, which is not written out clearly anywhere as far as I remember - we should do that. Meanwhile, there is this diagram: https://drive.google.com/file/d/1Ujd17uTIdn_chPdYNhLa6xWQCC_wPKtQ/view?usp=sharing

**Comment by DillonJ** [comment]
This would have prevented this issue: https://github.com/spine-tools/SpineOpt.jl/issues/937 and a lot of issues like it.

I think it would be a very valuable functionality that we've needed for a long time. I see it's tagged wit the V0.8 milestone. It would be nice if it could get done somehow

**Comment by jkiviluo** [comment]
This has been implemented, although there could be more functionality to define parameter types inside maps (but that should be another issue).
