### ISSUE TITLE
SpineToolbox takes very long to open

### ISSUE THREAD

**Issue by e-zaline** [spine-tools/Spine-Toolbox#2186]
Hello,
Most of the time (but not always) SpineToolbox takes a long time to open. Often one minute, or even two minutes or more.
On other occasions (a minority, though) it opens only in a few seconds.
I am using mini-conda, but I had the same issue with Anaconda.
Thanks for your help!

**Comment by jkiviluo** [comment]
This seems to be persistent issue for some laptops. For me, FlexTool project is bit slow to open, 5-10 seconds. But other projects are reasonably fast. I guess it must be some file i/o that waits to get a response.

Could be related with issues where same laptops take much longer to execute workflows. Should be profiled to see where the problem might be.

**Comment by jkiviluo** [comment]
I put this in v0.7, since it would be very nice to get this improved. Maybe @PiispaH could profile this and see if there is something obviously slow. If nothing is found, then let's move it v0.8 with high priority.

**Comment by PiispaH** [comment]
We discussed this with @soininen and it seems that the importing process can sometimes take longer. On my computer opening Toolbox without a project usually takes around 7 seconds, but on some occasions it takes up to 20 seconds. Even when it takes longer to open, the execution time of the actual non-import related Spine Toolbox code stays pretty much constant (around 5 s). When Toolbox took 20 seconds to open, my anti-malware software was using more resources than when it opens in under 10 seconds, so the slowness of the importing might have something to do with antivirus software checking files while python is trying to import them. This hypothesis will be tested with a computer which's anti-malware software can be disabled. Either way might be that not much can be done about this in the code (except for the non-import related part).

**Comment by jkiviluo** [comment]
But import related stuff shouldn't change depending on the project, right? I mean, the FlexTool project is clearly slower for me than other projects. And this is also true when Toolbox is already running. It feels like the situation has clearly improved, but FlexTool project is still slower.

**Comment by soininen** [comment]
I measured startup times of Toolbox in a Windows 11 system where I could turn Windows Defender on and off and I did observe spikes in startup times when using real-time protection. Sometimes it took 5-6 times longer to get Toolbox up and running which means 20-30s on that particular system. On the other hand, I did not see the spikes when real-time protection was off. The spikes happened immediately after I had turned real-time protection on or when I started Toolbox for the first time in a fresh terminal.

I did not encounter such spikes while executing a project.

Even without the spikes real-time protection slowed down both startup and execution but the difference was negligible in grand scheme of things.

**Comment by PekkaSavolainen** [comment]
I did something here (see PR #2713). Hope it helps.

**Comment by jkiviluo** [comment]
Should this be closed @PiispaH @soininen @PekkaSavolainen ?

**Comment by PekkaSavolainen** [comment]
Not sure if my latest commit did anything to improve the situation after all. Maybe we can close and come back if anybody comes up with a fresh idea.
