### ISSUE TITLE
How to make sure tools run in the right python/julia environment etc.

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#2196]
I don't know if we have an issue about this already, but we have discussed it in the first Mopo meeting in Helsinki.

The question is how to attach a specific python version, julia version, environment, etc, to a tool so it produces the exact same results for different users. At the moment, if I clone your Spine Toolbox project, it is up to me to configure the right python or julia for each tool so it works as intended. Moreover, you don't have any way to tell me what that python and julia needs to be via the project itself - you need to tell me via a readme or some documentation of sorts. Ideally we would have a more streamlined way.

I was discussing recently with some users/collaborators that are trying to tackle this issue. Their idea is as follows:

- Create a docker container that has the right python and julia, etc.
- Start a Jupyter kernel in that docker - this creates a connection file in a location within that docker that's accessible from outside
- From spinetoolbox, use that connection file to setup a kernel and associate that kernel to the tool
- Run the tool

With this, it is guaranteed that by sharing the Spine Toolbox project and the docker container, the tool will always run in the same python and python environment.

What do you think? Do we have any ongoing plans to tackle this issue differently? @DillonJ @jkiviluo @PekkaSavolainen @soininen

**Comment by jkiviluo** [comment]
Would it then be easy to keep the Spine Toolbox updated through Docker? Could there be git and pip in the same container too? I haven't really used it, so I know very little about this...

**Comment by jkiviluo** [comment]
Closing this since https://github.com/spine-tools/Spine-Toolbox/issues/3029 has more detailed plans. Not using Docker though, which may be something to revisit later (after we have better defined environments then it can be easier to build Dockers too).
