### ISSUE TITLE
DB not updating after close-reopen and after reload

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2198]
I have a workflow that writes parameters to a DB using a Julia script. When I open the DB I don't see the updated parameter values, just the old ones. Closing a reopening doesn't show the new values. Reloading doesn't show the new values either. Only closing toolbox and restarting it will show the new values in DB editor. 

I think it's hugely important that a user can trust what they see in their DB. 

The only way for me to confidently work around this is to manually execute the workflow in stages and close and restart toolbox every time a tool writes to a DB which clearly isn't great.

It feels like this has been a fairly persistent issue and others have posted similar things. 

I wonder do we need a test for this?

**Comment by PiispaH** [comment]
This could be fixed by making the reload button work like the rollback option. Then when the db is reloaded all of the uncommitted changes to the data would be wiped. Is this a valid way of doing things or how should the reload button actually differ from the rollback button?

**Comment by jkiviluo** [comment]
We may need some more fundamental changes to manage multiple edits from different sources (some of that has been discussed for the v0.8). A quick fix here could be that reload button is disabled whenever there are uncommitted changes in the database editor. Then reload button could safely check for changes from the outside.

We should not wipe uncommitted changes without confirming this from the user.
