### ISSUE TITLE
DB Editor gives successful message when adding data has failed to to a locked DB

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2201]
When adding data, such as adding new relationships when the DB is locked, DB Editor reports the operation as successful via a message in the bottom corner, but a traceback in the console indicates the operation has failed and the data is not changed in the DB and can't be comitted.

**Comment by PiispaH** [comment]
@DillonJ @jkiviluo @manuelma if any of you have time, could you check out the above linked pull requests to check that I didn't accidentally break some obvious functionality in the db editor that the unit tests or my rudimentary testing don't catch. Just so nothing catastrophic gets into 0.7.

**Comment by jkiviluo** [comment]
I haven't had any issues while using that branch (not extensively). I think it could be merged.
