### ISSUE TITLE
Changing alternative inputs weird data to db

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2204]
This happens at least on flextool db editor when changing a is_active parameter's alternative to another and back. It produces this error message: Invalid value '332.0'. I don't know where it gets that number. The editor still shows that the value is 'yes', but it is not. I've not seen this problem when the parameter does not have a parameter value list set.
This can be reproduced on Flextool master input db when changing the battery_inverter is_active alternative to battery_invest and back to battery:
![invalid_value](https://github.com/spine-tools/Spine-Toolbox/assets/84875787/b6c2bf92-235d-47a8-b4b3-78d35b5011c4)

**Comment by soininen** [comment]
I think the parameter value list values have been fixed by now. Please reopen if necessary.
