### ISSUE TITLE
Toolbox crashes when trying to commit database

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2216]
While fixing #2198 found another problem with the db editor.

How to reproduce:
1. Open db editor and make some changes without committing
2. Execute an item that modifies the databases data
3. Try to commit the database -> Toolbox crashes

**Comment by jkiviluo** [comment]
Reproduces on my laptop. Placing this in v0.8, since you can workaround this (by committing early and often).

**Comment by DillonJ** [comment]
In the steps to reproduce, it doesn't sound like the frequency of the commit or the volume of the data is a factor, so does committing early and often really work around it?

Having experience this issue quite a bit, it is quite annoying

I'm wondering, maybe we could have an auto-commit option in this case.

**Comment by jkiviluo** [comment]
I just meant that committing before running items that modify the data is the workaround. Sloppy language. sorry.

**Comment by jkiviluo** [comment]
Yes, we should focus on getting to v0.8. I'm sorry I kept too many things in v0.7. I was thinking we should kill bugs there, but I suppose it's the wrong way. Today I went through issues from v0.7 and without milestones and put them in v0.8 unless they were really creating a bad user experience.

**Comment by soininen** [comment]
Toolbox does not crash in `0.8-dev`, at least not when committing after external Importer or database modifying Tool execution.
