### ISSUE TITLE
Importer: suggestion of improvement: change the order of the Mappings

### ISSUE THREAD

**Issue by e-zaline** [spine-tools/Spine-Toolbox#2239]
It would be nice to be able to change the order of the different mappings in SpineToolbox Importers.
E.g.: a drag-and-drop, or "move up" "move down" buttons

![image](https://github.com/spine-tools/Spine-Toolbox/assets/62605130/686202f9-3628-4f2e-a6cb-2aa266d16779)

**Comment by soininen** [comment]
It should be possible to reorder the tables as well --- your 0d entities could be in a table *after* the nd entities they are elements of making it impossible to import the data on one go (or you need to check the "Import entities" check box which can be dangerous).
