### ISSUE TITLE
Toolbox crashing when arrows are used to change mapping options

### ISSUE THREAD

**Issue by FebinKa** [spine-tools/Spine-Toolbox#2247]
The Spine Toolbox keeps crashing when I change the numbers in the mapping options of the exporter using the arrows. However, no problem arises if I change the values by directly entering a number into the cell.

![SpineMapping](https://github.com/spine-tools/Spine-Toolbox/assets/55534006/0bf47c9d-2e27-4ffd-835d-df314d311867)

**Comment by PiispaH** [comment]
Duplicate of #2235
