### ISSUE TITLE
Exporting results from different scenarios into one file

### ISSUE THREAD

**Issue by FebinKa** [spine-tools/Spine-Toolbox#2250]
It would be nice to be able to export the results from different scenarios into one single file. As far as I could tell, they are currently saved in a separate folder by scenario instead.

**Comment by nnhjy** [comment]
This happens when exporting to `.csv` and `.xlsx` files.

**Comment by jkiviluo** [comment]
The exporter is still bit half-finished in this regard. You can export multiple scenarios to one file, but you need to have no scenarios selected in the arrow (and the exporter should also use 'alternative' as one of it's dimensions, so you can distuingish between the scenario results). If you select one or more scenarios, they will go to different files.

**Comment by jkiviluo** [comment]
Related to https://github.com/spine-tools/Spine-Toolbox/issues/2147

**Comment by soininen** [comment]
This is now possible with the Alternative filters.
