### ISSUE TITLE
Data not visible in db after purge and undo

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2261]
If you purge the whole DB in DB editor, pressing undo doesn't show the data that was there previously. To see the data again you either have to undo all the way to the db not being dirty anymore and then pressing the reload button or commit after the undo and then pressing reload.

**Comment by jkiviluo** [comment]
I wonder if we want to keep undo available after purge? It's nice in principle, but if you have large databases, you could easily hit memory limits.

**Comment by soininen** [comment]
I have been wondering the memory usage, too, but we should still investigate the root of the issue even if we decide to clear the undo stack on purge. There might be a bug there that affects database item removal in general and undo in general.

**Comment by PiispaH** [comment]
This seems to be fixed now.
