### ISSUE TITLE
Toolbox does not run selection

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2271]
Running 'starts' but nothing happens. Event log last message: 'Executing Selected Directed Acyclic Graphs'.
Traceback:
![MicrosoftTeams-image](https://github.com/spine-tools/Spine-Toolbox/assets/84875787/8041bf4d-e4d5-4b45-80f5-38bb24b16ad3)
Stop button is visible, but pressing it does not do anything either.
Done using newly re-installed toolbox and flextool

**Comment by soininen** [comment]
This is a bug in `path_in_dir()`: it should not raise an Exception but return True.
