### ISSUE TITLE
Spine Database API erroneously offers to "upgrade" a database that is of too new version

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2280]
If database has a version hash that is not recognized by Toolbox, we should just refuse to open it and print an appropriate error instead of offering to "upgrade" the database.

**Comment by PiispaH** [comment]
I didn't manage to find a case where Toolbox would offer to update a database of which's version was not recognized. It only offers to update DBs that are of older recognized versions and it seemed to do that successfully. It does however open a blank DB editor window/tab when the cancel is clicked on the dialog even though it refuses to open the actual outdated DB.

**Comment by soininen** [comment]
Looks like this has indeed been fixed in `0.8-dev`:

![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/e548d030-ef75-4a44-8bea-a82649999d28)

I think we can close this issue once the PR above is merged.
