### ISSUE TITLE
Importing file in Database editor with All files filter fails

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2283]
When trying to import a file from Database editor while the All files filter is selected:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/53416b1c-5d33-434e-85fd-a203c0217896)

In console, I see this Traceback:
```
Traceback (most recent call last):
  File "spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 485, in import_file
    raise ValueError()
ValueError
```
Importing works if any of the file type specific filters are selected while accepting the Import dialog.

**Comment by PiispaH** [comment]
Fixed in duplicate #2308
