### ISSUE TITLE
Importer crashes if encoding is not utf-8

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2284]
![encoding](https://github.com/spine-tools/Spine-Toolbox/assets/84875787/4e36ffe9-c947-4c96-81c7-ebd9a5ae4a18)

One of the imported files does not have utf-8 encoding and it has special character.
Import_Results "keeps running" when it has crashed.

**Comment by ArttuTupala** [comment]
[node__period__t.csv](https://github.com/spine-tools/Spine-Toolbox/files/12463605/node__period__t.csv)

**Comment by soininen** [comment]
By the way, this happens when importing data package which defaults to "utf-8".
