### ISSUE TITLE
Spine DB Editor gives an error message when adding relationships through copy-pasting relationship parameter data

### ISSUE THREAD

**Issue by nhniina** [spine-tools/Spine-Toolbox#2285]
I've added the following connection to my database: Bastusel_to_Grytfors_disch. I've also added the following two nodes to my database: Grytfors_upper and Bastusel_lower.

When trying to copy-paste the following data to connection__node__node

connection__node__node	Bastusel_to_Grytfors_disch ǀ Grytfors_upper ǀ Bastusel_lower	connection_flow_delay	Base	{"type": "duration", "data": "1h"}
connection__node__node	Bastusel_to_Grytfors_disch ǀ Grytfors_upper ǀ Bastusel_lower	fix_ratio_out_in_connection_flow	Base	1

everything works, but Spine DB Editors shows an error message: There's already a relationship called 'connection__node__node__Bastusel_to_Grytfors_disch_Grytfors_upper_Bastusel_lower' in the same class.

When copy-pasting the two parameter data rows one by one, there's no error message. There's also no error message when first adding just the relationships, and then copy-pasting all parameter data.

**Comment by PiispaH** [comment]
Should be fixed int the 0.8 branch now
