### ISSUE TITLE
Get Database editor documentation up-to-date with the new entity stuff

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2306]
Database editor has had some drastic changes since entities replaced objects and relationships. The documentation should be brought up-to-date regarding the changes.

### Text Formatting

See **General Consistency** section in #2267.

### Spine Data Structure

- [x] Energy-modelling-workbench now hosts the description of Spine data structure. Therefore it is enough to provide a link to the documentation. The current text and figure should be replace by something simple like this:

> Documentation for the Spine data structure can be found [here](https://github.com/energy-modelling-workbench/spine-data-model#spine-data-model).

### Getting Started

**Launching the Editor** section:
- [x] Check that the instructions still work.
- [x] The editor can also be launched from Toolbox using **File** -> **New DB Editor**.
- [x] Instructions on how to add multiple databases to a single editor probably deserves its own page or at least its own section. Note that multiple URLs can also be added directly to the URL field.

**Knowing the UI** section:
- [x] Describe the tabbed interface: opening tabs, closing tabs, dragging tabs around etc. Can be short as most users should be familiar with tabs from web browsers.
- [x] Describe the navigation bar: its buttons and the URL bar.
- [x] Navigation bar's filter functionality may require its own page or at least section.
- [x] Introduce the hamburger menu. This is probably the most important single component in the entire UI.
- [x] Introduce docks and how to revert the interface back to the default state in more detail.
- [x] Update the terminology in the UI components list.
- [x] Remove Tool/Feature tree, it does not exist anymore.
- [x] Explain how to switch between different views (Table, Graph, Pivot) in more detail.
- [x] Undo/redo
- [x] **Hamburger Menu -> New...**.
- [x] **Hamburger Menu -> Open...**.

The usual stuff:
- [x] Update (maybe even add new?) screenshots.
- [x] Ensure links are not broken.

### Viewing Data

- [x] Update the description of **Entity Tree**: we have a single tree nowadays.
- [x] Make sure we don't talk about objects or relationships but rather about entities, dimensions, elements.
- [x] The term **Stacked tables** is not mentioned anywhere in Database editor itself. It should be replaced by **Table View**. Similarly replace **Entity graph** -> **Graph View** and **Pivot table** -> **Pivot View**.
- [x] Add section about **Entity alternative** table. (very brief at the moment)
- [ ] ~Add section or even own page about configuring and viewing the dynamic graphs~ moved to #2513
- [x] Drop **Viewing tools and features**.
- [x] Update screenshots.
- [x] Make sure links work.

### Adding Data

- [x] Make sure we don't talk about objects or relationships but rather about entities, dimensions, elements.
- [x] The term **Stacked tables** is not mentioned anywhere in Database editor itself. It should be replaced by **Table View**. Similarly replace **Entity graph** -> **Graph View** and **Pivot table** -> **Pivot View**.
- [x] Add section about adding entity alternatives.
- [x] Drop **Adding tools, features, and methods**.
- [x] Update screenshots.
- [x] Make sure links work.

### Updating Data

- [x] Make sure we don't talk about objects or relationships but rather about entities, dimensions, elements.
- [x] The term **Stacked tables** is not mentioned anywhere in Database editor itself. It should be replaced by **Table View**. Similarly replace **Entity graph** -> **Graph View** and **Pivot table** -> **Pivot View**.
- [x] Add section about updating entity alternatives.
- [x] Drop **Updating tools and features**.
- [x] Update screenshots.
- [x] Make sure links work.

### Removing Data

- [x] Make sure we don't talk about objects or relationships but rather about entities, dimensions, elements.
- [x] The term **Stacked tables** is not mentioned anywhere in Database editor itself. It should be replaced by **Table View**. Similarly replace **Entity graph** -> **Graph View** and **Pivot table** -> **Pivot View**.
- [x] Move **Purging Items** as the first section.
- [x] Expand the **Purging Items** section to explain about the new buttons on the dialog.
- [x] Drop **Removing tools and features**.
- [x] Things can be removed from **Graph View** which could be mentioned here.
- [x] Update screenshots.
- [x] Make sure links work.

### Managing Data

- [x] Make sure we don't talk about objects or relationships but rather about entities, dimensions, elements.
- [x] Update screenshots.
- [x] Make sure links work.

### Importing and Exporting Data

- [x] Make sure we don't talk about objects or relationships but rather about entities, dimensions, elements.
- [x] It probably makes more sense to first explain how to import/export before going into details on how the JSON file looks like. Move the **Excel Format** and **JSON Format** subsections to the end of the page under a new title **Format Specifications** or similar.
- [x] Update screenshots.
- [x] Make sure links work.

### Committing and Rolling Back

- [x] Renamed to Committing and History
- [x] Add a screenshot of the **Commit Dialog**.

### Links and loops

- [ ] ~Add information on how to make loops and what they do~ This somehow ended up here even though not related at all

### Functionality without home

- [x] Add page for **History** and **Commit Viewer**. (added under Committing and History)
- [x] Add page for **Vacuum**
- [x] Add page for **Settings** or at least link to Toolbox Settings documentation in **Getting Started**.

**Comment by soininen** [comment]
Updated the Spine Data Structure section in the issue description above.

**Comment by PiispaH** [comment]
This should be about done now.
