### ISSUE TITLE
WSL Package not installed

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2309]
I receive console messages that the WSL package is not installed. I have installed it but am wondering if there is an issue with the dependencies of the project? This relates to v0.7

**Comment by PekkaSavolainen** [comment]
If you mean this WSL https://pypi.org/project/wsl/, it is not a Spine Toolbox requirement. Are you perhaps running a Tool that imports it?

**Comment by jkiviluo** [comment]
@DillonJ Is this an issue for Toolbox? Should we close?

**Comment by DillonJ** [comment]
@jkiviluo yeah, sorry - not sure what was looking for it.

**Comment by jkiviluo** [comment]
I'll close. If Toolbox relevant stuff resurfaces, let's open it again.
