### ISSUE TITLE
Importer File Selection resets everytime after closing, ignores project.json config

### ISSUE THREAD

**Issue by kTelaar** [spine-tools/Spine-Toolbox#2315]
Hi,

while working with an Excel Importer Spec that has different files as "Available resources" in the Importer Properties (ref. screenshot)

![grafik](https://github.com/spine-tools/Spine-Toolbox/assets/140422859/5edb65fb-0363-4427-960a-55186bd7355f)

only one file should be ticked, as is correctly saved in the project.json-Code (see below). 
Instead every single time you open the project you have to deselect every file but the one you actually want to select (MainInput.xlsx). If you don't do that you'll run into this error:

![grafik](https://github.com/spine-tools/Spine-Toolbox/assets/140422859/ed2c2e26-9508-429b-9f38-52e5556070e1) 
This behaviour was present in spinetoolbox 0.6.18 and is still present in 0.7. I'll attach the complete project.json-File if it helps as well. Many thanks!

            "type": "Importer",
            "description": "",
            "x": -858.5309073067253,
            "y": -279.74993519582114,
            "specification": "Main Model Input",
            "cancel_on_error": true,
            "on_conflict": "replace",
            "file_selection": [
                [
                    "<Data Connection Main>/.gitkeep",
                    false
                ],
                [
                    "<Data Connection Main>/MainInput.xlsx",
                    true
                ],
                [
                    "<Data Connection Main>/Relationships.csv",
                    false
                ],
                [
                    "<Data Connection Main>/model.csv",
                    false
                ],
                [
                    "<Data Connection Main>/model_config.csv",
                    false
                ],
                [
                    "<Data Connection Main>/model_date.csv",
                    false
                ],
                [
                    "<Data Connection Main>/output.xlsx",
                    false
                ],
                [
                    "<Data Connection Main>/report.csv",
                    false
                ],
                [
                    "<Data Connection Main>/stochastic_scenario.csv",
                    false
                ],
                [
                    "<Data Connection Main>/stochastic_structure.csv",
                    false
                ],
                [
                    "<Data Connection Main>/subset_countries.csv",
                    false
                ],
                [
                    "<Data Connection Main>/temporal_block.csv",
                    false
                ]
            ]
[project_and_importer_jsons.zip](https://github.com/spine-tools/Spine-Toolbox/files/12610804/project_and_importer_jsons.zip)

**Comment by jkiviluo** [comment]
While this is most likely a bug and should be fixed - do you need the connection from "Data connection main" to "Importer main"? If you don't have that, then the csv files should not appear as resources, but you could make the "CSV_to_XLSX" to pass "MainInput.xlsx" to "Importer main" (in tool specifications - Output files).

Also, importer can read csv (and you maybe could skip CSV_to_XLSX step). If you use "Pack CSV files" option in the link properties (select the arrow from csv data source to importer) all of those separate csv files will appear just like "sheets" in Excel would in the importer.

**Comment by kTelaar** [comment]
Yes, we do need the connection from "Data Connection Main" to "Importer Main". The only thing the connection from "CSV_to_XLSX" to "Importer Main" does is to guarantee correct sequencing of the project. (no output defined)

We have decided to disable all "Output files" in Tools specifications and instead use data connection that refer to the created output files in a TEMP-DATA-folder. (No more accumulation of not needed .csv and .xlsx files after each run)

Pack CSV-Files as json sounds interesting, I'll look into that.
The rather basic workaround implemented at the moment looks like this
![grafik](https://github.com/spine-tools/Spine-Toolbox/assets/140422859/9c915698-a2c2-4a31-a06b-330c6a44a664)

**Comment by jkiviluo** [comment]
Please note that the fix @PekkaSavolainen is making will be in the v0.8-dev branch and most likely will never be available in v0.7 (since it's not a critical bug). We hope to move to v0.8 in near future.

**Comment by PekkaSavolainen** [comment]
I'm still working on it since the fix in the PR introduced some other problems. If it ends up being a small fix, I can cherry-pick it to master.

**Comment by PekkaSavolainen** [comment]
FYI @kTelaar

This should now be fixed in both `0.8-dev` and `master` branches.
