### ISSUE TITLE
Option to sort entity classes by dimensionality

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2319]
It would feel more natural to me to see entities displayed in the tree ordered by dimensionality. 

If, for example, I click on the unit class, I will already see all the parameters that involve unit, so I will only ever need to search out the relevant multi-dimensional tree entries if I want to specifically filter by those. This will help manage clutter and get a better feel for the data in my opinion

**Comment by jkiviluo** [comment]
There will be a possibility to order your classes in any way you want down the road. 

However, we could do this by default, as it's probably better than pure alphabetical sort. Of course we should have 0-dimensional classes in alphabetical order and then n-dimensional in alphabetical order after that.

**Comment by PiispaH** [comment]
After the merge of the above PR, entity classes are first sorted by dimension count and then by name.
