### ISSUE TITLE
Show the ID of a class icon and colour in DB Editor

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2320]
It would be very useful to know the ID of a class' icon and colour so that SpineOpt templates can be updated without having to export a JSON just to get that code. Maybe on right click in the class editor widget, you could be offerred the option to copy the id? It could also appear on the tooltip, but you'd also need some way to copy it

**Comment by jkiviluo** [comment]
I think right click context menu in the class editor widget would be nice. Another alternative would be to have a column for it after the icon. Then you could also paste there. Another question is should the color and the icon be separated (so you can copy paste only one of them). One can already copy-paste color from the icon editor, which is nice.

**Comment by PiispaH** [comment]
The right click context menu is implemented by the above pr. Please reopen if you fell that another way would be better.
