### ISSUE TITLE
New added entity class changes dimension after opening Toolbox again

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2322]
Adding a new class `set_link` to the db linked in issue #2312 causes some weird behavior. First the class normal but once the changes are committed and Toolbox is opened again, the new class suddenly has more dimensions than the two that it originally had. Somehow it picks up classes `tool`, `unit`, `node` and `node_link_node` in addition to the classes `set` and `link` it was originally composed of.

**Comment by jkiviluo** [comment]
Probably related to the entity_class_ids that were not deleted from all tables when the original class was deleted.

**Comment by manuelma** [comment]
Ah, I see... then hopefully you have fixed it with https://github.com/spine-tools/Spine-Database-API/commit/7fa4b1e3549cf77387f96e7dfe735e733e681cff @PiispaH ?

**Comment by PiispaH** [comment]
Yes it should work now but only with new databases that aren't already corrupted since I didn't implement any fix for already broken DBs. Maybe some check could be implemented that looks for entries in the DB that don't have a "parent" anymore?

**Comment by jkiviluo** [comment]
Maybe we can trust that people only have working DBs. Down the road we could think about a DB checker tool, but no need to hurry with that.

**Comment by manuelma** [comment]
I suggest we close now. Hopefully we won't see more issues related to these DBs getting corrupted prior to https://github.com/spine-tools/Spine-Database-API/commit/7fa4b1e3549cf77387f96e7dfe735e733e681cff
