### ISSUE TITLE
Parameter value editor does not support non-float array values.

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2328]
In SpineOpt, the `resolution` `temporal_block` parameter can be an array of duration values, but it is impossible to enter these using the parameter value editor in toolbox - it converts everything to floats instead.

This is in 0.7, not sure if it's fixed in 0.8 but I don't imagine it has been.

**Comment by DillonJ** [comment]
Just to add that you can paste the JSON text into the value field in the parameter value pane, but you can't use the array value editor which only wants to know about floats. So duration values are supported in arrays it's just that parameter value editor doesn't allow a user to enter them nicely

**Comment by PiispaH** [comment]
From the Array value editor selecting Duration in the value type dropdown list allows one to input duration values straight into the array? At least for me in the master branch as well as in 0.8-dev.

**Comment by DillonJ** [comment]
Looks like a bad case of user error! Sorry about that!
