### ISSUE TITLE
Add support for PySide6 6.6

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2345]
PySide6 6.5.3 was just released and we seem to have a bunch of problems related to disconnect() signals. We need to investigate if the 6.5.3 version is broken or if we need to adjust our codebase to work with the new version. My hunch is that 6.5.3 is enforcing a policy that you cannot disconnect a signal that is not connected without getting a RuntimeError. **In the meantime, we should disallow 6.5.3 from pyproject.toml on both toolbox and spine-items.**

As an example, here's one traceback from action https://github.com/spine-tools/Spine-Toolbox/actions/runs/6454620214

```
test_add_to_existing_plot (tests.test_plotting.TestPlotPivotTableSelection) ... Traceback (most recent call last):
  File "/home/runner/work/Spine-Toolbox/Spine-Toolbox/spinetoolbox/spine_db_editor/widgets/tabular_view_mixin.py", line 759, in _change_selected_frozen_row
    with disconnect(selection_model.currentChanged, self._change_selected_frozen_row):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/runner/work/Spine-Toolbox/Spine-Toolbox/spinetoolbox/helpers.py", line 1261, in disconnect
    signal.disconnect(slot)
RuntimeError: Failed to disconnect signal currentChanged(QModelIndex,QModelIndex).
```

**Comment by PekkaSavolainen** [comment]
The latest PySide6 (6.6.3.1) seems to be working fine. I'll test it a little bit more and then merge the two PR's above to 0.8-dev branch. By the way, Python 3.12 support was added to PySide6 in v6.6.1, so this should help issue #2522 as well.

**Comment by PekkaSavolainen** [comment]
Done. @soininen what do you think about supporting pyside6 6.6 in `master` as well? It would make life easier for users who jump between branches. Maybe better to let the dust settle in `0.8-dev` first and then do it, if you think it's a good idea.

**Comment by soininen** [comment]
> what do you think about supporting pyside6 6.6 in master as well?

Go ahead if it is not too much work. It definitely makes life easier for us developers who switch branches regularly.
