### ISSUE TITLE
Data connection doesn't notify about missing .sqlite file in its references

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2375]
In the image below the File path to `awf.xlsx` is red because the file no longer exists. However the file `DataConnection.sqlite` doesn't exist anymore either but one could assume from the coloring that it indeed exists.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/1af89353-cf85-41b7-9512-1831cccb361d)

**Comment by soininen** [comment]
There is a special validation mechanism in Data connection to check if database URLs are working (works also for remote databases such as MySQL). Currently, the mechanism is hooked to `DataConnection._log_database_reference_error()` which just prints an error to the logger but could be used to mark the URLs red in the Properties tab as well.
