### ISSUE TITLE
Time series plot is incorrect

### ISSUE THREAD

**Issue by clizbe** [spine-tools/Spine-Toolbox#2383]
*Problem*
When plotting timeseries, the value for each time window appears only at that start time, and the connecting line is the value of the next window.
This causes two problems:
1) The value for the window is incorrect. e.g. The value from 00:00-01:00 is the 01:00 value instead of the 00:00 value.
2) The last window appears empty (because only the value is shown, and not the duration)

*Suggestions*
If it's matplotlib, then `plt.step` has an argument `where='post'` that might fix it. But don't know if this will fix the final time window.
See *Comparison of pyplot.step and pyplot.stairs*:
https://matplotlib.org/stable/gallery/lines_bars_and_markers/stairs_demo.html#sphx-glr-gallery-lines-bars-and-markers-stairs-demo-py

Or maybe the duration of the window needs to be taken into account somehow.

*Example*
1) The 00:00 to 01:00 window shows a value of 30 (incorrect), instead of 10 (correct).
2) The time resolution for the fuel_node is [1,1,1,2] - with the last window being 2 hours. In this example, value for the last window is the same as the previous window. Due to the plotting, it appears not to exist - because it is shown (as a point) at 03:00, but the line does not continue to 05:00.
The other lines also stop at 04:00 despite the model_end being 05:00.
![image](https://github.com/spine-tools/Spine-Toolbox/assets/11889283/3ad2b6dc-f100-4712-a133-c97d7fa89465)

**Comment by soininen** [comment]
The "correctness" actually depends on how you (or your model) interprets the time stamps: is it the beginning, the middle or the end? In any case, the default can be changed if there is strong enough push for it.

**Comment by clizbe** [comment]
I think in SpineOpt we assume it's the value at the beginning of the period, that continues until the next period.
But I don't know how to create more "push" for this.
When I asked other SpineOpters (@manuelma  and @Tasqu) about it - they agreed that it's "plotting backwards" and should be fixed.

**Comment by soininen** [comment]
> When I asked other SpineOpters (@manuelma and @Tasqu) about it - they agreed that it's "plotting backwards" and should be fixed.

That is enough push for me :) Back in the day I asked around which way the steps should be and there was no strong opinion. It is good to get this settled.

**Comment by soininen** [comment]
This turned out to be a real bug. It has now been fixed for the `0.8-dev` development branch but I think it is not critical enough to be backported to `master`.

**Comment by clizbe** [comment]
Thanks for fixing this @soininen! Now the time resolution tutorial I'm making will be easier to follow.

**Comment by soininen** [comment]
> Now the time resolution tutorial I'm making will be easier to follow.

It will probably take some time (months?) for the fix to land on the `master` branch. Perhaps I should speed up the process if the plots are needed for a tutorial.

**Comment by clizbe** [comment]
Yes it would be nice if it's in the Registry version, so that I can use it for the tutorial. But if not, I'll just make the tutorial as-is (with a note about the update) and fix it later.
