### ISSUE TITLE
Confirm project upgrade

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2404]
When we bump the Spine Toolbox project version, ask user whether they want to upgrade the project or not.

**Comment by PekkaSavolainen** [comment]
About the backup file name. When a project is upraded, it creates a backup file of the old `project.json` file. That is e.g. `project.json.bak11` where 11 is the project version. There was discussion that we should add a **tag** to this backup file name. Which tag did you mean? (@jkiviluo, @soininen)

**Comment by jkiviluo** [comment]
Latest Toolbox version tag. So, the filename could become `project.json.bak11_v0.7.1`. If on a commit without a tag, then look backward to the previous tag.

**Comment by PekkaSavolainen** [comment]
> Latest Toolbox version tag. So, the filename could become project.json.bak11_v0.7.1. If on a commit without a tag, then look backward to the previous tag.

Isn't there a bit of a chicked-egg problem here. 

1. You have a project on tag 0.7.1
2. You switch to tag 0.8.0
3. Toolbox asks if you want to upgrade. You click Yes.
4. Backup file is created (project.json.bak11_v0.8.0)

I think you would like that the file is named project.json.bak11_v0.7.1 in this case, right? But this is not possible, Toolbox does not know the commit or the tag where the project was previously saved in.

**Comment by soininen** [comment]
Could we add a `dict` somewhere which maps project version to Toolbox version?

**Comment by PekkaSavolainen** [comment]
I guess we could just save a tag or commit hash into project.json and when a project is upgraded, we just insert it into the backup file name.

**Comment by PekkaSavolainen** [comment]
I would rather not add the tag at all. If we add a tag based on the version of Toolbox, the backup file name will be different if you just switched a branch or if you switched a branch and did `pip install -r requirements.txt --upgrade`. The added benefit is very minimal compared to the work and added complexity.

**Comment by soininen** [comment]
I think it is alright to drop the tag if it gets too complicated.
