### ISSUE TITLE
Exporter fails to filter entities based on the scenario in v0.8

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2411]
I just tried converting FlexTool to v0.8 and it seems like all else is working, but exporter does not filter entities based on the selected scenario. Entities have been migrated from is_active to entity alternative in the DB, but the exporter just exports all entities from the DB despite that my scenario has only a small subset of alternatives (and therefore entities). To be exact: It is filtering parameter values, but it's not filtering entities.

Maybe this is a Spine_DB_API issue - feel free to move.

Which one should take this @soininen or @manuelma?

**Comment by soininen** [comment]
@jkiviluo I could not reproduce the problem with a test project. In my case, the entities were filtered fine. Is the project where you encountered issues available somewhere for investigation?

**Comment by jkiviluo** [comment]
Sent you a project. The exporter actually executes. It's just that the contents are not filtered (when it comes to entities).
