### ISSUE TITLE
DB editor refresh issues in v0.8

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2431]
After using a script to write data to a DB, the refresh button seems to work in unexpected ways. Sometimes it all seems ok, but sometimes not all newly added items appear. This needs to be identified better, but to show I'm not hallucinating, here's a snapshot. The timeline object has not appeared, but the timeline parameter value has:

![image](https://github.com/spine-tools/Spine-Toolbox/assets/40472544/48ed7b3f-788c-4a6b-8e98-2fa7c6ac9bf7)

No traceback.

**Comment by jkiviluo** [comment]
Happened today: I got the exact same parameter row twice in the DB editor view. Only way to get rid of it was to restart Toolbox.

**Comment by manuelma** [comment]
Just to make sure @jkiviluo - this happens directly after you press refresh. You don't do anything other that scrolling and expanding - you don't modify anything after the refresh.

Also, in your experience how often would you say something unexpected happens?

**Comment by jkiviluo** [comment]
> this happens directly after you press refresh

Right. Nothing else.

I think it happens every time when I import new entities. Parameter data seems to come through though.

**Comment by soininen** [comment]
I think I can now reproduce this. I have a script that adds a few entities to entity classes along with some parameter values with different alternatives. After these steps:

1. Purge entities and parameter values in DB editor
2. Run the script outside of Toolbox
3. Press refresh button in DB editor

no new entities or values appear in the editor even though I can confirm that the data is in the database.

**Comment by jkiviluo** [comment]
This is done for now. Improved conflict resolution will be its own issue.
