### ISSUE TITLE
Cannot edit the main program file of tools in Spine or change/create new tools specifications

### ISSUE THREAD

**Issue by SeanByrne08** [spine-tools/Spine-Toolbox#2436]
Hi, 

I have not been able to open a tools main program file in Spine. When I try to open a tool the following screen appears. 

![image](https://github.com/spine-tools/SpineOpt.jl/assets/141043201/9edc8475-2594-4af2-b2b3-47e89be80961)

The code still runs as expected and I have been able to edit the codes using VS Code as the editor. I have not been able to make new tools as I cannot change/create a new tool specification.

Any suggestions on how to fix this problem would be appreciated, Thank you!

**Comment by PiispaH** [comment]
This could be a bug or then some of the ui elements might just be disabled. Try right clicking the Spine Toolbox logo in the upper right corner of the tool specification editor. There you can toggle the visibility of the ui elements. Hopefully this is enough to fix the situation @SeanByrne08.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/87fd607f-3337-4628-a528-308930f132ca)

**Comment by SeanByrne08** [comment]
Hi Henrik,
Yes, this has solved my problem!
Thank you for the quick response!
Sean
