### ISSUE TITLE
Default Julia executable path not working in 0.8

### ISSUE THREAD

**Issue by Tasqu** [spine-tools/Spine-Toolbox#2460]
For whatever reason, seems like Spine Toolbox v0.8 Julia tools don't seem to find the system/project default Julia executable. Julia tools seem to work fine as long as an executable path is defined in their tool specification, though.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/7d404eb8-73d1-4be1-824b-95f3e9c1b08a)
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/7bb19612-72f9-4cab-8479-cf368d67e716)

`juliatest` seems to be complaining that Julia executable isn't found.

## Difference between the tools:

`juliatest` doesn't work when the `Executable` field is left empty, and it's fetched from Toolbox settings.
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/f37c95b7-afb4-4cfe-9966-30ea75d00e19)
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/2f0c7719-2a25-48f4-b52f-b627fd1ebc22)
However, `juliatest2` works when the exact same path is given explicitly in the tool specification.
![image](https://github.com/spine-tools/Spine-Toolbox/assets/77660814/2334cef5-71de-4093-a744-e19fae35070c)

**Comment by PekkaSavolainen** [comment]
I'll take a look.

**Comment by PekkaSavolainen** [comment]
This should be fixed now. Thanks for a very good issue description!
