### ISSUE TITLE
v0.8 bug removing entities

### ISSUE THREAD

**Issue by tarskul** [spine-tools/Spine-Toolbox#2466]
Sometimes when you remove entities, they don't dissappear (especially in the graphview). Sometimes it is resolved by closing/opening the spine db editor, other times the issue persists. I have not yet found consistent behaviour in this issue. I'll add more info if I come across a more consistent problem but I already wanted to notify you of this potential issue.

**Comment by PiispaH** [comment]
Has this still been happening as of late?

**Comment by tarskul** [comment]
Hm, can't really say. I have not been using the spine db editor much lately. At the moment I'm focusing on doing everything with scripts.

**Comment by PiispaH** [comment]
A bunch of this kind of bugs were fixed in the last few months. I suspect that this might have already been fixed somewhere along the line. Please reopen if you encounter this again.
