### ISSUE TITLE
Incompatability with pendulum v3.0.0

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2474]
On a fresh toolbox install of master on a new machine I got a traceback when trying to start toolbox. The punchline was 

```AttributeError: module 'pendulum' has no attribute 'Pendulum'```

I didn't save the full traceback unfortunately. The solution for me was to downgrade the pendulum package from v 3.0.0 to v 2.1.2 (the version installed on another machine with a working toolbox installation)

Edit: the full traceback is available as an image in this post: https://github.com/spine-tools/SpineOpt.jl/issues/833#issuecomment-1876810465

**Comment by datejada** [comment]
@DillonJ please look at this workaround @asashishh found: https://github.com/spine-tools/SpineOpt.jl/issues/833#issuecomment-1876810465

**Comment by DillonJ** [comment]
The workaround of downgrading the pendulum package seems easier that modifying package files outside of the package system. One way or the other, this toolbox issue should be fixed as anyone trying to install latest 0.7 master currently will get this error. @pekkapaa @soininen  what's the best way to address this? Pin the pendulum version or can latest master be easily made compatible with pendulum v3.0.0?

**Comment by PiispaH** [comment]
The issue here is that dagster that is a dependency of spine-engine doesn't support pendulum 3.0.0 in the older versions of it that we are using: https://github.com/dagster-io/dagster/issues/17285. The pull request above just restricts pendulum to version under 3.0.0.

**Comment by soininen** [comment]
A new version of spine_engine that includes the updated pendulum version restriction has been released to PyPI.
