### ISSUE TITLE
Opening two different .sqlite files with the same name in the same Spine DB Editor tab

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2487]
Data Stores A and B both have own databases in their own directories named `test.sqlite`. If both of the databases are opened in the same tab of a db editor and the refresh button is pressed, all of the later added database's entries vanish from the db editor.

**Comment by soininen** [comment]
We should use `spinetoolbox.helpers.unique_name()` to ensure that the db codenames are always unique.

**Comment by PiispaH** [comment]
This is a more general issue that applies to not just databases with the same names so I created a new issue #2526.
