### ISSUE TITLE
Visualize Tool type on Design View

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2491]
We need to visualize the Tool type (Julia, Python, Gams, Executable) on Design View in a better way. You can see the problem in the picture below, where tool `A` is a Python Tool, tool `B` is a Julia Tool, `C` is a Gams Tool, and `D` is an Executable Tool. All Tools here look identical so it would be nice to see which is which. There is a label in Tool properties, which does say that `A` is a Python tool but it's not ideal.

![new_issue_visualize_tool_spec_type](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/a8e4e499-9376-4890-96d8-5d83d49fcb5a)

The idea at the moment is to add a Python, Julia, Executable or Gams icon in the same box as the hammer but I'm open for other ideas as well.

**Comment by PekkaSavolainen** [comment]
Python, Julia, Gams, and Executable icons are now shown under Tools on Design View. Looks a lot better IMO.

**Comment by soininen** [comment]
It looks cool, indeed! However, we may want to reconsider the icon's placement:

![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/aedeaddf-d809-47fc-8f4b-43e4120788b7)

Can we somehow squeeze tool type icons inside the item icon so it will not get obscured behind the link arrows etc.?

**Comment by PekkaSavolainen** [comment]
> Can we somehow squeeze tool type icons inside the item icon so it will not get obstructed behind the link arrows etc.?

This was the intention originally but the tool item insides are getting a bit crowded. Only vacant places inside the item icon are the red circles in the picture below.

![issue_2491_spec_icon_placement](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/a85bef0e-6dbf-414f-a0f3-15b1019438b7)

I can try and tweak it a bit and see how it looks.

**Comment by jkiviluo** [comment]
I'd prefer the location inside the tool icon, bottom left maybe (or top right).

**Comment by PekkaSavolainen** [comment]
> I'd prefer the location inside the tool icon, bottom left maybe (or top right).

Top right is reserved for notifications (exclamation mark in a red circle).

**Comment by PekkaSavolainen** [comment]
Which one's the best?

1.
![issue_2491_option1](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/1d1e8907-b251-496f-92a8-86e45292122f)

2.
![issue_2491_option2](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/7102db86-c07f-4650-8404-827aa890580a)

3.
![issue_2491_option3](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/61667005-6827-4e7d-9ed7-b211ea8082ec)

4.
![issue_2491_option4](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/e7a2b258-336c-4341-871b-8b4503a4479d)

**Comment by soininen** [comment]
> Which one's the best?

1 or 4. Perhaps I'd go with 4.

**Comment by soininen** [comment]
> We also have a problem with tool names taking too much space.

Would it help if the name was rendered on multiple lines?

**Comment by manuelma** [comment]
How about this, icon centered on the bottom left corner:

![image](https://github.com/spine-tools/Spine-Toolbox/assets/11472756/112ce80a-a25f-4332-8299-d4175677e939)

**Comment by PekkaSavolainen** [comment]
I think @manuelma's suggestion wins. I made the change.

**Comment by PekkaSavolainen** [comment]
>>    Would it help if the name was rendered on multiple lines?

> It would be better - keeping the width of the text closer to the width of the icon (can be like 20-40% wider).

Long names are now on multiple lines. Please reopen if not working as expected.
