### ISSUE TITLE
Enforcing parameter type choices in the parameter_definitions

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2496]
Parameter_definition should be able to say what kind of parameter types are ok for the particular parameter. E.g. parameter 'efficiency' could take a constant or a map (for part-load efficiency), but no other parameter types.

Relevant updates to DB structure to enable this:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/40472544/adfd125e-7d54-4412-aabe-cd8f79cd775b)

**Comment by jkiviluo** [comment]
@soininen Should we close this?

**Comment by soininen** [comment]
Yeah, this one has been implemented.
