### ISSUE TITLE
Workflow editor user interface development 

### ISSUE THREAD

**Issue by jeenou** [spine-tools/Spine-Toolbox#2510]
### User function categories:

- Create and edit projects, and create and edit workflows inside projects
    1. Manage projects
    2. Manage settings
    3. Build/modify tool specifications
    4. Manage plugins
    5. Build/modify workflows
    6. Change tool/workflow settings
- Use ready-made workflows for building case studies with modelling tools
    1. Execute workflows
    2. Start/use consoles (view execution)
    3. Use database editor

### General UX suggestions:
- [ ] #2589
- [ ] Open different view based on user function
    1. Project and workflow creator mode
    2. User mode

### Top Menu

- File
    - New Project
    - Open project
    - Open recent
    - Save project
    - Save project as
    - Close project
    - Set project description
    - New DB Editor
    - Settings
        - [x] #2586
        - General
            - Main
                - Custom open project dialog
                - Delete data when project item is removed from project
                - Open previous project at startup
                - Always confirm exit
                - When there are unsaved changes at exit: drop-down menu 
                - Work directory
            - UI
                - Color toolbar icons
                - Color properties widgets
                - Curved links
                - Drag to draw links
                - Prevent items from overlapping
                - Rounded items
                - Show date and time in Event Log messages
                - Smooth zoom
                - Background
                - Link flash speed 
        - Tools
            - GAMS
                - GAMS executable
            - Julia
                - Basic console / Jupyter console
                - Install Julia     
                - Add/Update SpineOpt
                - [ ] Is this intuitive place for this?
            - Python
                - Basic console
                - Jupyter console
            - Conda
                - Select Conda executable
        - Db editor
            - Spine database editor
                - Commit session before closing
                - Show undo notifications
                - Sticky selection in Entity trees
                - Move relationships along with objects in Entity graph
                - Smooth Entity graph zoom
                - Smooth Entity graph rotation
                - Auto-expand objects by default in Entity graph
                - Merge databases by default in Entity graph
        - Spec. editors
            - Specification editors 
                - Save specification before closing
                - Show undo notifications
        - Engine
            - Maximum number of concurrent processes
                - Unlimited
                - Limit to available CPU cores
                - User defined limit
            - Maximum number of open consoles
                - Unlimited
                - Limit to available CPU cores
                - User defined limit
            - Remote execution
                - Enabled
                - Host
                - Port
                - Security
                - Certs
    - Quit
- Edit
    - Undo
    - Redo
    - Copy
    - Paste
    - Paste and duplicate files
    - Duplicate
    - Duplicate and duplicate files
    - Remove
    - Remove all
- View
    - Toolbars
        - Main toolbar
    - Dock widgets
        - Restore Dock Widgets
        - Design View
        - Project
        - Event Log
        - Properties
        - Console
    - Zoom 
        - [ ] This zooms only Design View, so the name could be more descriptive
- Plugins
    - Install Plugin
    - Manage Plugins
- Consoles
    - Start jupyter consol
- Server
    - [ ] There is only one function here, could this be removed and moved to another toolbar?
    - Retrieve project
- Help
    - User guide
    - Getting started
    - About Qt
    - About

### Main Toolbar
- [ ] Basic user don't need to use this toolbar at all, so it could be in some different mode, where you can build your own data workflow
- [x]  When hovered, there will be instruction how to use each tool in this toolbar, but there is a delay in that, so the user can first miss the instructions. Maybe those instructions could become visible also, when button is clicked
- [#2607] Drag-and-drop buttons are not intuitive, they don't look like they should be dragged to the design view. Maybe they could be in the left side of the Design View?
- Items
- [ ] This wasnt a toolbar or button, which was confusing, is this doing something? Can it be removed?
- Data connection
    - Drag-and-drop this onto the Design View to create a new Data Connection item
- Data store
    - Drag-and-drop this onto the Design View to create a new Data Store item
- Data Transformer
    - Drag-and-drop this onto the Design View to create a new Data Transformer item
    - [ ] There is also a arrow, so is it confusing that you can also click the arrow and drag this item? 
- New +
    - [ ] Is it best that the menu opens to the right instead of down?
    - Opens data transformer specification editor
       - Name    
        - Description
        - Select transformation
            - Transformation type
            - Rename entity classes
            - Rename parameters
            - Transform values
        - Rename classes
            - Add
            - Remove
        - Possible classes
        - Load from database
            - Database url
            - Load filter data from database
        - Drop-down Menu
            - Redo
            - Undo
            - Save
            - Duplicate
            - Close   
- Exporter
    - Drag-and-drop this onto the Design View to create a new Data Exporter item
    - [ ] There is also a arrow, so is it confusing that you can also click the arrow and drag this item?
    - New (Exporter specification editor)
        - Opens exporter specification editor
- Importer
    - Drag-and-drop this onto the Design View to create a new Data Importer item
    - [ ] There is also a arrow, so is it confusing that you can also click the arrow and drag this item? 
    - New (Importer specification editor)
        - Select connector for unnamed specification
            - Text/CSV
            - Excel
            - Gdx
            - JSON
            - Datapackage
            - SqlAlchemy
            - After selected, opens importer specification editor
- Merger
    - Drag-and-drop this onto the Design View to create a new Merger item
- Tool
    - Drag-and-drop this onto the Design View to create a new Tool item
    - [ ] There is also a arrow, so is it confusing that you can also click the arrow and drag this item? 
    - New +
        - Opens tool specification editor
            - Name
            - Description
            - Tool type
            - Command line arguments
            - Program files
            - Input & Output files
            - Terminal window 
- View
    - Drag-and-drop this onto the Design View to create a new View item
- From file...
    - Select Specification file
- Execute
    - [ ] "Project", "Selection" and "Stop" are combined with "Execute", but the hierarchy is not clear. "Execute" doesn't look like a title
    - Project
    - Selection
    - Stop

### Project
- This shows the project items
- [x] #2560
- ~~Is there a way of adding new project parts in this Project-view? If I click for example Data stores with right click, there comes only "Open project directory"~~
- ~~Data Stores~~
- ~~Data Connections~~
- ~~Tools~~
- ~~Views~~
- ~~Importers~~
- ~~Exporters~~
- ~~Manipulators~~

### Design View
- Has all the same project parts but vizualized with connections
- You can make connections by dragging arrows
- [ ] Between connections there is circles with icons for filtering the scenarios for example, but those are not intuitive
- Excel_input_data
    - [ ] What is the purpose to have this and that Import_from_Excel-piece here? Can those be combined?
- Import_from_Excel
    - This is for importing excel data
    - Opens when double-clicked
    - This same editor opens also from the toolbar
- Init
- Initialize
- Input_data
- Open_summary
- Import_results
- Results
- To_Excel
- Plot_results
- Plot settings

### Event Log
- In the event log we can see all the events in the program, what view has been opened for example
- [ ] Is this necessary for basic user? Maybe it could be extra feature but not in the main view in the beginning

### Console
- Guide: Select an executing item to see its console
- [ ] Its not intuitive to know how to select an item

### Properties
- Select an item to view its properties
- Specific use for every project item etc.

**Comment by PekkaSavolainen** [comment]
The issue desciption needs a bit of cleaning up. You @jeenou clearly had the FlexTool project open while doing the list. E.g the export_FlexTool3_csv, etc. are Specifications that are available for that project only. Also, all the stuff (Excel_input_data, Import_from_excel, etc.) under the Design View section are project items in the FlexTool project. I think these should be removed from this issue.

**Comment by jeenou** [comment]
Oh, you're right! I can check that list again so there would be no project related stuff there.

**Comment by manuelma** [comment]
I believe [this](https://github.com/spine-tools/Spine-Toolbox/issues/2607) addresses some of the points here. Please consider updating the description?

**Comment by jeenou** [comment]
This issue was an overview for workflow editor planning. The issues here will be resolved, when planning different user modes for toolbox. The contents of this issue will be added to the design and planning documents of different user modes and will not be added as individual issues right now.
