### ISSUE TITLE
Docs up to date for 0.8

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2513]
Here are a couple of things that were discussed in the MOPO meeting in Leuven on what to do for the documentation in preparation for 0.8.

### Overall
- Formatting by General consistency in #2156
- Check that new features in 0.8-dev branch that are worth to mention in the documentation are included in there
- Images may have gone out of date (at least Tool properties and spec editor UI have changed)

### Related to database editor changes
- [x] #2306
- [ ]  Add section or even own page about configuring and viewing the dynamic graphs
- [x] Replace references to objects and relationships with entities everywhere in the docs:
  - getting started
  - API Reference also has some mentions of objects and relationships since some of the code still has these mentioned

### Terminology
- [x] Update terms that need updating (new ones could still be added)

**Comment by jkiviluo** [comment]
closing, but new issue on the missing task
