### ISSUE TITLE
Update copyrights

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2514]
The copyright notices have been updated last time in 2022. Since then, we've started a new project which now holds the copyright so I guess we need to add a new line for that:

```
# Copyright (C) 2017-2022 Spine project consortium
# Copyright (C) 2023-2024 Mopo project consortium
```

Also, the copyright update scripts in `bin/` should be updated to handle the new line.

**Comment by soininen** [comment]
Done.

**Comment by soininen** [comment]
Reverted the changes. "Mopo consortium" is probably too restricted author - we should mention our contributors as well.

**Comment by jkiviluo** [comment]
I tried to read up on this. This page was pretty good: https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects

Based on that, let's do "Copyright Spine Toolbox contributors".

**Comment by DillonJ** [comment]
> Based on that, let's do "Copyright Spine Toolbox contributors".

As an example, there are plenty of constributions in the period between the two projects
