### ISSUE TITLE
Project item execution rank number not visible

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2518]
In a picture in #2516 the execution rank of the project items is not visible due to the background and number being both black. Even though in the discussion it is not clear what caused this, at least on my system changing the system wide color scheme to dark caused the numbers to become far less visible.

The background should therefore probably be set to always have the light version so that the numbers are visible at all times.

**Comment by PekkaSavolainen** [comment]
Donald.
