### ISSUE TITLE
Backup a datastore before migrating

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2521]
I believe we should always back up a datastore before migrating. There are plenty of reasons, chief of which is that the action is not reversible. Also, 

1. The migration might break or fail
2. The migration might be buggy and corrupt data
3. A user may be trying out a different branch and not intend to erreversably upgrade the DB
4. A user may have different versions of Toolbox across different machines and unintentionally get locked to a higher version

**Comment by jkiviluo** [comment]
I mostly agree, but I think the user should get a pop-up asking whether to 'not migrate', 'back-up and migrate', and 'just migrate'. Back-up and migrate could be highlighted and pre-chosen (just press enter and it's done). Back-up would overwrite an earlier back-up (to prevent filling up disks) - this should be told in the prompt. 

'not migrate' should result in something sensible. For example, when executing a project with old DBs, Toolbox first asks about migration but does not stop execution if I don't want to migrate. It should also inform the user to use Toolbox version that is compatible with the DB version (preferably it should show the version number).

**Comment by DillonJ** [comment]
My concern about this is that a user, when prompted with this, might not immediately realise the implications - that it is an irreversible process. We're conditioned a little to ignore constant pop ups. I don't see the downside of the backup - for me it seems to be standard practice... a user can always delete it later. However, your proposal is definitely better and safer than what we have now, but in my opinion, not safe enough.

I feel like if we are making "just migrate" even an option, we would need to strongly caveat this and present a second popup asking for confirmation and saying something like this: 

"Warning, this is an irreversible process. We may have made errors in the migration code and your data may be irreversibly lost or corrupted".

I wonder do the escience guys have an opinion on what would be considered standard practice here?

**Comment by suvayu** [comment]
On Fri, 26 Jan, 2024, 09:47 Jody Dillon, ***@***.***> wrote:

> I feel like if we are making "just migrate" even an option, we would need
> to strongly caveat this and present a second popup asking for confirmation
> and saying something like this:
>
> "Warning, this is an irreversible process. We may have made errors in the
> migration code and your data may be irreversibly lost or corrupted".
>
> I wonder do the escience guys have an opinion on what would be considered
> standard practice here? @suvayu <https://github.com/suvayu>?
>

I think your suggestion is a good idea. While single prompt is likely to be
skipped without reading, a second one definitely will catch the attention.

I can think of one possible example, try deleting a repository on GitHub,
on the final prompt they also ask you to type in the exact org/repo name
into a text field, and enables the delete button only on match.

I've seen similar UI in CLI applications as well where the tool asks for
confirmation by asking the user to type "yes" into a prompt.

--
Suvayu

>

**Comment by jkiviluo** [comment]
Sometimes DBs are large and you don't want to create extra copies due to disk space (it will also slow you down). Second prompt is fine, although I feel it's bit unnecessary ('just migrate' is not the default option). First click could also turn the button to 'Really? Click to confirm'.

**Comment by manuelma** [comment]
Implemented via https://github.com/spine-tools/Spine-Toolbox/pull/2605 - please reopen if not good.
