### ISSUE TITLE
Enable Python 3.12 support

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2522]
Python 3.12 has been released some time ago. However, we report our maximum supported version to be 3.11.

- Check that Spine Toolbox works on Python 3.12
- Change the maximum supported version to 3.12
- Check if the warning about the need to install Microsoft build tools applies to Python 3.12 as well

**Comment by soininen** [comment]
It turns out we cannot enable Python 3.12 support yet. The reason is the `pendulum` package that [gained Python 3.12 support only in version 3.0](https://github.com/sdispater/pendulum/issues/696) but Dagster requires Pendulum version less than 3.0.

Additionally, Toolbox installation on 3.12 still requires Microsoft build tools on Windows systems which should be mentioned in the documentation once Python 3.12 is supported.

**Comment by manuelma** [comment]
This might sound crazy but can we just ditch dagster? We are hooked on an older version, using API that is deprecated in the most recent version. My feeling is we could replicate the bit of functionality that we use from that old dagster with not too much effort (but I might be wrong)?

**Comment by soininen** [comment]
> This might sound crazy but can we just ditch dagster?

You are not crazy. I have been pondering the same. Maybe we should first try to upgrade it and if that seems even a little bit messy, then just ditch?

**Comment by soininen** [comment]
After we got rid of Dagster and its dependencies, outdated 3rd party packages are not blocking Python 3.12 anymore.

However, Toolbox crashes with a segfault immediately upon startup with Python 3.12. I need to still figure out what goes wrong.

**Comment by soininen** [comment]
Python 3.12 and later is now allowed.
