### ISSUE TITLE
Ditch Dagster

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2523]
As @manuelma puts it in #2522:

`We are hooked on an older version, using API that is deprecated in the most recent version. My feeling is we could replicate the bit of functionality that we use from that old dagster with not too much effort (but I might be wrong)?`

I have the same feeling. We are not really using much of Dagster's functionality anyway and getting rid of it would fix issues with dependencies and Python versions such as #2522 and #2517

**Comment by soininen** [comment]
A Python package to look into as a possible Dagster replacement: [Joblib](https://joblib.readthedocs.io/en/stable/).

**Comment by jkiviluo** [comment]
Joblib looks cool

**Comment by manuelma** [comment]
The main features of joblib don't look very well aligned with our requirements though. All we need is a system to replace deprecated dagster's PipelineDefinition, SolidDefinition, etc. In other words, we need to be able to (i) define a pipeline (set of jobs where the output of some is the input of some others) and (ii) a function that given a pipeline returns a list of all the jobs that are ready to execute. It should be straightforward to implement and much easier to maintain in the long-run.

**Comment by PekkaSavolainen** [comment]
This is done. Nice work @manuelma. Dagster is no longer a requirement in 0.8-dev branch. If you plan on hopping between `0.8-dev` and `master` branches you may want to keep dagster in your toolbox environment until these branches have been merged.

**Comment by manuelma** [comment]
Thank you @PekkaSavolainen - to be fair you did most of it.
