### ISSUE TITLE
Adding another database to editor doesn't keep entities

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2526]
If you have one database A (has entities) open in an editor and add another database B (also has entities), once the database is refreshed the newly added database's entities disappear. Sometimes also the new databases entities won't appear at all when added for the first time.

**Comment by soininen** [comment]
Is this about refreshing from the button on the DB editor's tool bar? We have a PR open that should fix the issue.

**Comment by PiispaH** [comment]
Yes it is, good!

**Comment by soininen** [comment]
Alright, lets hope #2477 will fix this, then.
