### ISSUE TITLE
Entity names not visible when they are added and tree view expanded

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2542]
How to reproduce:

1. Have a db with entity class "A" that has entity "a" under it that is committed.
2. Open that db in db editor without expanding the view of entity class "A"
3. Add new entity class "B" and entity "b" under it.
4. Expand the view of entity class "B" by pressing the arrow next to it.

What happens is that the column width of the column "name" in the entity tree view doesn't expand in order to allow the entity name "b" to show. Instead it get buried behind the next column. When entity class "A" is then expanded, the column width also becomes larger allowing the viewing of the entity names.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/f903a0c7-435a-4e57-8ad2-4eb5d1105795)

**Comment by manuelma** [comment]
@soininen just curious have you tested performance on large DBs? I believe that was the purpose of ResizingViewMixin.

**Comment by soininen** [comment]
> @soininen just curious have you tested performance on large DBs? I believe that was the purpose of ResizingViewMixin.

I don't have huge databases at my disposal, but we can tweak the number of rows used for resizing by [setResizeContentsPrecision()](https://doc.qt.io/qt-6/qheaderview.html#setResizeContentsPrecision) if the default of 1000 rows proves to be problematic.

**Comment by manuelma** [comment]
Fair enough - I remember having problems with that. Never found a good number so performance was not degraded for large DBs, but resizing was as I wanted it - I constantly needed to resize the views myself... What was the problem with the ResizingViewMixin exactly?

**Comment by soininen** [comment]
> What was the problem with the ResizingViewMixin exactly?

Honestly, I cannot say I have ever been really happy with how most views resize their columns in Toolbox.

This issue describes one such problem and simply setting resize mode to `ResizeToContents` seems fix it and make the column widths behave more like I would expect. I am not entirely sure if I am still satisfied with the situation, though, so we will see if `ResizingViewMixin` makes a comeback...

**Comment by manuelma** [comment]
I hear you - I guess I'm just worried about the performance. Maybe we need to bake some performance tests into the unit-tests somehow? I remember ResizeToContents being a bottleneck...

**Comment by soininen** [comment]
Tree views seem to work just fine with the automatic resizing to content but I have now reverted the feature from most table views and replaced it by stretching columns instead. I think it is much better than before and there should not be performance issues anymore. However, I am sure others may have other preferences so please open new issues if you feel like the columns are fighting against you, not with you.
