### ISSUE TITLE
DB editor "Copy name(s) as text" enabled for empty cells in parameter view

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2548]
The Copy name(s) as text -option from the hamburger menu of db editor is usually disabled when there is nothing to copy. When an empty cell in parameter view is selected the option becomes available and it just copies an empty string into the clipboard. Doesn't really matter much but to make things more consistent in the sense that if there is nothing to copy, don't allow the action, maybe also this case could be treated like nothing was selected.

**Comment by DillonJ** [comment]
I would argue that an emtpy cell _is_ something to copy - it's still information. Especially if that empty cell were itself contained within a broader selection, you would definitely want to copy it to preserve the structure of the data.

**Comment by jkiviluo** [comment]
If this would be implemented, it should not apply to copies of multiple cells, only when one cell is selected. But I think this is not worth implementing.
