### ISSUE TITLE
Remove Project Widget

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2560]
![new_issue_remove_project_dockwidget](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/33b92424-de00-4dbc-bd6d-838dc9cddf58)

**Comment by PekkaSavolainen** [comment]
Done. Everything else should be ok but some pics in the User Guide still show the project dock widget. I'll leave this open until I have updated the pics in chapters:
- Getting Started
- Settings
- How to set up SpineOpt.jl
- Setting up Consoles and External Tools
- Executing Projects

**Comment by soininen** [comment]
@PekkaSavolainen Thanks a lot for taking care of this! I will not miss that widget nor the code that came with it.

**Comment by manuelma** [comment]
RIP ProjectItemModel.
