### ISSUE TITLE
Allowing rubber-band selection with right mouse button

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2561]
I sometimes try to select multiple items in design- and graph view by pressing down the right mouse button and dragging the cursor. I guess this is something that I have gotten used to doing from other programs. Maybe this could be convenient for some alongside the existing CTRL + drag option.

**Comment by soininen** [comment]
To my understanding, the control key is there because there should be a way to drag the Design view around. Still, it is not discoverable and many users keep asking if it is possible to do the rubberband. Also, personally I would like to be able to select without extra keys.

One option is to reserve the left button for rubberband and use the right button for dragging the view.

**Comment by jkiviluo** [comment]
I like doing it the other way around: right button for dragging the view and left button for selecting. I think people will then be more likely to discover the feature - and that's important.

**Comment by manuelma** [comment]
@PiispaH I am not opposed to anything as long as it is a widely accepted standard that many users will find useful.

Also, it would be good if the same rules are applied to other views like the graph view.

**Comment by PiispaH** [comment]
> Also, it would be good if the same rules are applied to other views like the graph view.

Ahh yes, I was thinking about the design view in this issue but didn't write it clearly...

**Comment by PekkaSavolainen** [comment]
I believe this needs some fixing.

1. Open Design View context-menu
2. Click somewhere on Design View to close the context-menu
3. Try to make a connection

-> Drawing connections does not work anymore

**Comment by soininen** [comment]
Alright, I missed *that* combination of clicking stuff on design view. Thanks for the heads up, will fix.
