### ISSUE TITLE
Changing Python interpreter in Settings does not affect Tools

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2587]
1. Make a Python Tool that uses Basic console, leave the Interpreter to its default value
2. Close the Specification editor
3. Change the Python Basic console in Toolbox Settings
4. Reopen the Tool specification editor
5. The Basic console is still the same as in step 1

Expected behavior would be that the Tool's basic console changed when the Settings change.

**Comment by PekkaSavolainen** [comment]
Duplicate of #2446?

**Comment by soininen** [comment]
> Duplicate of #2446?

Looks like it is. Thanks for the heads-up!
