### ISSUE TITLE
Purge has two distinct icons in the UI

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2592]
Currently there are two icons in use to symbolize purging a database: a lighting bolt in Data Store properties and box thingy in the db editor hamburger menu. Having only one of these icons used would make the UI more consistent.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/8439f121-b59d-4530-bfc8-40e662cdda38)
![image](https://github.com/spine-tools/Spine-Toolbox/assets/98282892/17fd4ccd-20a5-414d-93a9-d3a5ef3ac414)

**Comment by PiispaH** [comment]
Now only one symbol is in use. The box icon is already in use in the db editor so decided to use the lightning bolt everywhere.

**Comment by manuelma** [comment]
Nice choice, the lightning bolt is the one used in the arrow too.
