### ISSUE TITLE
Entity group changes into entity when db editor opened again

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2598]
If an entity group A is created and committed and the editor is closed, upon opening the database again, the group A will not show its members anymore and the icon has changed to the corresponding entity classes icon. Somehow the db editor treats it like an entity and not like an actual entity group.

**Comment by manuelma** [comment]
Should be solved by https://github.com/spine-tools/Spine-Toolbox/commit/2840a748fef4f2452468be5e87dff46407ba024d
