### ISSUE TITLE
Commit viewer not showing the affected items

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2602]
in #1996:

> It seems like the commit history viewer only shows values that have changed

It seems to not even show those values anymore; I changed a few parameter values and the commit viewer doesn't show the changes:

<img src="https://github.com/spine-tools/Spine-Toolbox/assets/98282892/8f872699-fec3-43d8-91b1-8d544cf377d2" width="60%">

**Comment by jkiviluo** [comment]
@manuelma Any clue?
