### ISSUE TITLE
Try and make main toolbar more usable

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Toolbox#2607]
In the Leuven meeting, some people were complaining about the main ribbon being inintuitive. I think they're partially right. One thing is the Execute section could be a separate ribbon so it can be moved around. But the main issue is, it is a bit difficult to find the specifications and when you expand them, the ribbon becomes a bit weird.

I think a good option to try and mitigate these problems is to put the specs in an entire new ribbon. Should be very easy to do, so I might give it a quick try.

**Comment by soininen** [comment]
Should we move the plugin bars to the vertical position as well? When I open Toolbox I get this:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/b1503822-611b-4281-9bfb-aa17571947ae)

Would this make more sense?
![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/bfb1865f-c3fa-41b4-9bf6-d7d2fecec158)

**Comment by manuelma** [comment]
Probably, or keep them all on the top tool bar area for now. I didn't intend to put those two on the left, actually... was just an accident.

**Comment by soininen** [comment]
> I didn't intend to put those two on the left, actually... was just an accident.

I see. Sorry about the noise, then!

**Comment by manuelma** [comment]
No, thank you! Let's keep them at the top for now then. Otherwisw feel free to tweak. My main goal here was to put specifications in their own toolbar rather than inline the main toolbar next to each item - I thought that was too confusing.

**Comment by PekkaSavolainen** [comment]
When I drag any Tool Specification from a plugin (e.g. **SpineOpt plugin**) toolbar or from the **Specification** toolbar to the Design View, the specification set for the new Tool is the first Tool specification in the project.

To reproduce:
1. Drag Run SpineOpt from the Plugin Toolbar to the Design View
2. Click Ok to Add Tool
3. See `Tool Properties`. The specification is **not** `Run SpineOpt` as it should be but the first Tool Spec in your project.

**Comment by PekkaSavolainen** [comment]
Also, the _TitleWidget(QWidget) seems a bit off as can be seen from @soininen's screenshots above. If you look closely the title (e.g. SpineOpt plugin) is written twice. Once with white text and a second time with black text. Could we simply use a QLabel as a _TitleWidget() instead and put the title and the draggable buttons into a layout inside the toolbars? This would probably fix #2624 as well.

**Comment by manuelma** [comment]
> Also, the _TitleWidget(QWidget) seems a bit off as can be seen from @soininen's screenshots above. If you look closely the title (e.g. SpineOpt plugin) is written twice. Once with white text and a second time with black text. Could we simply use a QLabel as a _TitleWidget() instead and put the title and the draggable buttons into a layout inside the toolbars? This would probably fix #2624 as well.

Sorry, https://github.com/spine-tools/Spine-Toolbox/issues/2624 is solved, forgot to close it. You could try the idea with the layout, I couldn't make it work and look nice within a QToolBar. Alternatively we could keep the current design and just fix the paintEvent so it does the white stroking right.

**Comment by PekkaSavolainen** [comment]
> You could try the idea with the layout, I couldn't make it work and look nice within a QToolBar. Alternatively we could keep the current design and just fix the paintEvent so it does the white stroking right.

That's fine, I'll take your word on it. Maybe fixing the paintEvent is easier then.

**Comment by PekkaSavolainen** [comment]
> Alternatively we could keep the current design and just fix the paintEvent so it does the white stroking right.

@manuelma I just noticed that the white text is there on purpose. I thought it was a shadow or some rendering bug. What's the deal with it? Artistic self-expression?

**Comment by soininen** [comment]
I have a few plugins installed and when opening a project with multiple specifications (a few exporters, importers and tools, nothing special) so I have quite a few icons on the toolbars and they take a lot of space. Of course, I can move the toolbars around to make the window fit without needing to get an ultra-wide monitor, but it makes me wonder if we could do something to make the toolbars scale better with the number of icons.

**Comment by manuelma** [comment]
> > Alternatively we could keep the current design and just fix the paintEvent so it does the white stroking right.
> 
> @manuelma I just noticed that the white text is there on purpose. I thought it was a shadow or some rendering bug. What's the deal with it? Artistic self-expression?

Haha almost. It's supposed to be text-stroke, looks good on Linux, bad on Windows. Makes the title outstand from the other text. Should be easy to fix or we can just remove it.

**Comment by jkiviluo** [comment]
Just noting that Pekka is working on this (demoed in last Toolbox developer telco)

**Comment by PekkaSavolainen** [comment]
Made a new issue #2785 related to this.
