### ISSUE TITLE
Parameter value list options not shown with 0.8 when creating new parameter

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2609]
Parameter value list options not shown with 0.8 when creating new parameter
![image](https://github.com/spine-tools/Spine-Toolbox/assets/84875787/233313a2-62b3-4796-a0ef-6185a1e7be04)
![image](https://github.com/spine-tools/Spine-Toolbox/assets/84875787/a928de8c-bdfb-4582-a2e4-a595cc870c0e)

**Comment by ArttuTupala** [comment]
The problem is not just visual, whatever you put there, it will transform it to None

**Comment by ArttuTupala** [comment]
If the parameter value list used is changed (or changed back), it will work correctly. So, it seems to be a problem with the database upgrade

**Comment by manuelma** [comment]
Fixed by above commit, please reopen if not the case.
