### ISSUE TITLE
Convert yellow loopbacks automatically to jumps

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#2614]
If the user is about to do a loop into a DAG, the link is converted automatically to a jump.

For example, in the 'dag' below, the link from `Tool to Data Store` would be converted into a blue link automatically (because in this example, the `Data Store to Tool` link was drawn first).

![new_issue_crash_when_opening_project_with_loop](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/826a3d61-a91f-4ef4-ab10-f496d52eab03)

Fun fact: If you do a project like this and save it, then close and relaunch the app. toolbox crashes at start up (provided that you have enabled 'Open previous project at startup' in Settings). This proposal would solve this issue since it would be impossible to make loops with yellow links after the change.

**Comment by soininen** [comment]
Maybe we should just prevent such links? Conversion to jump might come as unexpected surprise.

**Comment by soininen** [comment]
How about we ask the user if they want to turn the link into a jump?

**Comment by jkiviluo** [comment]
I like the idea of converting loops automatically to blue links. Other option would be to disallow yellow links and give a pop-up explaining why you can't do that and also how to make a loop (using alt).
