### ISSUE TITLE
After pressing cancel on the migration to 0.8 window, no other data stores can be opened

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2619]
After pressing cancel on the database migration to 0.8 window "incompatible database version", no other data stores can be opened.
Or the same data store item if database is changed.
Restart fixes.

**Comment by manuelma** [comment]
Thanks for this @ArttuTupala 
Doesnt't seem to happen everytime?

**Comment by ArttuTupala** [comment]
For me, it happens every time. For other 0.7 databases, the same migration window can be opened and even the migration can be done, but afterwards the database won't open if the cancel button has been pressed in the session.

**Comment by ArttuTupala** [comment]
Correction: Double clicking the store does not work, but right click Open URL in Spine DB editor -> New window works

**Comment by soininen** [comment]
Data stores seem to work fine now with regards to database migrations.
