### ISSUE TITLE
Importer's inner boxes

### ISSUE THREAD

**Issue by Alireza64z** [spine-tools/Spine-Toolbox#2641]
I accidentally closed the internal boxes of the Importer, and now I cannot reopen them. Can you please guide me on how to restore its inner boxes? I have tried uninstalling and reinstalling Spinetoolbox, but it did not work. I have attached a picture of the Importer for your reference.
![Importer_box](https://github.com/spine-tools/Spine-Toolbox/assets/141316670/381d9b27-b54b-47cc-8800-a002096d67cd)

**Comment by PekkaSavolainen** [comment]
Right-click somewhere in the 'banner' and you can select which dock to revive.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/43600314/5381e03f-c423-4de2-8492-5f0949cf27e8)
