### ISSUE TITLE
When opening the importer, a vast majority of the window is a blank space

### ISSUE THREAD

**Issue by e-zaline** [spine-tools/Spine-Toolbox#2661]
Hello,
I did not have this issue before, but for a few months now, when I open my importer in Spine Toolbox, half of the window is a blank space. I then need to manually adjust the inside windows to reduce this blank space.
I have noticed the same issue on my colleague's computer.
For info, I am using FlexTool.
Thank you

![image](https://github.com/spine-tools/Spine-Toolbox/assets/62605130/6cbdb222-f76c-42ea-9c1b-153495cc889e)

**Comment by PekkaSavolainen** [comment]
Found the problem and a fix coming up soon. I believe a line was removed by mistake (when doing #2329) a couple of months ago from the master branch that introduced this bug.

**Comment by PekkaSavolainen** [comment]
Should be fixed now. Please reopen if not.

**Comment by e-zaline** [comment]
It's fixed, thanks!
