### ISSUE TITLE
Check that CHANGELOG.md is up-to-date for 0.8-dev

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2693]
We are planning to merge 0.8-dev to master soon. To prepare for that, we should ensure that CHANGELOG.md is up-to-date and contains at least the most important changes compared to 0.7.x.

**Comment by soininen** [comment]
I did a small update to `CHANGELOG.md`. I guess I am happy with it now.

**Comment by PekkaSavolainen** [comment]
Looks good to me.

**Comment by soininen** [comment]
This ship has now sailed.
