### ISSUE TITLE
Setting the default julia environment does not work

### ISSUE THREAD

**Issue by tarskul** [spine-tools/Spine-Toolbox#2702]
Consider a workflow with a simple input data base, a tool with a specific script in the middle and an output data base. The script is a simple julia script that reads the input data base and writes to the output data base. However, the julia script uses a package that is in a julia environment. For example a setup that uses SpineOpt.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/120471470/d2c3eebe-f80b-4925-ba21-f0fe437d3441)

By setting the julia environment in the settings (as below)
![image](https://github.com/spine-tools/Spine-Toolbox/assets/120471470/c15379b5-2c1f-41b6-b419-180a444d7098)

You get the following error:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/120471470/1926a26b-60ab-4afd-9f38-fcb18550fbef)

But if you set the julia environment in the tool itself:
![image](https://github.com/spine-tools/Spine-Toolbox/assets/120471470/ac37dd3e-6f4f-4905-937d-29c96f88b746)

Then it runs just fine.

From this it seems that the global setting does not work as intended.

**Comment by PekkaSavolainen** [comment]
Thanks @tarskul. Run SpineOpt is a bit of a special case because the Tool spec is actually coming from it's own Git repo (it's a plugin). There may be a bug in using the global (julia environment) settings for plugin specs.

Your workaround should work though. Just remember to save the Tool spec after setting the Julia environment in the Tool Specificaiton Editor.

**Comment by tarskul** [comment]
This was merely an example. The behaviour is the same if you use a local install of SpineOpt with your own tool specification (which I use to run the 0.8-dev version).

**Comment by PekkaSavolainen** [comment]
Found the bug. Fix coming up...

**Comment by PekkaSavolainen** [comment]
Should be fixed now. Please reopen if not.
