### ISSUE TITLE
Opening a database in DB editor tab while still loading previous database mixes data from both

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2709]
1. Open a large enough database in DB editor so you have time to go to hamburger menu -> open and browse to another database while the original database is still fetching
2. Database items that were already loaded from the original database get correctly cleared away from sight but things that finish fetching after opening the new database still appear on screen. 

Cancelling fetching might be too difficult. Maybe we could just disable the open action while fetching?

**Comment by jkiviluo** [comment]
Noticed similar behavior when I had two DBs with the same 'name' (not file name). I hadn't spend time to explore that - just noting here.

**Comment by jkiviluo** [comment]
Maybe connected: https://github.com/spine-tools/Spine-Toolbox/issues/2606#issuecomment-2061291232
