### ISSUE TITLE
Better ordering of parameters 

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2711]
If I want to edit parameters from the dependent classes, I typically choose the full n-d class and not a 0-d class. Conversely, when I want to edit parameters of the 0-d class, I choose that and I would expect to see them first. However, due to alphabetical ordering of classes, I might see parameters of one of the dependent classes first and that's not nice - I need to go scrolling which I despise.

So, I think it would be better if all the parameter_definitions and parameter_values of the 0-d class were shown first and only then, in alphabetical class order, the parameters from the dependent classes.

There are more changes to ordering in the https://github.com/spine-tools/Spine-Toolbox/issues/2492, but this should something quick and simple, right?

**Comment by DillonJ** [comment]
We had a related issue where it would be nice to reorder how items are displayed in the tree. In my view, this would make understanding the data a little easier

**Comment by DillonJ** [comment]
We have this issue https://github.com/spine-tools/Spine-Toolbox/issues/2008

It would be great if we could do something with this. I notice the milestone for the other issue is constantly being bumped down the road

**Comment by PiispaH** [comment]
This caused some problems: #2833. Trying again hopefully with better results.
