### ISSUE TITLE
Selecting dependent n-d entity from entity tree fails to filter unrelated entities from Parameter value table

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2719]
See the screenshot below. The intention here is to hide "knife" and "spoon" on the Parameter value table because I have selected stuff that contains "fork" only.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/40c7c5fe-f8cc-495e-a9aa-71f31e16867f)

**Comment by PiispaH** [comment]
Related to #2405
