### ISSUE TITLE
Importing objects and relationships from json in v0.8

### ISSUE THREAD

**Issue by tarskul** [spine-tools/Spine-Toolbox#2725]
SpineOpt v0.8 still uses objects and relationships which works most of the time. However, we've found a bug. Objects, of which the object class is not defined in the json are not imported (whereas it does work in v0.7).

Steps to reproduce:
1. make a new spine db
2. import `spineopt_template.json`
3. import `basic_model_template.json`
4. in v0.7 the contents would be imported, in v0.8 they are not

Currently, if you want it to work, you have to add the object classes to the `basic_model_template` (and remove the relationships for simplicity), the contents will be imported.

**Comment by jkiviluo** [comment]
This applies also to entities - if the entity_class is not in the template before the entity that is to be imported, the entity won't obey the import order.
