### ISSUE TITLE
Import scenario crashes / won't import 

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2738]
Import item type scenario, forces having "scenario active flags" as pivot, if there is something else (like alternatives), it crashes.
![image](https://github.com/spine-tools/Spine-Toolbox/assets/84875787/374034cf-1a50-4c05-b142-5bd45ed19a01)

If using item type scenario alternative, it only creates alternatives, not scenarios.

**Comment by nnhjy** [comment]
Spotted the same issue.
Hope this sample could help: [scenarios_import.zip](https://github.com/spine-tools/Spine-Toolbox/files/15272757/scenarios_import.zip)

**Comment by soininen** [comment]
Closed the wrong issue, sorry.

**Comment by soininen** [comment]
The active flag mapping component is now gone from Importer (and Exporter, too). It is also possible to reorder mappings/source tables by drag and drop which allows importing scenarios before scenario alternatives. Hopefully this fixes the current issues.
