### ISSUE TITLE
Importer - Entity alternative

### ISSUE THREAD

**Issue by e-zaline** [spine-tools/Spine-Toolbox#2748]
Hello and congrats on v0.8!
Now that we don't need the "is_active" parameter but a "Entity alternative" set to true, how can we set that up in the importer specification editor?

**Comment by soininen** [comment]
I am afraid we may have forgotten to implement entity alternatives in importer and exporter... The previous is_active parameter should still work as a fallback mechanism even without tools, features and methods when importing. @manuelma might know better.

**Comment by e-zaline** [comment]
Hello @jkiviluo and @soininen,
Would it be possible to prioritize this topic and not wait for v0.9.0?
Now that I have the issue #2864 with the importer of is_active not working, it really makes FlexTool barely usable at all. 
Alternatively maybe you have a workaround? This is quite urgent on our side.
Thanks!

**Comment by soininen** [comment]
I am going to work on this now.

**Comment by soininen** [comment]
It is now possible to import entity alternatives. To setup the imports for existing mappings, check the "Import entity alternatives" check box in Entity class imports and set the Source reference for the "Entity activities" mapping.
![image](https://github.com/spine-tools/Spine-Toolbox/assets/19147159/59e90e9e-7be9-4e83-911d-e2ae49947db0)
