### ISSUE TITLE
error in importing multiple cell blocks from `xlsx`

### ISSUE THREAD

**Issue by nnhjy** [spine-tools/Spine-Toolbox#2760]
This [example.zip](https://github.com/spine-tools/Spine-Toolbox/files/15275498/example.zip) should explain the problem. There are 4 cases where some parameter values of `unit__node__node` are to be imported. Cases 1 and 2 don't work despite 3 and 4 working.

**Comment by soininen** [comment]
The bug has been fixed in `spinedb_api`. The second case works after you select the "Import entities" checkbox in Importer specification editor.
