### ISSUE TITLE
Show plot data and copy plot data not working when plotting Maps with structure datetime -> timeseries

### ISSUE THREAD

**Issue by DillonJ** [spine-tools/Spine-Toolbox#2762]
If I plot the timeseries contained in a map either all together or individually, it plots fine, but I can't show the plot data or copy the plot data because the series names are datetimes.

Here is the TB

Traceback (most recent call last):
  File "c:\Workspace\Spine\spinetoolbox\spinetoolbox\helpers.py", line 121, in new_function
    return func(*args, **kwargs)
  File "c:\Workspace\Spine\spinetoolbox\spinetoolbox\widgets\plot_widget.py", line 106, in show_plot_data
    rows = self._get_plot_data()
  File "c:\Workspace\Spine\spinetoolbox\spinetoolbox\widgets\plot_widget.py", line 81, in _get_plot_data
    label = " | ".join(["None" if name is None else name for name in xy_data.data_index])
TypeError: sequence item 0: expected str instance, DateTime found

**Comment by PiispaH** [comment]
This is only in the master branch, meaning 0.8. I don't think any of the 0.7 branches will get any updates anymore.

**Comment by PiispaH** [comment]
@soininen convinced me to make this new branch for 0.7 where this is fixed: https://github.com/spine-tools/Spine-Toolbox/tree/release-0.7.5 @DillonJ

**Comment by DillonJ** [comment]
Thanks @PiispaH and @soininen
