### ISSUE TITLE
Create a connection between the objects

### ISSUE THREAD

**Issue by mohsen80kia** [spine-tools/Spine-Toolbox#2772]
Hi erevery one,
​I have a problem to connect the following objects together in the updated version of Spine Toolbox
I think, this problem is related to the updated version! Can you help me about this issue? 

![00](https://github.com/spine-tools/Spine-Toolbox/assets/96463232/79df71eb-7520-4f56-80ce-e5832a996fde)

**Comment by PiispaH** [comment]
Hi @mohsen80kia. So you have defined multi-dimensional entities that have for example the "elec" and "powerplant" entites as elements and they are not showing in the graph? What iterms have you have selected from the Entity Tree to produce this image? Is the `Max. entity dimension count` setting sufficiently large for the connections that you are supposed to be seeing?

**Comment by PiispaH** [comment]
I might actually know what is happening here, will try to fix it.

**Comment by PiispaH** [comment]
@mohsen80kia Now after updating Toolbox, is the problem fixed?

**Comment by PiispaH** [comment]
I think the case is closed. Please reopen if it isn't so.
