### ISSUE TITLE
Hide database name column in DB editor

### ISSUE THREAD

**Issue by nelliputkonen** [spine-tools/Spine-Toolbox#2773]
In DB editor, the name of the database is repeated in database column in Entity tree and Entity alternative docs. This is unnecessary when working with a single database. Hide database column when working with a single database.

Other option would be to toggle tree by database (instead of 'root'). This option would also allow to view multiple databases in the same editor tab, but I suppose this is not a typical use case, and would therefore opt for the first suggestion.

There was a suggestion to also get rid of 'root', but I think it's used when filtering Entity graph and therefore serves a purpose. Using the database name instead of 'root' might be more refined option.

**Comment by soininen** [comment]
@PiispaH You may want to check [QHeaderView.hideSection()](https://doc.qt.io/qt-6/qheaderview.html#hideSection)

**Comment by DillonJ** [comment]
Definitely like the idea to hide database name... seems also nice to replace root with the database name.
