### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by vipison** [spine-tools/Spine-Toolbox#2780]
![image](https://github.com/spine-tools/spine-items/assets/169991748/fe899425-1564-44de-a506-a0c39c5b4fe1)

Hi, I have basic problems with Spine.
I have tried to follow the tutorial with the simplest python script I can (only print ; see attachment) but even that does not work.
Moreover, I don’t see the part ‘Project’ at the left side of the Spine Toolbox Tool as it should be.
Where could the problem come from ?
Thanks !

**Comment by PekkaSavolainen** [comment]
Fixed a bug (#2781) related to this issue.

**Comment by vipison** [comment]
Great ! Thanks a lot !

**Comment by vipison** [comment]
It worked but with an input file, the same problem..
![image](https://github.com/spine-tools/Spine-Toolbox/assets/169991748/0e1cefd7-cf4f-4a5b-82f6-ce2426a1af4c)

**Comment by vipison** [comment]
![image](https://github.com/spine-tools/Spine-Toolbox/assets/169991748/4e1c4de9-577a-41db-8a98-54523d25a4af)

**Comment by soininen** [comment]
Check the Traceback in the Python Console down right: your Test240516 cannot find a file named `input.txt`. Indeed, your input file is called `input240516.txt`. Try renaming the file or modify the Python script of Test240516 so that the file names match.

**Comment by vipison** [comment]
Of course.. thanks !

**Comment by soininen** [comment]
I guess this one has been resolved. Feel free to reopen if there is still something to the Getting Started tutorial.

**Comment by vipison** [comment]
Yes, thanks a lot for the quick reactions even to the (stupid) questions..
