### ISSUE TITLE
Julia Installer wizard does not work in Windows bundle

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2797]
Using the Julia Installer from Toolbox Settings when on [Windows bundle](https://spine-tools.github.io/Downloads/) gives this error in Julia Installer's log:

```
Julia installation started
$ Spine Toolbox\_internal\Python\python.exe -m jill install --confirm --install_dir Ö:\julias --symlink_dir Ö:\julias\bin

Spine Toolbox\_internal\Python\python.exe: No module named jill

Julia installation failed
```

The error is expected because the bundle comes with a barebones embeddable Python which does not have any of Toolbox dependencies installed. Possible fixes:

1. Call `jill` directly from Python.
2. Try installing `jill` into the embeddable Python environment. I doubt this is feasible
3. Hide the **Install Julia** button on Windows. It is both [recommended](https://www.julialang.org/downloads/) and easy to install Julia from Windows store.

Reported by @nelliputkonen

**Comment by DillonJ** [comment]
If at all possible, it would be great if there was a bundle solution for SpineOpt users. While I appreciate there are complexities, it feels like having to install Julia saperately and manually is defeating the purpose. Would this also mean that there are other manual steps required back in toolbox to point to the julia installation?

**Comment by nelliputkonen** [comment]
Completely agree with @DillonJ, it would be wonderful for the user if there could be a bundle solution, so the user only needs to install SpineOpt via Toolbox and Julia is handled in the background!

**Comment by soininen** [comment]
> Would this also mean that there are other manual steps required back in toolbox to point to the julia installation?

Toolbox picks up Julia automatically if it finds it in the `PATH` environment variable. Otherwise, you must do it manually.

It is possible to add any files into the bundle so we could try embedding Julia *and* SpineOpt into a special Toolbox `.zip` bundle. The biggest hurdle would probably be the embedded Julia: it has to be "relocatable", that is, it has to be possible to start Julia from the unzipped directory so there cannot be any hard-coded path in the Julia package. Relocatability was exactly the reason why we ended up using the special "embeddable" Python instead of a full-blown installation in the current Toolbox bundles.

In any case, bundling Julia and SpineOpt with Toolbox is a topic for another issue. Anyone interested in that could open one.

**Comment by nelliputkonen** [comment]
I can do it :)

**Comment by soininen** [comment]
I am not saying I do not have interest in such bundles --- on the contrary I would love to see such easy-to-install packages for SpineOpt and for FlexTool, too.

**Comment by PekkaSavolainen** [comment]
Done by implementing option 2 in the issue description.
