### ISSUE TITLE
Activating and deactivating scenario filters in db breaks graph view

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2820]
1. Activate an scenario filter is applied from the **Filter** in db editor toolbar.
2. Deactivate the filter so that no filters are active.
3. Select anything from the **Entity tree** -> nothing will draw

All of the other dock widgets seem to be responding after the filter manipulation, but the graph view seems to get stuck on showing a whole lot of nothing.

**Comment by jkiviluo** [comment]
At the moment, filter is broken all together. But filtering using the scenario tree works fine, so maybe we should get of this redundancy that's not working anyway.
