### ISSUE TITLE
Entity tree clears when adding new entity

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2828]
1. In a database with class A that has entities and class B that doesn't, enable *Hide empty classes*
2. Add an entity to the db through the *Entity alternative* -table. -> **Entity tree** is now completely empty

**Comment by e-zaline** [comment]
I don't know if it is the same issue because I am working with importers, but I do have a mismatch between my entity tree and my actual entities:
 
<img width="728" alt="image" src="https://github.com/spine-tools/Spine-Toolbox/assets/62605130/24c764f9-5700-4490-94f7-a7cd4a6203d0">

**Comment by PiispaH** [comment]
Do you have a way to reproduce the mismatch in your image @e-zaline?

**Comment by jkiviluo** [comment]
I think this could have been fixed with recent updates - the issue was probably related to the improper handling of the tabs. If the issue pops up again, please re-open.
