### ISSUE TITLE
Results database does not show parameter values

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2833]
Results database (FlexTool) does not show parameter values even though they exist. (File size+ They can be exported to excel)
The entities are showing.

![image](https://github.com/spine-tools/Spine-Toolbox/assets/84875787/1c9b60a1-13a7-4535-8715-bac6cc34c282)

**Comment by PiispaH** [comment]
Fixed by reverting one previous commit.
