### ISSUE TITLE
Dock widgets not visisible

### ISSUE THREAD

**Issue by luciacip** [spine-tools/Spine-Toolbox#2839]
The dock widgets are not visible although they are active. Also after View -> Dock Widgets -> Restore dock widgets. 
<img width="959" alt="Spine" src="https://github.com/spine-tools/Spine-Toolbox/assets/146172227/e294d0a7-229e-4db8-a257-79f2fca1421e">

**Comment by PiispaH** [comment]
Hi @luciacip. Are you using a bundled Windows version of Toolbox or have you cloned the repository using git? Right clicking on the menubar next to *Help* and toggling the docks from there doesn't help either?

**Comment by luciacip** [comment]
Hey, I'm using the bundled Windows version and no, with the right click it doesn't work either unfortunately. Should I try cloning the repository?

**Comment by PiispaH** [comment]
Yeah, you probably have to try that if the other bundles don't work either on your machine. I'm not able to replicate this issue on my computer.

**Comment by hannesfelipe** [comment]
@PekkaSavolainen @PiispaH I work together with @luciacip and could replicate the issue. It appears when you run an optimization and while running, moving the dock widgets to another position. If you then say "restore" you get the blank screen and it is impossible to get the dock widgets back. Also the reinstallation (independent on the way of installing it) of spinetoolbox is not solving the problem.

**Comment by hannesfelipe** [comment]
@PekkaSavolainen @PiispaH we found a solution. The de- and re-installation cannot solve the bug. You must delete all files from the registry in HKEY_CURRENT_USER\Software\SpineProject\Spine Toolbox. 
I hope we do not create this problem again, but do you have an idea wy this can happen when restore the Dock Widgets while running the optimization?

**Comment by PekkaSavolainen** [comment]
I managed to replicate this once but cannot do it again after resetting the Spine Toolbox settings in registry. I think I did it by moving the Properties over the Design View and then clicked Restore Dock Widgets **while execution is in progress**. Can you (@hannesfelipe) replicate it a second time? Any idea on what docks you moved and where?

**Comment by PekkaSavolainen** [comment]
I can reproduce it consistently now. Will fix.

**Comment by hannesfelipe** [comment]
@PekkaSavolainen thank you and I hope I don't have to replicate it once again (I also forgot what docks I moved and where).

**Comment by PekkaSavolainen** [comment]
Done.
