### ISSUE TITLE
Graph view does not show

### ISSUE THREAD

**Issue by e-zaline** [spine-tools/Spine-Toolbox#2866]
When I click on "Graph", it briefly shows something for half a second but dissapear immediately - so I cannot see the Graph view.
It does not happen with all databases, but frequently.

**Comment by PiispaH** [comment]
Does it show if you enable the view from View->Entity graph or press the Reset docs button and then select the Graph again @e-zaline?

**Comment by jkiviluo** [comment]
Any message in the console? 

When did this behaviour start? Henrik merged an update to the graph view on Friday, which allows to filter the graph view by choosing an alternative(s).

**Comment by PiispaH** [comment]
So this still keeps happening after pressing the reset button @e-zaline?

**Comment by e-zaline** [comment]
It actually depends what the button graph is supposed to do. Should the graph appear and disappear when I click/unclick it, or is "Reset Docs" the mean of making the graph view disappear?

For now, when I click Reset Docs and the Graph, the Graph view appears. When I click again Graph, my screen flickers but the graph does not disappear.

**Comment by PiispaH** [comment]
At the moment, the `Reset docs` button resets the layout of every view and automatically selects the `Table` view. So the graph should disappear when it is clicked. If you have already pressed `Graph` and press it again, it just reloads the current view.

**Comment by PiispaH** [comment]
I guess you had deleted the Entity graph dock widget from the `Graph` view. Then when you select the `Graph` again from the menubar, it initially loads the default layout for that view. After that it applies the modifications the user has made to that view (in this case removing the Entity graph). A bit confusing I would say
