### ISSUE TITLE
Execute project shortcut F5

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2887]
Now the graph view uses F5 as a shortcut to rebuild the graph. F5 is currently also a shortcut to execute the entire project. Maybe it is not a good idea to have the same key for both of these actions, since executing the whole project can be a bit problematic in some cases.

**Comment by jkiviluo** [comment]
F5 is a generic refresh shortcut so we should keep that. F9 is often used as an execution shortcut - I would consider switching to that. Also, executing whole project is rare (to me at least). I would use F9 to execute selection and shift-F9 to execute project.

**Comment by ptsavol** [comment]
Done.
