### ISSUE TITLE
Stopping Tool execution makes Toolbox very slow and choppy

### ISSUE THREAD

**Issue by PiispaH** [spine-tools/Spine-Toolbox#2892]
[Here](https://github.com/user-attachments/files/16230584/execution_slowdown.zip) is a project that has two tools, a link that connects them and one self loop on the first tool. The loop has a nonsense condition and actually never stops running. If the project is executed and after only a few executions of the loop, the execution is stopped, Toolbox becomes very choppy.

Switching the project does nothing to help (doesn't always even open the other project, sometimes just freezes). Seems that  the longer the loop is let to do its thing, the more unresponsive Toolbox becomes.

While the execution is going on, Toolbox has no issues. Instantly when the execution is stopped, the problem arises.

**Comment by soininen** [comment]
This has been fixed by spine-tools/spine-engine#150
