### ISSUE TITLE
"Fatal error from pip prevented installation." on Kaggle environment 

### ISSUE THREAD

**Issue by DenizCanELCI** [spine-tools/Spine-Toolbox#2911]
I got the following error when I run "!python -m pipx install git+https://github.com/spine-tools/spinetoolbox-dev" on Kaggle environment:

"""
Fatal error from pip prevented installation. Full pip output in file:-tools/...
    /root/.local/state/pipx/log/cmd_2024-08-03_18.28.09_pip_errors.log

pip seemed to fail to build package:
    psycopg2

Some possibly relevant errors from pip install:
        Error: pg_config executable not found.

Error installing spinetoolbox-dev from spec
'git+https://github.com/spine-tools/spinetoolbox-dev'. """

**Comment by PekkaSavolainen** [comment]
Which Python? If 3.12, try 3.11.

**Comment by DenizCanELCI** [comment]
I kinda lost the notebook which I tried. I can close the issue if you say it does work in python 3.12

**Comment by jkiviluo** [comment]
I'm closing this, since there seems to be no clear fix to do. If something like this repeats, would be good to know. Thanks @DenizCanELCI
