### ISSUE TITLE
Can't run spinetoolbox after upgrade to newest version

### ISSUE THREAD

**Issue by JanaTerem** [spine-tools/Spine-Toolbox#2919]
After the 21.08.2024 installation of new version of SpineTool, SpineOpt and SpineInterface the error occur:
[error.docx](https://github.com/user-attachments/files/16690379/error.docx)

SpineToolbox: 0.8.2
Julia: 1.10.0
Pyton: 3.11.9

**Comment by soininen** [comment]
Your database is newer than what is supported by your Toolbox. You can either reinstall [Toolbox from sources using Git](https://github.com/spine-tools/Spine-Toolbox?tab=readme-ov-file#installation-from-sources-using-git) or wait until we release Toolbox 0.8.3 which hopefully happens in a week.

**Comment by JanaTerem** [comment]
Thank you!

**Comment by soininen** [comment]
Toolbox 0.8.3 has been released. If you have installed Toolbox using `pip` or `pipx`, please update, and let us know if the update works.

**Comment by soininen** [comment]
As the error message states, you need to update SpineInterface as well. The exact procedure depends on how you installed SpineOpt, but [this](https://spine-tools.github.io/SpineOpt.jl/latest/getting_started/installation/#Upgrade-2) may prove helpful.

**Comment by JanaTerem** [comment]
Still have the troubles:

Execution started at 2024-08-28T12:38:38.468
WARNING: using JuMP.Parameter in module SpineInterface conflicts with an existing identifier.
Preparing SpineOpt for sqlite:///C:\Users\Teremranova\Downloads\SignAture_2020_MAIN.sqlite?spinedbfilter=cfg%3Ascenario%3AMAIN...
ERROR: LoadError: version mismatch: DB server requires client version 8, whereas current version is 6; please update SpineInterface Stacktrace

I upgraded SpineOpt through Julia

**Comment by soininen** [comment]
Please see [here](https://github.com/spine-tools/SpineOpt.jl?tab=readme-ov-file#loudspeaker-community-and-how-to-ask-help-rocket) how to get in touch with SpineOpt experts. I am sure they can be of musch more help than us Toolbox developers.
