### ISSUE TITLE
Changing alternative order in scenario tree causes error

### ISSUE THREAD

**Issue by ArttuTupala** [spine-tools/Spine-Toolbox#2923]
Changing alternative order in scenario tree causes error on commit.
Happens only when making more than one change in order before commit. 

![image](https://github.com/user-attachments/assets/7bacad35-add7-49a2-929b-7a515600adac)

**Comment by soininen** [comment]
This has probably been fixed by 6ea8fbfd7611d9a2df88f1c3a3eb2f276a071e8a. Can you update requirements and check if that is the case?

**Comment by ArttuTupala** [comment]
Solved the issue
