### ISSUE TITLE
Decrease size of toolbar items/text spacing

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2964]
When using toolbar vertically, the icons are bit tall and some items are not directly visible since room runs out (especially on laptop screens). Solution would be to decrease icon size, decrease vertical spacing between texts and check that item name does not extend to multiple rows (replace with ... if doesn't fit in the bar horizontall).

**Comment by ptsavol** [comment]
Done. Please reopen if necessary.
