### ISSUE TITLE
Remove the Troubleshooting section when SpineOpt installation fails

### ISSUE THREAD

**Issue by ptsavol** [spine-tools/Spine-Toolbox#2973]
When clicking the `Add/Update SpineOpt` button in File->Settings->Tools and going through the install wizard, if SpineOpt installation fails for any reason, a troubleshooting page opens up, where users **must** select an option to continue. These options were written a long time ago for a Julia that SpineOpt probably does not support anymore and the one for Windows mentions Windows 7. After user selects an option from the troubleshooting page, a new page opens up where we try to fix something automatically (one of these fixes is to Reset Julia Registry), and I'm not sure if we should be doing that for users that don't know what they are doing. I propose we remove the troubleshooting section and replace it with page in the wizard that tells the user what to try next:

1. Try the Add/update SpineOpt button again
2. Go to Terminal and open Julia. Do `import Pkg; Pkg.add_registry(SpineOptRegistry)...; Pkg.add("SpineOpt")` See also Installation section in SpineOpt Documentation (link)
3. Open an issue on Toolbox's Github page and post the error message or traceback (link)

**Comment by jkiviluo** [comment]
Does not reproduce. Ask if there was a traceback.

**Comment by ptsavol** [comment]
I did not dare to remove the troubleshooting section because it was quite good actually. It just needed a bit of refreshing.
