### ISSUE TITLE
Support PySide6 6.8.x

### ISSUE THREAD

**Issue by ptsavol** [spine-tools/Spine-Toolbox#2980]
Toolbox crashes on PySide6 6.8.0. The crash happens in qtpy's QtGui.py line 120 `from PySide6.QtGui import *`, which is called by qtconsole's util.py line `from qtpy import QtCore, QtGui`, which is called in our code in file jupyter_console_widget.py line `from qtconsole.client import QtKernelClient`. I don't think we can do anything about it but to wait for a new version of qtpy or PySide 6.8.1.

Related to #2979.

**Comment by soininen** [comment]
Looks like the issue with 6.8.0.1 is that it segfaults when we e.g. set the text for `QGraphicsTextItem`s in icons on Design view --- i.e. it is a bug in PySide6's text handling/rendering.

**Comment by ptsavol** [comment]
Done. It is possible that I missed some signal-slot issues that need to be handled for the new PySide6 version so please report crashes/odd behavior post haste.
