### ISSUE TITLE
Workflow editor: Properties widget has a vertical height limit

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#3012]
Properties widget needs to have a vertical scroll bar, so that it's height can be smaller. Now, on small screens, it prevents changing the size of the widget (and other widgets) in a way that makes the workflow editor difficult to use.

**Comment by ptsavol** [comment]
I have implemented this in my User/Design Mode branch. Maybe I should separate it to another branch so we can have in this master soon.

**Comment by jkiviluo** [comment]
Great. If you think it would take more than 10 minutes, don't bother. It's not that bad (one can workaround it by moving the properties window fully to its own vertical slot.

**Comment by ptsavol** [comment]
You should be able to resize the main window and the dock widgets more freely now. It took a bit longer than 10 minutes but I think it was to good to separate this fix from an unrelated branch.

**Comment by ptsavol** [comment]
Found a bug here. The 'Color properties widget' setting does not work anymore.
