### ISSUE TITLE
Path references broken when opening the FlexTool project from FlexTool+Toolbox bundle

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#3015]
There is an experimental Toolbox bundle (available e.g. [here](https://github.com/jkiviluo/Spine-Toolbox/releases)) that contains the [FlexTool](https://github.com/irena-flextool/flextool) model as Toolbox project. After opening the project using the bundled Toolbox, file references in Data Connections are apparently broken, though refreshing the references fixes the issue. Also, Data stores cannot seem to find their `.sqlite` files.

Reported by @jkiviluo

**Comment by jkiviluo** [comment]
This was most likely not a real issue - something else was going wrong, since it doesn't repeat anymore. Can be opened if need be.
