### ISSUE TITLE
Not possible to execute main programs from a folder

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#3020]
Sometimes the root folder of an execution should be parent of the folder where the main program is. E.g. structure

src --> main_program
input --> input files

Trying to use src/main.py for main program fails (the error message is not very helpful).

Relates to having actual root folder: https://github.com/spine-tools/Spine-Toolbox/issues/2958#issuecomment-2456837610

**Comment by ptsavol** [comment]
Related to #799.
